/*
Credoxa Events API

Testing LifecycleAlertsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package credoxaevents

import (
	"context"
	openapiclient "github.com/alhiedi/credoxa-go/events"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_credoxaevents_LifecycleAlertsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LifecycleAlertsAPIService OperatorSaasLifecycleAlertsActionCreate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.LifecycleAlertsAPI.OperatorSaasLifecycleAlertsActionCreate(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LifecycleAlertsAPIService OperatorSaasLifecycleAlertsActionRetrieve", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.LifecycleAlertsAPI.OperatorSaasLifecycleAlertsActionRetrieve(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LifecycleAlertsAPIService OperatorSaasLifecycleAlertsList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LifecycleAlertsAPI.OperatorSaasLifecycleAlertsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LifecycleAlertsAPIService OperatorSaasLifecycleAlertsRetrieve", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var alertId string

		resp, httpRes, err := apiClient.LifecycleAlertsAPI.OperatorSaasLifecycleAlertsRetrieve(context.Background(), alertId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
