/*
Credoxa Events API

Testing OperatorAnalyticsRecoveryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package credoxaevents

import (
	"context"
	openapiclient "github.com/alhiedi/credoxa-go/events"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_credoxaevents_OperatorAnalyticsRecoveryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsEventDeadLetters", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsEventDeadLetters(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsLateArrivalRepair", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsLateArrivalRepair(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsRebuildList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsRebuildList(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsRecoveryLeases", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsRecoveryLeases(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsRecoveryList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsRecoveryList(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsRepairAction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var action string
		var repairId string

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsRepairAction(context.Background(), action, repairId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatorAnalyticsRecoveryAPIService OperatorAnalyticsRepairDeadLetters", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OperatorAnalyticsRecoveryAPI.OperatorAnalyticsRepairDeadLetters(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
