/*
Credoxa Events API

Testing SaaSAnalyticsOperatorAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package credoxaevents

import (
	"context"
	openapiclient "github.com/alhiedi/credoxa-go/events"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_credoxaevents_SaaSAnalyticsOperatorAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SaaSAnalyticsOperatorAPIService SaasAnalyticsRuntimeControl", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SaaSAnalyticsOperatorAPI.SaasAnalyticsRuntimeControl(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
