/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type RetentionAPI interface {

	/*
		RetentionPoliciesCreate Method for RetentionPoliciesCreate

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiRetentionPoliciesCreateRequest
	*/
	RetentionPoliciesCreate(ctx context.Context) ApiRetentionPoliciesCreateRequest

	// RetentionPoliciesCreateExecute executes the request
	//  @return RetentionPolicyRead
	RetentionPoliciesCreateExecute(r ApiRetentionPoliciesCreateRequest) (*RetentionPolicyRead, *http.Response, error)

	/*
		RetentionPoliciesDestroy Method for RetentionPoliciesDestroy

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param policyId
		@return ApiRetentionPoliciesDestroyRequest
	*/
	RetentionPoliciesDestroy(ctx context.Context, policyId string) ApiRetentionPoliciesDestroyRequest

	// RetentionPoliciesDestroyExecute executes the request
	RetentionPoliciesDestroyExecute(r ApiRetentionPoliciesDestroyRequest) (*http.Response, error)

	/*
		RetentionPoliciesList Method for RetentionPoliciesList

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiRetentionPoliciesListRequest
	*/
	RetentionPoliciesList(ctx context.Context) ApiRetentionPoliciesListRequest

	// RetentionPoliciesListExecute executes the request
	//  @return []RetentionPolicyRead
	RetentionPoliciesListExecute(r ApiRetentionPoliciesListRequest) ([]RetentionPolicyRead, *http.Response, error)

	/*
		RetentionPoliciesPartialUpdate Method for RetentionPoliciesPartialUpdate

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param policyId
		@return ApiRetentionPoliciesPartialUpdateRequest
	*/
	RetentionPoliciesPartialUpdate(ctx context.Context, policyId string) ApiRetentionPoliciesPartialUpdateRequest

	// RetentionPoliciesPartialUpdateExecute executes the request
	//  @return RetentionPolicyRead
	RetentionPoliciesPartialUpdateExecute(r ApiRetentionPoliciesPartialUpdateRequest) (*RetentionPolicyRead, *http.Response, error)

	/*
		RetentionPoliciesRetrieve Method for RetentionPoliciesRetrieve

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param policyId
		@return ApiRetentionPoliciesRetrieveRequest
	*/
	RetentionPoliciesRetrieve(ctx context.Context, policyId string) ApiRetentionPoliciesRetrieveRequest

	// RetentionPoliciesRetrieveExecute executes the request
	//  @return RetentionPolicyRead
	RetentionPoliciesRetrieveExecute(r ApiRetentionPoliciesRetrieveRequest) (*RetentionPolicyRead, *http.Response, error)

	/*
		RetentionPoliciesUpdate Method for RetentionPoliciesUpdate

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param policyId
		@return ApiRetentionPoliciesUpdateRequest
	*/
	RetentionPoliciesUpdate(ctx context.Context, policyId string) ApiRetentionPoliciesUpdateRequest

	// RetentionPoliciesUpdateExecute executes the request
	//  @return RetentionPolicyRead
	RetentionPoliciesUpdateExecute(r ApiRetentionPoliciesUpdateRequest) (*RetentionPolicyRead, *http.Response, error)

	/*
		RetentionPreviewCreate Method for RetentionPreviewCreate

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiRetentionPreviewCreateRequest
	*/
	RetentionPreviewCreate(ctx context.Context) ApiRetentionPreviewCreateRequest

	// RetentionPreviewCreateExecute executes the request
	//  @return RetentionExplanation
	RetentionPreviewCreateExecute(r ApiRetentionPreviewCreateRequest) (*RetentionExplanation, *http.Response, error)
}

// RetentionAPIService RetentionAPI service
type RetentionAPIService service

type ApiRetentionPoliciesCreateRequest struct {
	ctx                         context.Context
	ApiService                  RetentionAPI
	retentionPolicyWriteRequest *RetentionPolicyWriteRequest
}

func (r ApiRetentionPoliciesCreateRequest) RetentionPolicyWriteRequest(retentionPolicyWriteRequest RetentionPolicyWriteRequest) ApiRetentionPoliciesCreateRequest {
	r.retentionPolicyWriteRequest = &retentionPolicyWriteRequest
	return r
}

func (r ApiRetentionPoliciesCreateRequest) Execute() (*RetentionPolicyRead, *http.Response, error) {
	return r.ApiService.RetentionPoliciesCreateExecute(r)
}

/*
RetentionPoliciesCreate Method for RetentionPoliciesCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRetentionPoliciesCreateRequest
*/
func (a *RetentionAPIService) RetentionPoliciesCreate(ctx context.Context) ApiRetentionPoliciesCreateRequest {
	return ApiRetentionPoliciesCreateRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return RetentionPolicyRead
func (a *RetentionAPIService) RetentionPoliciesCreateExecute(r ApiRetentionPoliciesCreateRequest) (*RetentionPolicyRead, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RetentionPolicyRead
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.retentionPolicyWriteRequest == nil {
		return localVarReturnValue, nil, reportError("retentionPolicyWriteRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.retentionPolicyWriteRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRetentionPoliciesDestroyRequest struct {
	ctx        context.Context
	ApiService RetentionAPI
	policyId   string
}

func (r ApiRetentionPoliciesDestroyRequest) Execute() (*http.Response, error) {
	return r.ApiService.RetentionPoliciesDestroyExecute(r)
}

/*
RetentionPoliciesDestroy Method for RetentionPoliciesDestroy

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param policyId
	@return ApiRetentionPoliciesDestroyRequest
*/
func (a *RetentionAPIService) RetentionPoliciesDestroy(ctx context.Context, policyId string) ApiRetentionPoliciesDestroyRequest {
	return ApiRetentionPoliciesDestroyRequest{
		ApiService: a,
		ctx:        ctx,
		policyId:   policyId,
	}
}

// Execute executes the request
func (a *RetentionAPIService) RetentionPoliciesDestroyExecute(r ApiRetentionPoliciesDestroyRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesDestroy")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/{policy_id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"policy_id"+"}", strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(url.PathEscape(parameterValueToString(r.policyId, "policyId")), ":", "%3A"), "@", "%40"), "$", "%24"), "&", "%26"), "+", "%2B"), "=", "%3D"), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiRetentionPoliciesListRequest struct {
	ctx        context.Context
	ApiService RetentionAPI
}

func (r ApiRetentionPoliciesListRequest) Execute() ([]RetentionPolicyRead, *http.Response, error) {
	return r.ApiService.RetentionPoliciesListExecute(r)
}

/*
RetentionPoliciesList Method for RetentionPoliciesList

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRetentionPoliciesListRequest
*/
func (a *RetentionAPIService) RetentionPoliciesList(ctx context.Context) ApiRetentionPoliciesListRequest {
	return ApiRetentionPoliciesListRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []RetentionPolicyRead
func (a *RetentionAPIService) RetentionPoliciesListExecute(r ApiRetentionPoliciesListRequest) ([]RetentionPolicyRead, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []RetentionPolicyRead
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRetentionPoliciesPartialUpdateRequest struct {
	ctx                                context.Context
	ApiService                         RetentionAPI
	policyId                           string
	patchedRetentionPolicyWriteRequest *PatchedRetentionPolicyWriteRequest
}

func (r ApiRetentionPoliciesPartialUpdateRequest) PatchedRetentionPolicyWriteRequest(patchedRetentionPolicyWriteRequest PatchedRetentionPolicyWriteRequest) ApiRetentionPoliciesPartialUpdateRequest {
	r.patchedRetentionPolicyWriteRequest = &patchedRetentionPolicyWriteRequest
	return r
}

func (r ApiRetentionPoliciesPartialUpdateRequest) Execute() (*RetentionPolicyRead, *http.Response, error) {
	return r.ApiService.RetentionPoliciesPartialUpdateExecute(r)
}

/*
RetentionPoliciesPartialUpdate Method for RetentionPoliciesPartialUpdate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param policyId
	@return ApiRetentionPoliciesPartialUpdateRequest
*/
func (a *RetentionAPIService) RetentionPoliciesPartialUpdate(ctx context.Context, policyId string) ApiRetentionPoliciesPartialUpdateRequest {
	return ApiRetentionPoliciesPartialUpdateRequest{
		ApiService: a,
		ctx:        ctx,
		policyId:   policyId,
	}
}

// Execute executes the request
//
//	@return RetentionPolicyRead
func (a *RetentionAPIService) RetentionPoliciesPartialUpdateExecute(r ApiRetentionPoliciesPartialUpdateRequest) (*RetentionPolicyRead, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RetentionPolicyRead
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesPartialUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/{policy_id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"policy_id"+"}", strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(url.PathEscape(parameterValueToString(r.policyId, "policyId")), ":", "%3A"), "@", "%40"), "$", "%24"), "&", "%26"), "+", "%2B"), "=", "%3D"), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	if r.patchedRetentionPolicyWriteRequest != nil {
		localVarPostBody = r.patchedRetentionPolicyWriteRequest
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRetentionPoliciesRetrieveRequest struct {
	ctx        context.Context
	ApiService RetentionAPI
	policyId   string
}

func (r ApiRetentionPoliciesRetrieveRequest) Execute() (*RetentionPolicyRead, *http.Response, error) {
	return r.ApiService.RetentionPoliciesRetrieveExecute(r)
}

/*
RetentionPoliciesRetrieve Method for RetentionPoliciesRetrieve

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param policyId
	@return ApiRetentionPoliciesRetrieveRequest
*/
func (a *RetentionAPIService) RetentionPoliciesRetrieve(ctx context.Context, policyId string) ApiRetentionPoliciesRetrieveRequest {
	return ApiRetentionPoliciesRetrieveRequest{
		ApiService: a,
		ctx:        ctx,
		policyId:   policyId,
	}
}

// Execute executes the request
//
//	@return RetentionPolicyRead
func (a *RetentionAPIService) RetentionPoliciesRetrieveExecute(r ApiRetentionPoliciesRetrieveRequest) (*RetentionPolicyRead, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RetentionPolicyRead
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesRetrieve")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/{policy_id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"policy_id"+"}", strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(url.PathEscape(parameterValueToString(r.policyId, "policyId")), ":", "%3A"), "@", "%40"), "$", "%24"), "&", "%26"), "+", "%2B"), "=", "%3D"), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRetentionPoliciesUpdateRequest struct {
	ctx                         context.Context
	ApiService                  RetentionAPI
	policyId                    string
	retentionPolicyWriteRequest *RetentionPolicyWriteRequest
}

func (r ApiRetentionPoliciesUpdateRequest) RetentionPolicyWriteRequest(retentionPolicyWriteRequest RetentionPolicyWriteRequest) ApiRetentionPoliciesUpdateRequest {
	r.retentionPolicyWriteRequest = &retentionPolicyWriteRequest
	return r
}

func (r ApiRetentionPoliciesUpdateRequest) Execute() (*RetentionPolicyRead, *http.Response, error) {
	return r.ApiService.RetentionPoliciesUpdateExecute(r)
}

/*
RetentionPoliciesUpdate Method for RetentionPoliciesUpdate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param policyId
	@return ApiRetentionPoliciesUpdateRequest
*/
func (a *RetentionAPIService) RetentionPoliciesUpdate(ctx context.Context, policyId string) ApiRetentionPoliciesUpdateRequest {
	return ApiRetentionPoliciesUpdateRequest{
		ApiService: a,
		ctx:        ctx,
		policyId:   policyId,
	}
}

// Execute executes the request
//
//	@return RetentionPolicyRead
func (a *RetentionAPIService) RetentionPoliciesUpdateExecute(r ApiRetentionPoliciesUpdateRequest) (*RetentionPolicyRead, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RetentionPolicyRead
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPoliciesUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/policies/{policy_id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"policy_id"+"}", strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(url.PathEscape(parameterValueToString(r.policyId, "policyId")), ":", "%3A"), "@", "%40"), "$", "%24"), "&", "%26"), "+", "%2B"), "=", "%3D"), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.retentionPolicyWriteRequest == nil {
		return localVarReturnValue, nil, reportError("retentionPolicyWriteRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.retentionPolicyWriteRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRetentionPreviewCreateRequest struct {
	ctx                          context.Context
	ApiService                   RetentionAPI
	retentionPreviewInputRequest *RetentionPreviewInputRequest
}

func (r ApiRetentionPreviewCreateRequest) RetentionPreviewInputRequest(retentionPreviewInputRequest RetentionPreviewInputRequest) ApiRetentionPreviewCreateRequest {
	r.retentionPreviewInputRequest = &retentionPreviewInputRequest
	return r
}

func (r ApiRetentionPreviewCreateRequest) Execute() (*RetentionExplanation, *http.Response, error) {
	return r.ApiService.RetentionPreviewCreateExecute(r)
}

/*
RetentionPreviewCreate Method for RetentionPreviewCreate

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRetentionPreviewCreateRequest
*/
func (a *RetentionAPIService) RetentionPreviewCreate(ctx context.Context) ApiRetentionPreviewCreateRequest {
	return ApiRetentionPreviewCreateRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return RetentionExplanation
func (a *RetentionAPIService) RetentionPreviewCreateExecute(r ApiRetentionPreviewCreateRequest) (*RetentionExplanation, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *RetentionExplanation
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetentionAPIService.RetentionPreviewCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/retention/preview/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.retentionPreviewInputRequest == nil {
		return localVarReturnValue, nil, reportError("retentionPreviewInputRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.retentionPreviewInputRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["cookieAuth"]; ok {
				localVarHeaderParams["Cookie"] = "sessionid=" + apiKey.Key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
