/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RecoveryEscalationEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoveryEscalationEvent{}

// RecoveryEscalationEvent struct for RecoveryEscalationEvent
type RecoveryEscalationEvent struct {
	Id         string                               `json:"id"`
	Sequence   int64                                `json:"sequence"`
	EventType  RecoveryEscalationEventEventTypeEnum `json:"event_type"`
	Actor      NullableString                       `json:"actor,omitempty"`
	Payload    interface{}                          `json:"payload,omitempty"`
	OccurredAt *time.Time                           `json:"occurred_at,omitempty"`
	CreatedAt  time.Time                            `json:"created_at"`
}

type _RecoveryEscalationEvent RecoveryEscalationEvent

// NewRecoveryEscalationEvent instantiates a new RecoveryEscalationEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoveryEscalationEvent(id string, sequence int64, eventType RecoveryEscalationEventEventTypeEnum, createdAt time.Time) *RecoveryEscalationEvent {
	this := RecoveryEscalationEvent{}
	this.Id = id
	this.Sequence = sequence
	this.EventType = eventType
	this.CreatedAt = createdAt
	return &this
}

// NewRecoveryEscalationEventWithDefaults instantiates a new RecoveryEscalationEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoveryEscalationEventWithDefaults() *RecoveryEscalationEvent {
	this := RecoveryEscalationEvent{}
	return &this
}

// GetId returns the Id field value
func (o *RecoveryEscalationEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RecoveryEscalationEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RecoveryEscalationEvent) SetId(v string) {
	o.Id = v
}

// GetSequence returns the Sequence field value
func (o *RecoveryEscalationEvent) GetSequence() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value
// and a boolean to check if the value has been set.
func (o *RecoveryEscalationEvent) GetSequenceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sequence, true
}

// SetSequence sets field value
func (o *RecoveryEscalationEvent) SetSequence(v int64) {
	o.Sequence = v
}

// GetEventType returns the EventType field value
func (o *RecoveryEscalationEvent) GetEventType() RecoveryEscalationEventEventTypeEnum {
	if o == nil {
		var ret RecoveryEscalationEventEventTypeEnum
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *RecoveryEscalationEvent) GetEventTypeOk() (*RecoveryEscalationEventEventTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *RecoveryEscalationEvent) SetEventType(v RecoveryEscalationEventEventTypeEnum) {
	o.EventType = v
}

// GetActor returns the Actor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecoveryEscalationEvent) GetActor() string {
	if o == nil || IsNil(o.Actor.Get()) {
		var ret string
		return ret
	}
	return *o.Actor.Get()
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecoveryEscalationEvent) GetActorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actor.Get(), o.Actor.IsSet()
}

// HasActor returns a boolean if a field has been set.
func (o *RecoveryEscalationEvent) HasActor() bool {
	if o != nil && o.Actor.IsSet() {
		return true
	}

	return false
}

// SetActor gets a reference to the given NullableString and assigns it to the Actor field.
func (o *RecoveryEscalationEvent) SetActor(v string) {
	o.Actor.Set(&v)
}

// SetActorNil sets the value for Actor to be an explicit nil
func (o *RecoveryEscalationEvent) SetActorNil() {
	o.Actor.Set(nil)
}

// UnsetActor ensures that no value is present for Actor, not even an explicit nil
func (o *RecoveryEscalationEvent) UnsetActor() {
	o.Actor.Unset()
}

// GetPayload returns the Payload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecoveryEscalationEvent) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecoveryEscalationEvent) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *RecoveryEscalationEvent) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given interface{} and assigns it to the Payload field.
func (o *RecoveryEscalationEvent) SetPayload(v interface{}) {
	o.Payload = v
}

// GetOccurredAt returns the OccurredAt field value if set, zero value otherwise.
func (o *RecoveryEscalationEvent) GetOccurredAt() time.Time {
	if o == nil || IsNil(o.OccurredAt) {
		var ret time.Time
		return ret
	}
	return *o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryEscalationEvent) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OccurredAt) {
		return nil, false
	}
	return o.OccurredAt, true
}

// HasOccurredAt returns a boolean if a field has been set.
func (o *RecoveryEscalationEvent) HasOccurredAt() bool {
	if o != nil && !IsNil(o.OccurredAt) {
		return true
	}

	return false
}

// SetOccurredAt gets a reference to the given time.Time and assigns it to the OccurredAt field.
func (o *RecoveryEscalationEvent) SetOccurredAt(v time.Time) {
	o.OccurredAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RecoveryEscalationEvent) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RecoveryEscalationEvent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RecoveryEscalationEvent) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o RecoveryEscalationEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoveryEscalationEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sequence"] = o.Sequence
	toSerialize["event_type"] = o.EventType
	if o.Actor.IsSet() {
		toSerialize["actor"] = o.Actor.Get()
	}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.OccurredAt) {
		toSerialize["occurred_at"] = o.OccurredAt
	}
	return toSerialize, nil
}

func (o *RecoveryEscalationEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"sequence",
		"event_type",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoveryEscalationEvent := _RecoveryEscalationEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoveryEscalationEvent)

	if err != nil {
		return err
	}

	*o = RecoveryEscalationEvent(varRecoveryEscalationEvent)

	return err
}

type NullableRecoveryEscalationEvent struct {
	value *RecoveryEscalationEvent
	isSet bool
}

func (v NullableRecoveryEscalationEvent) Get() *RecoveryEscalationEvent {
	return v.value
}

func (v *NullableRecoveryEscalationEvent) Set(val *RecoveryEscalationEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryEscalationEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryEscalationEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryEscalationEvent(val *RecoveryEscalationEvent) *NullableRecoveryEscalationEvent {
	return &NullableRecoveryEscalationEvent{value: val, isSet: true}
}

func (v NullableRecoveryEscalationEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryEscalationEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
