/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegionalFailoverExecutionDispatchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionalFailoverExecutionDispatchResponse{}

// RegionalFailoverExecutionDispatchResponse struct for RegionalFailoverExecutionDispatchResponse
type RegionalFailoverExecutionDispatchResponse struct {
	ExecutionId string `json:"execution_id"`
	TaskId      string `json:"task_id"`
	Revision    int32  `json:"revision"`
}

type _RegionalFailoverExecutionDispatchResponse RegionalFailoverExecutionDispatchResponse

// NewRegionalFailoverExecutionDispatchResponse instantiates a new RegionalFailoverExecutionDispatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionalFailoverExecutionDispatchResponse(executionId string, taskId string, revision int32) *RegionalFailoverExecutionDispatchResponse {
	this := RegionalFailoverExecutionDispatchResponse{}
	this.ExecutionId = executionId
	this.TaskId = taskId
	this.Revision = revision
	return &this
}

// NewRegionalFailoverExecutionDispatchResponseWithDefaults instantiates a new RegionalFailoverExecutionDispatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionalFailoverExecutionDispatchResponseWithDefaults() *RegionalFailoverExecutionDispatchResponse {
	this := RegionalFailoverExecutionDispatchResponse{}
	return &this
}

// GetExecutionId returns the ExecutionId field value
func (o *RegionalFailoverExecutionDispatchResponse) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecutionDispatchResponse) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *RegionalFailoverExecutionDispatchResponse) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetTaskId returns the TaskId field value
func (o *RegionalFailoverExecutionDispatchResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecutionDispatchResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *RegionalFailoverExecutionDispatchResponse) SetTaskId(v string) {
	o.TaskId = v
}

// GetRevision returns the Revision field value
func (o *RegionalFailoverExecutionDispatchResponse) GetRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecutionDispatchResponse) GetRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *RegionalFailoverExecutionDispatchResponse) SetRevision(v int32) {
	o.Revision = v
}

func (o RegionalFailoverExecutionDispatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionalFailoverExecutionDispatchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["execution_id"] = o.ExecutionId
	toSerialize["task_id"] = o.TaskId
	toSerialize["revision"] = o.Revision
	return toSerialize, nil
}

func (o *RegionalFailoverExecutionDispatchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"execution_id",
		"task_id",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionalFailoverExecutionDispatchResponse := _RegionalFailoverExecutionDispatchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionalFailoverExecutionDispatchResponse)

	if err != nil {
		return err
	}

	*o = RegionalFailoverExecutionDispatchResponse(varRegionalFailoverExecutionDispatchResponse)

	return err
}

type NullableRegionalFailoverExecutionDispatchResponse struct {
	value *RegionalFailoverExecutionDispatchResponse
	isSet bool
}

func (v NullableRegionalFailoverExecutionDispatchResponse) Get() *RegionalFailoverExecutionDispatchResponse {
	return v.value
}

func (v *NullableRegionalFailoverExecutionDispatchResponse) Set(val *RegionalFailoverExecutionDispatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionalFailoverExecutionDispatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionalFailoverExecutionDispatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionalFailoverExecutionDispatchResponse(val *RegionalFailoverExecutionDispatchResponse) *NullableRegionalFailoverExecutionDispatchResponse {
	return &NullableRegionalFailoverExecutionDispatchResponse{value: val, isSet: true}
}

func (v NullableRegionalFailoverExecutionDispatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionalFailoverExecutionDispatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
