/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RegionalFailoverExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionalFailoverExecution{}

// RegionalFailoverExecution struct for RegionalFailoverExecution
type RegionalFailoverExecution struct {
	Id                         string                           `json:"id"`
	OrganizationId             string                           `json:"organization_id"`
	TopologyId                 string                           `json:"topology_id"`
	TopologyName               string                           `json:"topology_name"`
	SourceRegionId             string                           `json:"source_region_id"`
	SourceRegionCode           string                           `json:"source_region_code"`
	TargetRegionId             string                           `json:"target_region_id"`
	TargetRegionCode           string                           `json:"target_region_code"`
	SafetyDecisionId           string                           `json:"safety_decision_id"`
	ExecutionFingerprint       string                           `json:"execution_fingerprint"`
	Status                     *string                          `json:"status,omitempty"`
	ExpectedTopologyRevision   int64                            `json:"expected_topology_revision"`
	ExpectedAuthorityRegionId  string                           `json:"expected_authority_region_id"`
	ExpectedAuthorityEpoch     int64                            `json:"expected_authority_epoch"`
	ExpectedFencingToken       string                           `json:"expected_fencing_token"`
	ResultingAuthorityRegionId NullableString                   `json:"resulting_authority_region_id,omitempty"`
	ResultingAuthorityEpoch    NullableInt64                    `json:"resulting_authority_epoch,omitempty"`
	ResultingFencingToken      NullableString                   `json:"resulting_fencing_token,omitempty"`
	RequestedBy                string                           `json:"requested_by"`
	RequestReason              string                           `json:"request_reason"`
	RequestedAt                time.Time                        `json:"requested_at"`
	StartedAt                  NullableTime                     `json:"started_at,omitempty"`
	CompletedAt                NullableTime                     `json:"completed_at,omitempty"`
	FailureStage               *string                          `json:"failure_stage,omitempty"`
	FailureReason              *string                          `json:"failure_reason,omitempty"`
	Metadata                   interface{}                      `json:"metadata,omitempty"`
	Revision                   *int64                           `json:"revision,omitempty"`
	Stages                     []RegionalFailoverStage          `json:"stages"`
	Events                     []RegionalFailoverExecutionEvent `json:"events"`
}

type _RegionalFailoverExecution RegionalFailoverExecution

// NewRegionalFailoverExecution instantiates a new RegionalFailoverExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionalFailoverExecution(id string, organizationId string, topologyId string, topologyName string, sourceRegionId string, sourceRegionCode string, targetRegionId string, targetRegionCode string, safetyDecisionId string, executionFingerprint string, expectedTopologyRevision int64, expectedAuthorityRegionId string, expectedAuthorityEpoch int64, expectedFencingToken string, requestedBy string, requestReason string, requestedAt time.Time, stages []RegionalFailoverStage, events []RegionalFailoverExecutionEvent) *RegionalFailoverExecution {
	this := RegionalFailoverExecution{}
	this.Id = id
	this.OrganizationId = organizationId
	this.TopologyId = topologyId
	this.TopologyName = topologyName
	this.SourceRegionId = sourceRegionId
	this.SourceRegionCode = sourceRegionCode
	this.TargetRegionId = targetRegionId
	this.TargetRegionCode = targetRegionCode
	this.SafetyDecisionId = safetyDecisionId
	this.ExecutionFingerprint = executionFingerprint
	this.ExpectedTopologyRevision = expectedTopologyRevision
	this.ExpectedAuthorityRegionId = expectedAuthorityRegionId
	this.ExpectedAuthorityEpoch = expectedAuthorityEpoch
	this.ExpectedFencingToken = expectedFencingToken
	this.RequestedBy = requestedBy
	this.RequestReason = requestReason
	this.RequestedAt = requestedAt
	this.Stages = stages
	this.Events = events
	return &this
}

// NewRegionalFailoverExecutionWithDefaults instantiates a new RegionalFailoverExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionalFailoverExecutionWithDefaults() *RegionalFailoverExecution {
	this := RegionalFailoverExecution{}
	return &this
}

// GetId returns the Id field value
func (o *RegionalFailoverExecution) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegionalFailoverExecution) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *RegionalFailoverExecution) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RegionalFailoverExecution) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetTopologyId returns the TopologyId field value
func (o *RegionalFailoverExecution) GetTopologyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TopologyId
}

// GetTopologyIdOk returns a tuple with the TopologyId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetTopologyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopologyId, true
}

// SetTopologyId sets field value
func (o *RegionalFailoverExecution) SetTopologyId(v string) {
	o.TopologyId = v
}

// GetTopologyName returns the TopologyName field value
func (o *RegionalFailoverExecution) GetTopologyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TopologyName
}

// GetTopologyNameOk returns a tuple with the TopologyName field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetTopologyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopologyName, true
}

// SetTopologyName sets field value
func (o *RegionalFailoverExecution) SetTopologyName(v string) {
	o.TopologyName = v
}

// GetSourceRegionId returns the SourceRegionId field value
func (o *RegionalFailoverExecution) GetSourceRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRegionId
}

// GetSourceRegionIdOk returns a tuple with the SourceRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetSourceRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRegionId, true
}

// SetSourceRegionId sets field value
func (o *RegionalFailoverExecution) SetSourceRegionId(v string) {
	o.SourceRegionId = v
}

// GetSourceRegionCode returns the SourceRegionCode field value
func (o *RegionalFailoverExecution) GetSourceRegionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRegionCode
}

// GetSourceRegionCodeOk returns a tuple with the SourceRegionCode field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetSourceRegionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRegionCode, true
}

// SetSourceRegionCode sets field value
func (o *RegionalFailoverExecution) SetSourceRegionCode(v string) {
	o.SourceRegionCode = v
}

// GetTargetRegionId returns the TargetRegionId field value
func (o *RegionalFailoverExecution) GetTargetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetRegionId
}

// GetTargetRegionIdOk returns a tuple with the TargetRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetTargetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetRegionId, true
}

// SetTargetRegionId sets field value
func (o *RegionalFailoverExecution) SetTargetRegionId(v string) {
	o.TargetRegionId = v
}

// GetTargetRegionCode returns the TargetRegionCode field value
func (o *RegionalFailoverExecution) GetTargetRegionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetRegionCode
}

// GetTargetRegionCodeOk returns a tuple with the TargetRegionCode field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetTargetRegionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetRegionCode, true
}

// SetTargetRegionCode sets field value
func (o *RegionalFailoverExecution) SetTargetRegionCode(v string) {
	o.TargetRegionCode = v
}

// GetSafetyDecisionId returns the SafetyDecisionId field value
func (o *RegionalFailoverExecution) GetSafetyDecisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SafetyDecisionId
}

// GetSafetyDecisionIdOk returns a tuple with the SafetyDecisionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetSafetyDecisionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SafetyDecisionId, true
}

// SetSafetyDecisionId sets field value
func (o *RegionalFailoverExecution) SetSafetyDecisionId(v string) {
	o.SafetyDecisionId = v
}

// GetExecutionFingerprint returns the ExecutionFingerprint field value
func (o *RegionalFailoverExecution) GetExecutionFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionFingerprint
}

// GetExecutionFingerprintOk returns a tuple with the ExecutionFingerprint field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetExecutionFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionFingerprint, true
}

// SetExecutionFingerprint sets field value
func (o *RegionalFailoverExecution) SetExecutionFingerprint(v string) {
	o.ExecutionFingerprint = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegionalFailoverExecution) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *RegionalFailoverExecution) SetStatus(v string) {
	o.Status = &v
}

// GetExpectedTopologyRevision returns the ExpectedTopologyRevision field value
func (o *RegionalFailoverExecution) GetExpectedTopologyRevision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpectedTopologyRevision
}

// GetExpectedTopologyRevisionOk returns a tuple with the ExpectedTopologyRevision field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetExpectedTopologyRevisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedTopologyRevision, true
}

// SetExpectedTopologyRevision sets field value
func (o *RegionalFailoverExecution) SetExpectedTopologyRevision(v int64) {
	o.ExpectedTopologyRevision = v
}

// GetExpectedAuthorityRegionId returns the ExpectedAuthorityRegionId field value
func (o *RegionalFailoverExecution) GetExpectedAuthorityRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedAuthorityRegionId
}

// GetExpectedAuthorityRegionIdOk returns a tuple with the ExpectedAuthorityRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetExpectedAuthorityRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAuthorityRegionId, true
}

// SetExpectedAuthorityRegionId sets field value
func (o *RegionalFailoverExecution) SetExpectedAuthorityRegionId(v string) {
	o.ExpectedAuthorityRegionId = v
}

// GetExpectedAuthorityEpoch returns the ExpectedAuthorityEpoch field value
func (o *RegionalFailoverExecution) GetExpectedAuthorityEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpectedAuthorityEpoch
}

// GetExpectedAuthorityEpochOk returns a tuple with the ExpectedAuthorityEpoch field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetExpectedAuthorityEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAuthorityEpoch, true
}

// SetExpectedAuthorityEpoch sets field value
func (o *RegionalFailoverExecution) SetExpectedAuthorityEpoch(v int64) {
	o.ExpectedAuthorityEpoch = v
}

// GetExpectedFencingToken returns the ExpectedFencingToken field value
func (o *RegionalFailoverExecution) GetExpectedFencingToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedFencingToken
}

// GetExpectedFencingTokenOk returns a tuple with the ExpectedFencingToken field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetExpectedFencingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedFencingToken, true
}

// SetExpectedFencingToken sets field value
func (o *RegionalFailoverExecution) SetExpectedFencingToken(v string) {
	o.ExpectedFencingToken = v
}

// GetResultingAuthorityRegionId returns the ResultingAuthorityRegionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetResultingAuthorityRegionId() string {
	if o == nil || IsNil(o.ResultingAuthorityRegionId.Get()) {
		var ret string
		return ret
	}
	return *o.ResultingAuthorityRegionId.Get()
}

// GetResultingAuthorityRegionIdOk returns a tuple with the ResultingAuthorityRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetResultingAuthorityRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultingAuthorityRegionId.Get(), o.ResultingAuthorityRegionId.IsSet()
}

// HasResultingAuthorityRegionId returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasResultingAuthorityRegionId() bool {
	if o != nil && o.ResultingAuthorityRegionId.IsSet() {
		return true
	}

	return false
}

// SetResultingAuthorityRegionId gets a reference to the given NullableString and assigns it to the ResultingAuthorityRegionId field.
func (o *RegionalFailoverExecution) SetResultingAuthorityRegionId(v string) {
	o.ResultingAuthorityRegionId.Set(&v)
}

// SetResultingAuthorityRegionIdNil sets the value for ResultingAuthorityRegionId to be an explicit nil
func (o *RegionalFailoverExecution) SetResultingAuthorityRegionIdNil() {
	o.ResultingAuthorityRegionId.Set(nil)
}

// UnsetResultingAuthorityRegionId ensures that no value is present for ResultingAuthorityRegionId, not even an explicit nil
func (o *RegionalFailoverExecution) UnsetResultingAuthorityRegionId() {
	o.ResultingAuthorityRegionId.Unset()
}

// GetResultingAuthorityEpoch returns the ResultingAuthorityEpoch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetResultingAuthorityEpoch() int64 {
	if o == nil || IsNil(o.ResultingAuthorityEpoch.Get()) {
		var ret int64
		return ret
	}
	return *o.ResultingAuthorityEpoch.Get()
}

// GetResultingAuthorityEpochOk returns a tuple with the ResultingAuthorityEpoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetResultingAuthorityEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultingAuthorityEpoch.Get(), o.ResultingAuthorityEpoch.IsSet()
}

// HasResultingAuthorityEpoch returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasResultingAuthorityEpoch() bool {
	if o != nil && o.ResultingAuthorityEpoch.IsSet() {
		return true
	}

	return false
}

// SetResultingAuthorityEpoch gets a reference to the given NullableInt64 and assigns it to the ResultingAuthorityEpoch field.
func (o *RegionalFailoverExecution) SetResultingAuthorityEpoch(v int64) {
	o.ResultingAuthorityEpoch.Set(&v)
}

// SetResultingAuthorityEpochNil sets the value for ResultingAuthorityEpoch to be an explicit nil
func (o *RegionalFailoverExecution) SetResultingAuthorityEpochNil() {
	o.ResultingAuthorityEpoch.Set(nil)
}

// UnsetResultingAuthorityEpoch ensures that no value is present for ResultingAuthorityEpoch, not even an explicit nil
func (o *RegionalFailoverExecution) UnsetResultingAuthorityEpoch() {
	o.ResultingAuthorityEpoch.Unset()
}

// GetResultingFencingToken returns the ResultingFencingToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetResultingFencingToken() string {
	if o == nil || IsNil(o.ResultingFencingToken.Get()) {
		var ret string
		return ret
	}
	return *o.ResultingFencingToken.Get()
}

// GetResultingFencingTokenOk returns a tuple with the ResultingFencingToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetResultingFencingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultingFencingToken.Get(), o.ResultingFencingToken.IsSet()
}

// HasResultingFencingToken returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasResultingFencingToken() bool {
	if o != nil && o.ResultingFencingToken.IsSet() {
		return true
	}

	return false
}

// SetResultingFencingToken gets a reference to the given NullableString and assigns it to the ResultingFencingToken field.
func (o *RegionalFailoverExecution) SetResultingFencingToken(v string) {
	o.ResultingFencingToken.Set(&v)
}

// SetResultingFencingTokenNil sets the value for ResultingFencingToken to be an explicit nil
func (o *RegionalFailoverExecution) SetResultingFencingTokenNil() {
	o.ResultingFencingToken.Set(nil)
}

// UnsetResultingFencingToken ensures that no value is present for ResultingFencingToken, not even an explicit nil
func (o *RegionalFailoverExecution) UnsetResultingFencingToken() {
	o.ResultingFencingToken.Unset()
}

// GetRequestedBy returns the RequestedBy field value
func (o *RegionalFailoverExecution) GetRequestedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedBy
}

// GetRequestedByOk returns a tuple with the RequestedBy field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetRequestedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedBy, true
}

// SetRequestedBy sets field value
func (o *RegionalFailoverExecution) SetRequestedBy(v string) {
	o.RequestedBy = v
}

// GetRequestReason returns the RequestReason field value
func (o *RegionalFailoverExecution) GetRequestReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestReason
}

// GetRequestReasonOk returns a tuple with the RequestReason field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetRequestReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestReason, true
}

// SetRequestReason sets field value
func (o *RegionalFailoverExecution) SetRequestReason(v string) {
	o.RequestReason = v
}

// GetRequestedAt returns the RequestedAt field value
func (o *RegionalFailoverExecution) GetRequestedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RequestedAt
}

// GetRequestedAtOk returns a tuple with the RequestedAt field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetRequestedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedAt, true
}

// SetRequestedAt sets field value
func (o *RegionalFailoverExecution) SetRequestedAt(v time.Time) {
	o.RequestedAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *RegionalFailoverExecution) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}

// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *RegionalFailoverExecution) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *RegionalFailoverExecution) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *RegionalFailoverExecution) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}

// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *RegionalFailoverExecution) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *RegionalFailoverExecution) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetFailureStage returns the FailureStage field value if set, zero value otherwise.
func (o *RegionalFailoverExecution) GetFailureStage() string {
	if o == nil || IsNil(o.FailureStage) {
		var ret string
		return ret
	}
	return *o.FailureStage
}

// GetFailureStageOk returns a tuple with the FailureStage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetFailureStageOk() (*string, bool) {
	if o == nil || IsNil(o.FailureStage) {
		return nil, false
	}
	return o.FailureStage, true
}

// HasFailureStage returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasFailureStage() bool {
	if o != nil && !IsNil(o.FailureStage) {
		return true
	}

	return false
}

// SetFailureStage gets a reference to the given string and assigns it to the FailureStage field.
func (o *RegionalFailoverExecution) SetFailureStage(v string) {
	o.FailureStage = &v
}

// GetFailureReason returns the FailureReason field value if set, zero value otherwise.
func (o *RegionalFailoverExecution) GetFailureReason() string {
	if o == nil || IsNil(o.FailureReason) {
		var ret string
		return ret
	}
	return *o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailureReason) {
		return nil, false
	}
	return o.FailureReason, true
}

// HasFailureReason returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasFailureReason() bool {
	if o != nil && !IsNil(o.FailureReason) {
		return true
	}

	return false
}

// SetFailureReason gets a reference to the given string and assigns it to the FailureReason field.
func (o *RegionalFailoverExecution) SetFailureReason(v string) {
	o.FailureReason = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecution) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecution) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *RegionalFailoverExecution) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *RegionalFailoverExecution) GetRevision() int64 {
	if o == nil || IsNil(o.Revision) {
		var ret int64
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetRevisionOk() (*int64, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *RegionalFailoverExecution) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given int64 and assigns it to the Revision field.
func (o *RegionalFailoverExecution) SetRevision(v int64) {
	o.Revision = &v
}

// GetStages returns the Stages field value
func (o *RegionalFailoverExecution) GetStages() []RegionalFailoverStage {
	if o == nil {
		var ret []RegionalFailoverStage
		return ret
	}

	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetStagesOk() ([]RegionalFailoverStage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stages, true
}

// SetStages sets field value
func (o *RegionalFailoverExecution) SetStages(v []RegionalFailoverStage) {
	o.Stages = v
}

// GetEvents returns the Events field value
func (o *RegionalFailoverExecution) GetEvents() []RegionalFailoverExecutionEvent {
	if o == nil {
		var ret []RegionalFailoverExecutionEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecution) GetEventsOk() ([]RegionalFailoverExecutionEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *RegionalFailoverExecution) SetEvents(v []RegionalFailoverExecutionEvent) {
	o.Events = v
}

func (o RegionalFailoverExecution) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionalFailoverExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["execution_fingerprint"] = o.ExecutionFingerprint
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["expected_topology_revision"] = o.ExpectedTopologyRevision
	toSerialize["expected_authority_region_id"] = o.ExpectedAuthorityRegionId
	toSerialize["expected_authority_epoch"] = o.ExpectedAuthorityEpoch
	toSerialize["expected_fencing_token"] = o.ExpectedFencingToken
	if o.ResultingAuthorityRegionId.IsSet() {
		toSerialize["resulting_authority_region_id"] = o.ResultingAuthorityRegionId.Get()
	}
	if o.ResultingAuthorityEpoch.IsSet() {
		toSerialize["resulting_authority_epoch"] = o.ResultingAuthorityEpoch.Get()
	}
	if o.ResultingFencingToken.IsSet() {
		toSerialize["resulting_fencing_token"] = o.ResultingFencingToken.Get()
	}
	toSerialize["requested_by"] = o.RequestedBy
	toSerialize["request_reason"] = o.RequestReason
	toSerialize["requested_at"] = o.RequestedAt
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if !IsNil(o.FailureStage) {
		toSerialize["failure_stage"] = o.FailureStage
	}
	if !IsNil(o.FailureReason) {
		toSerialize["failure_reason"] = o.FailureReason
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	return toSerialize, nil
}

func (o *RegionalFailoverExecution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organization_id",
		"topology_id",
		"topology_name",
		"source_region_id",
		"source_region_code",
		"target_region_id",
		"target_region_code",
		"safety_decision_id",
		"execution_fingerprint",
		"expected_topology_revision",
		"expected_authority_region_id",
		"expected_authority_epoch",
		"expected_fencing_token",
		"requested_by",
		"request_reason",
		"requested_at",
		"stages",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionalFailoverExecution := _RegionalFailoverExecution{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionalFailoverExecution)

	if err != nil {
		return err
	}

	*o = RegionalFailoverExecution(varRegionalFailoverExecution)

	return err
}

type NullableRegionalFailoverExecution struct {
	value *RegionalFailoverExecution
	isSet bool
}

func (v NullableRegionalFailoverExecution) Get() *RegionalFailoverExecution {
	return v.value
}

func (v *NullableRegionalFailoverExecution) Set(val *RegionalFailoverExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionalFailoverExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionalFailoverExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionalFailoverExecution(val *RegionalFailoverExecution) *NullableRegionalFailoverExecution {
	return &NullableRegionalFailoverExecution{value: val, isSet: true}
}

func (v NullableRegionalFailoverExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionalFailoverExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
