/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// CircuitStateEnum * `closed` - closed * `open` - open * `half_open` - half_open * `unknown` - unknown
type CircuitStateEnum string

// List of CircuitStateEnum
const (
	CIRCUITSTATEENUM_CLOSED    CircuitStateEnum = "closed"
	CIRCUITSTATEENUM_OPEN      CircuitStateEnum = "open"
	CIRCUITSTATEENUM_HALF_OPEN CircuitStateEnum = "half_open"
	CIRCUITSTATEENUM_UNKNOWN   CircuitStateEnum = "unknown"
)

// All allowed values of CircuitStateEnum enum
var AllowedCircuitStateEnumEnumValues = []CircuitStateEnum{
	"closed",
	"open",
	"half_open",
	"unknown",
}

func (v *CircuitStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CircuitStateEnum(value)
	for _, existing := range AllowedCircuitStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CircuitStateEnum", value)
}

// NewCircuitStateEnumFromValue returns a pointer to a valid CircuitStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCircuitStateEnumFromValue(v string) (*CircuitStateEnum, error) {
	ev := CircuitStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CircuitStateEnum: valid values are %v", v, AllowedCircuitStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CircuitStateEnum) IsValid() bool {
	for _, existing := range AllowedCircuitStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CircuitStateEnum value
func (v CircuitStateEnum) Ptr() *CircuitStateEnum {
	return &v
}

type NullableCircuitStateEnum struct {
	value *CircuitStateEnum
	isSet bool
}

func (v NullableCircuitStateEnum) Get() *CircuitStateEnum {
	return v.value
}

func (v *NullableCircuitStateEnum) Set(val *CircuitStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCircuitStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCircuitStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCircuitStateEnum(val *CircuitStateEnum) *NullableCircuitStateEnum {
	return &NullableCircuitStateEnum{value: val, isSet: true}
}

func (v NullableCircuitStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCircuitStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
