/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleExecutionControlActionEnum * `pause` - pause * `resume` - resume * `cancel` - cancel * `reconcile` - reconcile * `retry` - retry
type LifecycleExecutionControlActionEnum string

// List of LifecycleExecutionControlActionEnum
const (
	LIFECYCLEEXECUTIONCONTROLACTIONENUM_PAUSE     LifecycleExecutionControlActionEnum = "pause"
	LIFECYCLEEXECUTIONCONTROLACTIONENUM_RESUME    LifecycleExecutionControlActionEnum = "resume"
	LIFECYCLEEXECUTIONCONTROLACTIONENUM_CANCEL    LifecycleExecutionControlActionEnum = "cancel"
	LIFECYCLEEXECUTIONCONTROLACTIONENUM_RECONCILE LifecycleExecutionControlActionEnum = "reconcile"
	LIFECYCLEEXECUTIONCONTROLACTIONENUM_RETRY     LifecycleExecutionControlActionEnum = "retry"
)

// All allowed values of LifecycleExecutionControlActionEnum enum
var AllowedLifecycleExecutionControlActionEnumEnumValues = []LifecycleExecutionControlActionEnum{
	"pause",
	"resume",
	"cancel",
	"reconcile",
	"retry",
}

func (v *LifecycleExecutionControlActionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleExecutionControlActionEnum(value)
	for _, existing := range AllowedLifecycleExecutionControlActionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleExecutionControlActionEnum", value)
}

// NewLifecycleExecutionControlActionEnumFromValue returns a pointer to a valid LifecycleExecutionControlActionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleExecutionControlActionEnumFromValue(v string) (*LifecycleExecutionControlActionEnum, error) {
	ev := LifecycleExecutionControlActionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleExecutionControlActionEnum: valid values are %v", v, AllowedLifecycleExecutionControlActionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleExecutionControlActionEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleExecutionControlActionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleExecutionControlActionEnum value
func (v LifecycleExecutionControlActionEnum) Ptr() *LifecycleExecutionControlActionEnum {
	return &v
}

type NullableLifecycleExecutionControlActionEnum struct {
	value *LifecycleExecutionControlActionEnum
	isSet bool
}

func (v NullableLifecycleExecutionControlActionEnum) Get() *LifecycleExecutionControlActionEnum {
	return v.value
}

func (v *NullableLifecycleExecutionControlActionEnum) Set(val *LifecycleExecutionControlActionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleExecutionControlActionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleExecutionControlActionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleExecutionControlActionEnum(val *LifecycleExecutionControlActionEnum) *NullableLifecycleExecutionControlActionEnum {
	return &NullableLifecycleExecutionControlActionEnum{value: val, isSet: true}
}

func (v NullableLifecycleExecutionControlActionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleExecutionControlActionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
