/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// AlertTypeEnum * `compliance` - Compliance * `slo_breach` - SLO breach * `dead_letter` - Dead letter * `legal_hold` - Legal hold * `archive_backlog` - Archive backlog * `purge_backlog` - Purge backlog * `evidence_gap` - Evidence gap
type AlertTypeEnum string

// List of AlertTypeEnum
const (
	ALERTTYPEENUM_COMPLIANCE      AlertTypeEnum = "compliance"
	ALERTTYPEENUM_SLO_BREACH      AlertTypeEnum = "slo_breach"
	ALERTTYPEENUM_DEAD_LETTER     AlertTypeEnum = "dead_letter"
	ALERTTYPEENUM_LEGAL_HOLD      AlertTypeEnum = "legal_hold"
	ALERTTYPEENUM_ARCHIVE_BACKLOG AlertTypeEnum = "archive_backlog"
	ALERTTYPEENUM_PURGE_BACKLOG   AlertTypeEnum = "purge_backlog"
	ALERTTYPEENUM_EVIDENCE_GAP    AlertTypeEnum = "evidence_gap"
)

// All allowed values of AlertTypeEnum enum
var AllowedAlertTypeEnumEnumValues = []AlertTypeEnum{
	"compliance",
	"slo_breach",
	"dead_letter",
	"legal_hold",
	"archive_backlog",
	"purge_backlog",
	"evidence_gap",
}

func (v *AlertTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AlertTypeEnum(value)
	for _, existing := range AllowedAlertTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AlertTypeEnum", value)
}

// NewAlertTypeEnumFromValue returns a pointer to a valid AlertTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAlertTypeEnumFromValue(v string) (*AlertTypeEnum, error) {
	ev := AlertTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AlertTypeEnum: valid values are %v", v, AllowedAlertTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AlertTypeEnum) IsValid() bool {
	for _, existing := range AllowedAlertTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AlertTypeEnum value
func (v AlertTypeEnum) Ptr() *AlertTypeEnum {
	return &v
}

type NullableAlertTypeEnum struct {
	value *AlertTypeEnum
	isSet bool
}

func (v NullableAlertTypeEnum) Get() *AlertTypeEnum {
	return v.value
}

func (v *NullableAlertTypeEnum) Set(val *AlertTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertTypeEnum(val *AlertTypeEnum) *NullableAlertTypeEnum {
	return &NullableAlertTypeEnum{value: val, isSet: true}
}

func (v NullableAlertTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
