/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleSLOIndicatorStateEnum * `healthy` - healthy * `warning` - warning * `breached` - breached * `unknown` - unknown
type LifecycleSLOIndicatorStateEnum string

// List of LifecycleSLOIndicatorStateEnum
const (
	LIFECYCLESLOINDICATORSTATEENUM_HEALTHY  LifecycleSLOIndicatorStateEnum = "healthy"
	LIFECYCLESLOINDICATORSTATEENUM_WARNING  LifecycleSLOIndicatorStateEnum = "warning"
	LIFECYCLESLOINDICATORSTATEENUM_BREACHED LifecycleSLOIndicatorStateEnum = "breached"
	LIFECYCLESLOINDICATORSTATEENUM_UNKNOWN  LifecycleSLOIndicatorStateEnum = "unknown"
)

// All allowed values of LifecycleSLOIndicatorStateEnum enum
var AllowedLifecycleSLOIndicatorStateEnumEnumValues = []LifecycleSLOIndicatorStateEnum{
	"healthy",
	"warning",
	"breached",
	"unknown",
}

func (v *LifecycleSLOIndicatorStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleSLOIndicatorStateEnum(value)
	for _, existing := range AllowedLifecycleSLOIndicatorStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleSLOIndicatorStateEnum", value)
}

// NewLifecycleSLOIndicatorStateEnumFromValue returns a pointer to a valid LifecycleSLOIndicatorStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleSLOIndicatorStateEnumFromValue(v string) (*LifecycleSLOIndicatorStateEnum, error) {
	ev := LifecycleSLOIndicatorStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleSLOIndicatorStateEnum: valid values are %v", v, AllowedLifecycleSLOIndicatorStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleSLOIndicatorStateEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleSLOIndicatorStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleSLOIndicatorStateEnum value
func (v LifecycleSLOIndicatorStateEnum) Ptr() *LifecycleSLOIndicatorStateEnum {
	return &v
}

type NullableLifecycleSLOIndicatorStateEnum struct {
	value *LifecycleSLOIndicatorStateEnum
	isSet bool
}

func (v NullableLifecycleSLOIndicatorStateEnum) Get() *LifecycleSLOIndicatorStateEnum {
	return v.value
}

func (v *NullableLifecycleSLOIndicatorStateEnum) Set(val *LifecycleSLOIndicatorStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleSLOIndicatorStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleSLOIndicatorStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleSLOIndicatorStateEnum(val *LifecycleSLOIndicatorStateEnum) *NullableLifecycleSLOIndicatorStateEnum {
	return &NullableLifecycleSLOIndicatorStateEnum{value: val, isSet: true}
}

func (v NullableLifecycleSLOIndicatorStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleSLOIndicatorStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
