/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OperatorRuntimeIncidentList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeIncidentList{}

// OperatorRuntimeIncidentList struct for OperatorRuntimeIncidentList
type OperatorRuntimeIncidentList struct {
	Id               string                      `json:"id"`
	DeduplicationKey string                      `json:"deduplication_key"`
	RuleCode         string                      `json:"rule_code"`
	Scope            RuntimeIncidentScopeEnum    `json:"scope"`
	OrganizationId   NullableString              `json:"organization_id,omitempty"`
	ConsumerId       NullableString              `json:"consumer_id,omitempty"`
	ConsumerCode     *string                     `json:"consumer_code,omitempty"`
	Severity         RuntimeIncidentSeverityEnum `json:"severity"`
	Status           *RuntimeIncidentStatusEnum  `json:"status,omitempty"`
	Active           bool                        `json:"active"`
	Signal           string                      `json:"signal"`
	Threshold        float64                     `json:"threshold"`
	OccurrenceCount  *int64                      `json:"occurrence_count,omitempty"`
	ReopenCount      *int64                      `json:"reopen_count,omitempty"`
	FirstDetectedAt  time.Time                   `json:"first_detected_at"`
	LastDetectedAt   time.Time                   `json:"last_detected_at"`
	LastObservedAt   time.Time                   `json:"last_observed_at"`
	AcknowledgedAt   NullableTime                `json:"acknowledged_at,omitempty"`
	AcknowledgedBy   *string                     `json:"acknowledged_by,omitempty"`
	ResolvedAt       NullableTime                `json:"resolved_at,omitempty"`
	ResolvedBy       *string                     `json:"resolved_by,omitempty"`
	Version          *int64                      `json:"version,omitempty"`
	CreatedAt        time.Time                   `json:"created_at"`
	UpdatedAt        time.Time                   `json:"updated_at"`
}

type _OperatorRuntimeIncidentList OperatorRuntimeIncidentList

// NewOperatorRuntimeIncidentList instantiates a new OperatorRuntimeIncidentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeIncidentList(id string, deduplicationKey string, ruleCode string, scope RuntimeIncidentScopeEnum, severity RuntimeIncidentSeverityEnum, active bool, signal string, threshold float64, firstDetectedAt time.Time, lastDetectedAt time.Time, lastObservedAt time.Time, createdAt time.Time, updatedAt time.Time) *OperatorRuntimeIncidentList {
	this := OperatorRuntimeIncidentList{}
	this.Id = id
	this.DeduplicationKey = deduplicationKey
	this.RuleCode = ruleCode
	this.Scope = scope
	this.Severity = severity
	this.Active = active
	this.Signal = signal
	this.Threshold = threshold
	this.FirstDetectedAt = firstDetectedAt
	this.LastDetectedAt = lastDetectedAt
	this.LastObservedAt = lastObservedAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewOperatorRuntimeIncidentListWithDefaults instantiates a new OperatorRuntimeIncidentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeIncidentListWithDefaults() *OperatorRuntimeIncidentList {
	this := OperatorRuntimeIncidentList{}
	return &this
}

// GetId returns the Id field value
func (o *OperatorRuntimeIncidentList) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OperatorRuntimeIncidentList) SetId(v string) {
	o.Id = v
}

// GetDeduplicationKey returns the DeduplicationKey field value
func (o *OperatorRuntimeIncidentList) GetDeduplicationKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeduplicationKey
}

// GetDeduplicationKeyOk returns a tuple with the DeduplicationKey field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetDeduplicationKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeduplicationKey, true
}

// SetDeduplicationKey sets field value
func (o *OperatorRuntimeIncidentList) SetDeduplicationKey(v string) {
	o.DeduplicationKey = v
}

// GetRuleCode returns the RuleCode field value
func (o *OperatorRuntimeIncidentList) GetRuleCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleCode
}

// GetRuleCodeOk returns a tuple with the RuleCode field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetRuleCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleCode, true
}

// SetRuleCode sets field value
func (o *OperatorRuntimeIncidentList) SetRuleCode(v string) {
	o.RuleCode = v
}

// GetScope returns the Scope field value
func (o *OperatorRuntimeIncidentList) GetScope() RuntimeIncidentScopeEnum {
	if o == nil {
		var ret RuntimeIncidentScopeEnum
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetScopeOk() (*RuntimeIncidentScopeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *OperatorRuntimeIncidentList) SetScope(v RuntimeIncidentScopeEnum) {
	o.Scope = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatorRuntimeIncidentList) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatorRuntimeIncidentList) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasOrganizationId() bool {
	if o != nil && o.OrganizationId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given NullableString and assigns it to the OrganizationId field.
func (o *OperatorRuntimeIncidentList) SetOrganizationId(v string) {
	o.OrganizationId.Set(&v)
}

// SetOrganizationIdNil sets the value for OrganizationId to be an explicit nil
func (o *OperatorRuntimeIncidentList) SetOrganizationIdNil() {
	o.OrganizationId.Set(nil)
}

// UnsetOrganizationId ensures that no value is present for OrganizationId, not even an explicit nil
func (o *OperatorRuntimeIncidentList) UnsetOrganizationId() {
	o.OrganizationId.Unset()
}

// GetConsumerId returns the ConsumerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatorRuntimeIncidentList) GetConsumerId() string {
	if o == nil || IsNil(o.ConsumerId.Get()) {
		var ret string
		return ret
	}
	return *o.ConsumerId.Get()
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatorRuntimeIncidentList) GetConsumerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsumerId.Get(), o.ConsumerId.IsSet()
}

// HasConsumerId returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasConsumerId() bool {
	if o != nil && o.ConsumerId.IsSet() {
		return true
	}

	return false
}

// SetConsumerId gets a reference to the given NullableString and assigns it to the ConsumerId field.
func (o *OperatorRuntimeIncidentList) SetConsumerId(v string) {
	o.ConsumerId.Set(&v)
}

// SetConsumerIdNil sets the value for ConsumerId to be an explicit nil
func (o *OperatorRuntimeIncidentList) SetConsumerIdNil() {
	o.ConsumerId.Set(nil)
}

// UnsetConsumerId ensures that no value is present for ConsumerId, not even an explicit nil
func (o *OperatorRuntimeIncidentList) UnsetConsumerId() {
	o.ConsumerId.Unset()
}

// GetConsumerCode returns the ConsumerCode field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetConsumerCode() string {
	if o == nil || IsNil(o.ConsumerCode) {
		var ret string
		return ret
	}
	return *o.ConsumerCode
}

// GetConsumerCodeOk returns a tuple with the ConsumerCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetConsumerCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerCode) {
		return nil, false
	}
	return o.ConsumerCode, true
}

// HasConsumerCode returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasConsumerCode() bool {
	if o != nil && !IsNil(o.ConsumerCode) {
		return true
	}

	return false
}

// SetConsumerCode gets a reference to the given string and assigns it to the ConsumerCode field.
func (o *OperatorRuntimeIncidentList) SetConsumerCode(v string) {
	o.ConsumerCode = &v
}

// GetSeverity returns the Severity field value
func (o *OperatorRuntimeIncidentList) GetSeverity() RuntimeIncidentSeverityEnum {
	if o == nil {
		var ret RuntimeIncidentSeverityEnum
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetSeverityOk() (*RuntimeIncidentSeverityEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *OperatorRuntimeIncidentList) SetSeverity(v RuntimeIncidentSeverityEnum) {
	o.Severity = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetStatus() RuntimeIncidentStatusEnum {
	if o == nil || IsNil(o.Status) {
		var ret RuntimeIncidentStatusEnum
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetStatusOk() (*RuntimeIncidentStatusEnum, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given RuntimeIncidentStatusEnum and assigns it to the Status field.
func (o *OperatorRuntimeIncidentList) SetStatus(v RuntimeIncidentStatusEnum) {
	o.Status = &v
}

// GetActive returns the Active field value
func (o *OperatorRuntimeIncidentList) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *OperatorRuntimeIncidentList) SetActive(v bool) {
	o.Active = v
}

// GetSignal returns the Signal field value
func (o *OperatorRuntimeIncidentList) GetSignal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signal
}

// GetSignalOk returns a tuple with the Signal field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetSignalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signal, true
}

// SetSignal sets field value
func (o *OperatorRuntimeIncidentList) SetSignal(v string) {
	o.Signal = v
}

// GetThreshold returns the Threshold field value
func (o *OperatorRuntimeIncidentList) GetThreshold() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *OperatorRuntimeIncidentList) SetThreshold(v float64) {
	o.Threshold = v
}

// GetOccurrenceCount returns the OccurrenceCount field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetOccurrenceCount() int64 {
	if o == nil || IsNil(o.OccurrenceCount) {
		var ret int64
		return ret
	}
	return *o.OccurrenceCount
}

// GetOccurrenceCountOk returns a tuple with the OccurrenceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetOccurrenceCountOk() (*int64, bool) {
	if o == nil || IsNil(o.OccurrenceCount) {
		return nil, false
	}
	return o.OccurrenceCount, true
}

// HasOccurrenceCount returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasOccurrenceCount() bool {
	if o != nil && !IsNil(o.OccurrenceCount) {
		return true
	}

	return false
}

// SetOccurrenceCount gets a reference to the given int64 and assigns it to the OccurrenceCount field.
func (o *OperatorRuntimeIncidentList) SetOccurrenceCount(v int64) {
	o.OccurrenceCount = &v
}

// GetReopenCount returns the ReopenCount field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetReopenCount() int64 {
	if o == nil || IsNil(o.ReopenCount) {
		var ret int64
		return ret
	}
	return *o.ReopenCount
}

// GetReopenCountOk returns a tuple with the ReopenCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetReopenCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ReopenCount) {
		return nil, false
	}
	return o.ReopenCount, true
}

// HasReopenCount returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasReopenCount() bool {
	if o != nil && !IsNil(o.ReopenCount) {
		return true
	}

	return false
}

// SetReopenCount gets a reference to the given int64 and assigns it to the ReopenCount field.
func (o *OperatorRuntimeIncidentList) SetReopenCount(v int64) {
	o.ReopenCount = &v
}

// GetFirstDetectedAt returns the FirstDetectedAt field value
func (o *OperatorRuntimeIncidentList) GetFirstDetectedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.FirstDetectedAt
}

// GetFirstDetectedAtOk returns a tuple with the FirstDetectedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetFirstDetectedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstDetectedAt, true
}

// SetFirstDetectedAt sets field value
func (o *OperatorRuntimeIncidentList) SetFirstDetectedAt(v time.Time) {
	o.FirstDetectedAt = v
}

// GetLastDetectedAt returns the LastDetectedAt field value
func (o *OperatorRuntimeIncidentList) GetLastDetectedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastDetectedAt
}

// GetLastDetectedAtOk returns a tuple with the LastDetectedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetLastDetectedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDetectedAt, true
}

// SetLastDetectedAt sets field value
func (o *OperatorRuntimeIncidentList) SetLastDetectedAt(v time.Time) {
	o.LastDetectedAt = v
}

// GetLastObservedAt returns the LastObservedAt field value
func (o *OperatorRuntimeIncidentList) GetLastObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastObservedAt
}

// GetLastObservedAtOk returns a tuple with the LastObservedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetLastObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastObservedAt, true
}

// SetLastObservedAt sets field value
func (o *OperatorRuntimeIncidentList) SetLastObservedAt(v time.Time) {
	o.LastObservedAt = v
}

// GetAcknowledgedAt returns the AcknowledgedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatorRuntimeIncidentList) GetAcknowledgedAt() time.Time {
	if o == nil || IsNil(o.AcknowledgedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.AcknowledgedAt.Get()
}

// GetAcknowledgedAtOk returns a tuple with the AcknowledgedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatorRuntimeIncidentList) GetAcknowledgedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.AcknowledgedAt.Get(), o.AcknowledgedAt.IsSet()
}

// HasAcknowledgedAt returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasAcknowledgedAt() bool {
	if o != nil && o.AcknowledgedAt.IsSet() {
		return true
	}

	return false
}

// SetAcknowledgedAt gets a reference to the given NullableTime and assigns it to the AcknowledgedAt field.
func (o *OperatorRuntimeIncidentList) SetAcknowledgedAt(v time.Time) {
	o.AcknowledgedAt.Set(&v)
}

// SetAcknowledgedAtNil sets the value for AcknowledgedAt to be an explicit nil
func (o *OperatorRuntimeIncidentList) SetAcknowledgedAtNil() {
	o.AcknowledgedAt.Set(nil)
}

// UnsetAcknowledgedAt ensures that no value is present for AcknowledgedAt, not even an explicit nil
func (o *OperatorRuntimeIncidentList) UnsetAcknowledgedAt() {
	o.AcknowledgedAt.Unset()
}

// GetAcknowledgedBy returns the AcknowledgedBy field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetAcknowledgedBy() string {
	if o == nil || IsNil(o.AcknowledgedBy) {
		var ret string
		return ret
	}
	return *o.AcknowledgedBy
}

// GetAcknowledgedByOk returns a tuple with the AcknowledgedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetAcknowledgedByOk() (*string, bool) {
	if o == nil || IsNil(o.AcknowledgedBy) {
		return nil, false
	}
	return o.AcknowledgedBy, true
}

// HasAcknowledgedBy returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasAcknowledgedBy() bool {
	if o != nil && !IsNil(o.AcknowledgedBy) {
		return true
	}

	return false
}

// SetAcknowledgedBy gets a reference to the given string and assigns it to the AcknowledgedBy field.
func (o *OperatorRuntimeIncidentList) SetAcknowledgedBy(v string) {
	o.AcknowledgedBy = &v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatorRuntimeIncidentList) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt.Get()
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatorRuntimeIncidentList) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolvedAt.Get(), o.ResolvedAt.IsSet()
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasResolvedAt() bool {
	if o != nil && o.ResolvedAt.IsSet() {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given NullableTime and assigns it to the ResolvedAt field.
func (o *OperatorRuntimeIncidentList) SetResolvedAt(v time.Time) {
	o.ResolvedAt.Set(&v)
}

// SetResolvedAtNil sets the value for ResolvedAt to be an explicit nil
func (o *OperatorRuntimeIncidentList) SetResolvedAtNil() {
	o.ResolvedAt.Set(nil)
}

// UnsetResolvedAt ensures that no value is present for ResolvedAt, not even an explicit nil
func (o *OperatorRuntimeIncidentList) UnsetResolvedAt() {
	o.ResolvedAt.Unset()
}

// GetResolvedBy returns the ResolvedBy field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetResolvedBy() string {
	if o == nil || IsNil(o.ResolvedBy) {
		var ret string
		return ret
	}
	return *o.ResolvedBy
}

// GetResolvedByOk returns a tuple with the ResolvedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetResolvedByOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedBy) {
		return nil, false
	}
	return o.ResolvedBy, true
}

// HasResolvedBy returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasResolvedBy() bool {
	if o != nil && !IsNil(o.ResolvedBy) {
		return true
	}

	return false
}

// SetResolvedBy gets a reference to the given string and assigns it to the ResolvedBy field.
func (o *OperatorRuntimeIncidentList) SetResolvedBy(v string) {
	o.ResolvedBy = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentList) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentList) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *OperatorRuntimeIncidentList) SetVersion(v int64) {
	o.Version = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OperatorRuntimeIncidentList) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OperatorRuntimeIncidentList) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *OperatorRuntimeIncidentList) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentList) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *OperatorRuntimeIncidentList) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o OperatorRuntimeIncidentList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeIncidentList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deduplication_key"] = o.DeduplicationKey
	toSerialize["rule_code"] = o.RuleCode
	toSerialize["scope"] = o.Scope
	if o.OrganizationId.IsSet() {
		toSerialize["organization_id"] = o.OrganizationId.Get()
	}
	if o.ConsumerId.IsSet() {
		toSerialize["consumer_id"] = o.ConsumerId.Get()
	}
	if !IsNil(o.ConsumerCode) {
		toSerialize["consumer_code"] = o.ConsumerCode
	}
	toSerialize["severity"] = o.Severity
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["signal"] = o.Signal
	toSerialize["threshold"] = o.Threshold
	if !IsNil(o.OccurrenceCount) {
		toSerialize["occurrence_count"] = o.OccurrenceCount
	}
	if !IsNil(o.ReopenCount) {
		toSerialize["reopen_count"] = o.ReopenCount
	}
	toSerialize["first_detected_at"] = o.FirstDetectedAt
	toSerialize["last_detected_at"] = o.LastDetectedAt
	toSerialize["last_observed_at"] = o.LastObservedAt
	if o.AcknowledgedAt.IsSet() {
		toSerialize["acknowledged_at"] = o.AcknowledgedAt.Get()
	}
	if !IsNil(o.AcknowledgedBy) {
		toSerialize["acknowledged_by"] = o.AcknowledgedBy
	}
	if o.ResolvedAt.IsSet() {
		toSerialize["resolved_at"] = o.ResolvedAt.Get()
	}
	if !IsNil(o.ResolvedBy) {
		toSerialize["resolved_by"] = o.ResolvedBy
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *OperatorRuntimeIncidentList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"deduplication_key",
		"rule_code",
		"scope",
		"severity",
		"active",
		"signal",
		"threshold",
		"first_detected_at",
		"last_detected_at",
		"last_observed_at",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeIncidentList := _OperatorRuntimeIncidentList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeIncidentList)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeIncidentList(varOperatorRuntimeIncidentList)

	return err
}

type NullableOperatorRuntimeIncidentList struct {
	value *OperatorRuntimeIncidentList
	isSet bool
}

func (v NullableOperatorRuntimeIncidentList) Get() *OperatorRuntimeIncidentList {
	return v.value
}

func (v *NullableOperatorRuntimeIncidentList) Set(val *OperatorRuntimeIncidentList) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeIncidentList) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeIncidentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeIncidentList(val *OperatorRuntimeIncidentList) *NullableOperatorRuntimeIncidentList {
	return &NullableOperatorRuntimeIncidentList{value: val, isSet: true}
}

func (v NullableOperatorRuntimeIncidentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeIncidentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
