/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegionalFailoverExecutionCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionalFailoverExecutionCreateRequest{}

// RegionalFailoverExecutionCreateRequest struct for RegionalFailoverExecutionCreateRequest
type RegionalFailoverExecutionCreateRequest struct {
	SafetyDecisionId string      `json:"safety_decision_id"`
	Reason           string      `json:"reason"`
	Metadata         interface{} `json:"metadata,omitempty"`
}

type _RegionalFailoverExecutionCreateRequest RegionalFailoverExecutionCreateRequest

// NewRegionalFailoverExecutionCreateRequest instantiates a new RegionalFailoverExecutionCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionalFailoverExecutionCreateRequest(safetyDecisionId string, reason string) *RegionalFailoverExecutionCreateRequest {
	this := RegionalFailoverExecutionCreateRequest{}
	this.SafetyDecisionId = safetyDecisionId
	this.Reason = reason
	return &this
}

// NewRegionalFailoverExecutionCreateRequestWithDefaults instantiates a new RegionalFailoverExecutionCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionalFailoverExecutionCreateRequestWithDefaults() *RegionalFailoverExecutionCreateRequest {
	this := RegionalFailoverExecutionCreateRequest{}
	return &this
}

// GetSafetyDecisionId returns the SafetyDecisionId field value
func (o *RegionalFailoverExecutionCreateRequest) GetSafetyDecisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SafetyDecisionId
}

// GetSafetyDecisionIdOk returns a tuple with the SafetyDecisionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecutionCreateRequest) GetSafetyDecisionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SafetyDecisionId, true
}

// SetSafetyDecisionId sets field value
func (o *RegionalFailoverExecutionCreateRequest) SetSafetyDecisionId(v string) {
	o.SafetyDecisionId = v
}

// GetReason returns the Reason field value
func (o *RegionalFailoverExecutionCreateRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverExecutionCreateRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *RegionalFailoverExecutionCreateRequest) SetReason(v string) {
	o.Reason = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverExecutionCreateRequest) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverExecutionCreateRequest) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RegionalFailoverExecutionCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *RegionalFailoverExecutionCreateRequest) SetMetadata(v interface{}) {
	o.Metadata = v
}

func (o RegionalFailoverExecutionCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionalFailoverExecutionCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["safety_decision_id"] = o.SafetyDecisionId
	toSerialize["reason"] = o.Reason
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *RegionalFailoverExecutionCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"safety_decision_id",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionalFailoverExecutionCreateRequest := _RegionalFailoverExecutionCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionalFailoverExecutionCreateRequest)

	if err != nil {
		return err
	}

	*o = RegionalFailoverExecutionCreateRequest(varRegionalFailoverExecutionCreateRequest)

	return err
}

type NullableRegionalFailoverExecutionCreateRequest struct {
	value *RegionalFailoverExecutionCreateRequest
	isSet bool
}

func (v NullableRegionalFailoverExecutionCreateRequest) Get() *RegionalFailoverExecutionCreateRequest {
	return v.value
}

func (v *NullableRegionalFailoverExecutionCreateRequest) Set(val *RegionalFailoverExecutionCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionalFailoverExecutionCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionalFailoverExecutionCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionalFailoverExecutionCreateRequest(val *RegionalFailoverExecutionCreateRequest) *NullableRegionalFailoverExecutionCreateRequest {
	return &NullableRegionalFailoverExecutionCreateRequest{value: val, isSet: true}
}

func (v NullableRegionalFailoverExecutionCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionalFailoverExecutionCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
