/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// RecoveryEscalationNotificationStatusEnum * `pending` - Pending * `processing` - Processing * `sent` - Sent * `failed` - Failed * `cancelled` - Cancelled
type RecoveryEscalationNotificationStatusEnum string

// List of RecoveryEscalationNotificationStatusEnum
const (
	RECOVERYESCALATIONNOTIFICATIONSTATUSENUM_PENDING    RecoveryEscalationNotificationStatusEnum = "pending"
	RECOVERYESCALATIONNOTIFICATIONSTATUSENUM_PROCESSING RecoveryEscalationNotificationStatusEnum = "processing"
	RECOVERYESCALATIONNOTIFICATIONSTATUSENUM_SENT       RecoveryEscalationNotificationStatusEnum = "sent"
	RECOVERYESCALATIONNOTIFICATIONSTATUSENUM_FAILED     RecoveryEscalationNotificationStatusEnum = "failed"
	RECOVERYESCALATIONNOTIFICATIONSTATUSENUM_CANCELLED  RecoveryEscalationNotificationStatusEnum = "cancelled"
)

// All allowed values of RecoveryEscalationNotificationStatusEnum enum
var AllowedRecoveryEscalationNotificationStatusEnumEnumValues = []RecoveryEscalationNotificationStatusEnum{
	"pending",
	"processing",
	"sent",
	"failed",
	"cancelled",
}

func (v *RecoveryEscalationNotificationStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecoveryEscalationNotificationStatusEnum(value)
	for _, existing := range AllowedRecoveryEscalationNotificationStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecoveryEscalationNotificationStatusEnum", value)
}

// NewRecoveryEscalationNotificationStatusEnumFromValue returns a pointer to a valid RecoveryEscalationNotificationStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecoveryEscalationNotificationStatusEnumFromValue(v string) (*RecoveryEscalationNotificationStatusEnum, error) {
	ev := RecoveryEscalationNotificationStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecoveryEscalationNotificationStatusEnum: valid values are %v", v, AllowedRecoveryEscalationNotificationStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecoveryEscalationNotificationStatusEnum) IsValid() bool {
	for _, existing := range AllowedRecoveryEscalationNotificationStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecoveryEscalationNotificationStatusEnum value
func (v RecoveryEscalationNotificationStatusEnum) Ptr() *RecoveryEscalationNotificationStatusEnum {
	return &v
}

type NullableRecoveryEscalationNotificationStatusEnum struct {
	value *RecoveryEscalationNotificationStatusEnum
	isSet bool
}

func (v NullableRecoveryEscalationNotificationStatusEnum) Get() *RecoveryEscalationNotificationStatusEnum {
	return v.value
}

func (v *NullableRecoveryEscalationNotificationStatusEnum) Set(val *RecoveryEscalationNotificationStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryEscalationNotificationStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryEscalationNotificationStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryEscalationNotificationStatusEnum(val *RecoveryEscalationNotificationStatusEnum) *NullableRecoveryEscalationNotificationStatusEnum {
	return &NullableRecoveryEscalationNotificationStatusEnum{value: val, isSet: true}
}

func (v NullableRecoveryEscalationNotificationStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryEscalationNotificationStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
