/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleReportRequestReportTypeEnum * `compliance` - compliance * `retention_attestation` - retention_attestation * `legal_hold` - legal_hold * `archive_audit` - archive_audit * `purge_audit` - purge_audit * `complete_lifecycle` - complete_lifecycle
type LifecycleReportRequestReportTypeEnum string

// List of LifecycleReportRequestReportTypeEnum
const (
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_COMPLIANCE            LifecycleReportRequestReportTypeEnum = "compliance"
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_RETENTION_ATTESTATION LifecycleReportRequestReportTypeEnum = "retention_attestation"
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_LEGAL_HOLD            LifecycleReportRequestReportTypeEnum = "legal_hold"
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_ARCHIVE_AUDIT         LifecycleReportRequestReportTypeEnum = "archive_audit"
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_PURGE_AUDIT           LifecycleReportRequestReportTypeEnum = "purge_audit"
	LIFECYCLEREPORTREQUESTREPORTTYPEENUM_COMPLETE_LIFECYCLE    LifecycleReportRequestReportTypeEnum = "complete_lifecycle"
)

// All allowed values of LifecycleReportRequestReportTypeEnum enum
var AllowedLifecycleReportRequestReportTypeEnumEnumValues = []LifecycleReportRequestReportTypeEnum{
	"compliance",
	"retention_attestation",
	"legal_hold",
	"archive_audit",
	"purge_audit",
	"complete_lifecycle",
}

func (v *LifecycleReportRequestReportTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleReportRequestReportTypeEnum(value)
	for _, existing := range AllowedLifecycleReportRequestReportTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleReportRequestReportTypeEnum", value)
}

// NewLifecycleReportRequestReportTypeEnumFromValue returns a pointer to a valid LifecycleReportRequestReportTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleReportRequestReportTypeEnumFromValue(v string) (*LifecycleReportRequestReportTypeEnum, error) {
	ev := LifecycleReportRequestReportTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleReportRequestReportTypeEnum: valid values are %v", v, AllowedLifecycleReportRequestReportTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleReportRequestReportTypeEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleReportRequestReportTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleReportRequestReportTypeEnum value
func (v LifecycleReportRequestReportTypeEnum) Ptr() *LifecycleReportRequestReportTypeEnum {
	return &v
}

type NullableLifecycleReportRequestReportTypeEnum struct {
	value *LifecycleReportRequestReportTypeEnum
	isSet bool
}

func (v NullableLifecycleReportRequestReportTypeEnum) Get() *LifecycleReportRequestReportTypeEnum {
	return v.value
}

func (v *NullableLifecycleReportRequestReportTypeEnum) Set(val *LifecycleReportRequestReportTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleReportRequestReportTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleReportRequestReportTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleReportRequestReportTypeEnum(val *LifecycleReportRequestReportTypeEnum) *NullableLifecycleReportRequestReportTypeEnum {
	return &NullableLifecycleReportRequestReportTypeEnum{value: val, isSet: true}
}

func (v NullableLifecycleReportRequestReportTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleReportRequestReportTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
