/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AnalyticsDeadLetterBulkReplayItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsDeadLetterBulkReplayItem{}

// AnalyticsDeadLetterBulkReplayItem struct for AnalyticsDeadLetterBulkReplayItem
type AnalyticsDeadLetterBulkReplayItem struct {
	ResourceId string `json:"resource_id"`
	Outcome    string `json:"outcome"`
	Message    string `json:"message"`
}

type _AnalyticsDeadLetterBulkReplayItem AnalyticsDeadLetterBulkReplayItem

// NewAnalyticsDeadLetterBulkReplayItem instantiates a new AnalyticsDeadLetterBulkReplayItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsDeadLetterBulkReplayItem(resourceId string, outcome string, message string) *AnalyticsDeadLetterBulkReplayItem {
	this := AnalyticsDeadLetterBulkReplayItem{}
	this.ResourceId = resourceId
	this.Outcome = outcome
	this.Message = message
	return &this
}

// NewAnalyticsDeadLetterBulkReplayItemWithDefaults instantiates a new AnalyticsDeadLetterBulkReplayItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsDeadLetterBulkReplayItemWithDefaults() *AnalyticsDeadLetterBulkReplayItem {
	this := AnalyticsDeadLetterBulkReplayItem{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *AnalyticsDeadLetterBulkReplayItem) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterBulkReplayItem) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *AnalyticsDeadLetterBulkReplayItem) SetResourceId(v string) {
	o.ResourceId = v
}

// GetOutcome returns the Outcome field value
func (o *AnalyticsDeadLetterBulkReplayItem) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterBulkReplayItem) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *AnalyticsDeadLetterBulkReplayItem) SetOutcome(v string) {
	o.Outcome = v
}

// GetMessage returns the Message field value
func (o *AnalyticsDeadLetterBulkReplayItem) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterBulkReplayItem) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AnalyticsDeadLetterBulkReplayItem) SetMessage(v string) {
	o.Message = v
}

func (o AnalyticsDeadLetterBulkReplayItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsDeadLetterBulkReplayItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource_id"] = o.ResourceId
	toSerialize["outcome"] = o.Outcome
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *AnalyticsDeadLetterBulkReplayItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource_id",
		"outcome",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyticsDeadLetterBulkReplayItem := _AnalyticsDeadLetterBulkReplayItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyticsDeadLetterBulkReplayItem)

	if err != nil {
		return err
	}

	*o = AnalyticsDeadLetterBulkReplayItem(varAnalyticsDeadLetterBulkReplayItem)

	return err
}

type NullableAnalyticsDeadLetterBulkReplayItem struct {
	value *AnalyticsDeadLetterBulkReplayItem
	isSet bool
}

func (v NullableAnalyticsDeadLetterBulkReplayItem) Get() *AnalyticsDeadLetterBulkReplayItem {
	return v.value
}

func (v *NullableAnalyticsDeadLetterBulkReplayItem) Set(val *AnalyticsDeadLetterBulkReplayItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsDeadLetterBulkReplayItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsDeadLetterBulkReplayItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsDeadLetterBulkReplayItem(val *AnalyticsDeadLetterBulkReplayItem) *NullableAnalyticsDeadLetterBulkReplayItem {
	return &NullableAnalyticsDeadLetterBulkReplayItem{value: val, isSet: true}
}

func (v NullableAnalyticsDeadLetterBulkReplayItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsDeadLetterBulkReplayItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
