/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the FailoverSafetyRuleEvidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FailoverSafetyRuleEvidence{}

// FailoverSafetyRuleEvidence struct for FailoverSafetyRuleEvidence
type FailoverSafetyRuleEvidence struct {
	Sequence   int32       `json:"sequence"`
	Rule       string      `json:"rule"`
	Status     string      `json:"status"`
	ReasonCode string      `json:"reason_code"`
	Message    string      `json:"message"`
	Mandatory  bool        `json:"mandatory"`
	Evidence   interface{} `json:"evidence"`
	CreatedAt  time.Time   `json:"created_at"`
}

type _FailoverSafetyRuleEvidence FailoverSafetyRuleEvidence

// NewFailoverSafetyRuleEvidence instantiates a new FailoverSafetyRuleEvidence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFailoverSafetyRuleEvidence(sequence int32, rule string, status string, reasonCode string, message string, mandatory bool, evidence interface{}, createdAt time.Time) *FailoverSafetyRuleEvidence {
	this := FailoverSafetyRuleEvidence{}
	this.Sequence = sequence
	this.Rule = rule
	this.Status = status
	this.ReasonCode = reasonCode
	this.Message = message
	this.Mandatory = mandatory
	this.Evidence = evidence
	this.CreatedAt = createdAt
	return &this
}

// NewFailoverSafetyRuleEvidenceWithDefaults instantiates a new FailoverSafetyRuleEvidence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFailoverSafetyRuleEvidenceWithDefaults() *FailoverSafetyRuleEvidence {
	this := FailoverSafetyRuleEvidence{}
	return &this
}

// GetSequence returns the Sequence field value
func (o *FailoverSafetyRuleEvidence) GetSequence() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetSequenceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sequence, true
}

// SetSequence sets field value
func (o *FailoverSafetyRuleEvidence) SetSequence(v int32) {
	o.Sequence = v
}

// GetRule returns the Rule field value
func (o *FailoverSafetyRuleEvidence) GetRule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetRuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rule, true
}

// SetRule sets field value
func (o *FailoverSafetyRuleEvidence) SetRule(v string) {
	o.Rule = v
}

// GetStatus returns the Status field value
func (o *FailoverSafetyRuleEvidence) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FailoverSafetyRuleEvidence) SetStatus(v string) {
	o.Status = v
}

// GetReasonCode returns the ReasonCode field value
func (o *FailoverSafetyRuleEvidence) GetReasonCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReasonCode
}

// GetReasonCodeOk returns a tuple with the ReasonCode field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetReasonCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReasonCode, true
}

// SetReasonCode sets field value
func (o *FailoverSafetyRuleEvidence) SetReasonCode(v string) {
	o.ReasonCode = v
}

// GetMessage returns the Message field value
func (o *FailoverSafetyRuleEvidence) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *FailoverSafetyRuleEvidence) SetMessage(v string) {
	o.Message = v
}

// GetMandatory returns the Mandatory field value
func (o *FailoverSafetyRuleEvidence) GetMandatory() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Mandatory
}

// GetMandatoryOk returns a tuple with the Mandatory field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetMandatoryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mandatory, true
}

// SetMandatory sets field value
func (o *FailoverSafetyRuleEvidence) SetMandatory(v bool) {
	o.Mandatory = v
}

// GetEvidence returns the Evidence field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *FailoverSafetyRuleEvidence) GetEvidence() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FailoverSafetyRuleEvidence) GetEvidenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Evidence) {
		return nil, false
	}
	return &o.Evidence, true
}

// SetEvidence sets field value
func (o *FailoverSafetyRuleEvidence) SetEvidence(v interface{}) {
	o.Evidence = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *FailoverSafetyRuleEvidence) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FailoverSafetyRuleEvidence) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FailoverSafetyRuleEvidence) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o FailoverSafetyRuleEvidence) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FailoverSafetyRuleEvidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sequence"] = o.Sequence
	toSerialize["rule"] = o.Rule
	toSerialize["status"] = o.Status
	toSerialize["reason_code"] = o.ReasonCode
	toSerialize["message"] = o.Message
	toSerialize["mandatory"] = o.Mandatory
	if o.Evidence != nil {
		toSerialize["evidence"] = o.Evidence
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *FailoverSafetyRuleEvidence) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sequence",
		"rule",
		"status",
		"reason_code",
		"message",
		"mandatory",
		"evidence",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFailoverSafetyRuleEvidence := _FailoverSafetyRuleEvidence{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFailoverSafetyRuleEvidence)

	if err != nil {
		return err
	}

	*o = FailoverSafetyRuleEvidence(varFailoverSafetyRuleEvidence)

	return err
}

type NullableFailoverSafetyRuleEvidence struct {
	value *FailoverSafetyRuleEvidence
	isSet bool
}

func (v NullableFailoverSafetyRuleEvidence) Get() *FailoverSafetyRuleEvidence {
	return v.value
}

func (v *NullableFailoverSafetyRuleEvidence) Set(val *FailoverSafetyRuleEvidence) {
	v.value = val
	v.isSet = true
}

func (v NullableFailoverSafetyRuleEvidence) IsSet() bool {
	return v.isSet
}

func (v *NullableFailoverSafetyRuleEvidence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFailoverSafetyRuleEvidence(val *FailoverSafetyRuleEvidence) *NullableFailoverSafetyRuleEvidence {
	return &NullableFailoverSafetyRuleEvidence{value: val, isSet: true}
}

func (v NullableFailoverSafetyRuleEvidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFailoverSafetyRuleEvidence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
