/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OperatorRuntimeMetricsWorkers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeMetricsWorkers{}

// OperatorRuntimeMetricsWorkers struct for OperatorRuntimeMetricsWorkers
type OperatorRuntimeMetricsWorkers struct {
	Observed       int32   `json:"observed"`
	Live           int32   `json:"live"`
	Running        int32   `json:"running"`
	Starting       int32   `json:"starting"`
	Stale          int32   `json:"stale"`
	Failed         int32   `json:"failed"`
	Draining       int32   `json:"draining"`
	CapacityRatio  float64 `json:"capacity_ratio"`
	ProcessedTotal int32   `json:"processed_total"`
	FailureTotal   int32   `json:"failure_total"`
}

type _OperatorRuntimeMetricsWorkers OperatorRuntimeMetricsWorkers

// NewOperatorRuntimeMetricsWorkers instantiates a new OperatorRuntimeMetricsWorkers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeMetricsWorkers(observed int32, live int32, running int32, starting int32, stale int32, failed int32, draining int32, capacityRatio float64, processedTotal int32, failureTotal int32) *OperatorRuntimeMetricsWorkers {
	this := OperatorRuntimeMetricsWorkers{}
	this.Observed = observed
	this.Live = live
	this.Running = running
	this.Starting = starting
	this.Stale = stale
	this.Failed = failed
	this.Draining = draining
	this.CapacityRatio = capacityRatio
	this.ProcessedTotal = processedTotal
	this.FailureTotal = failureTotal
	return &this
}

// NewOperatorRuntimeMetricsWorkersWithDefaults instantiates a new OperatorRuntimeMetricsWorkers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeMetricsWorkersWithDefaults() *OperatorRuntimeMetricsWorkers {
	this := OperatorRuntimeMetricsWorkers{}
	return &this
}

// GetObserved returns the Observed field value
func (o *OperatorRuntimeMetricsWorkers) GetObserved() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Observed
}

// GetObservedOk returns a tuple with the Observed field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetObservedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Observed, true
}

// SetObserved sets field value
func (o *OperatorRuntimeMetricsWorkers) SetObserved(v int32) {
	o.Observed = v
}

// GetLive returns the Live field value
func (o *OperatorRuntimeMetricsWorkers) GetLive() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Live
}

// GetLiveOk returns a tuple with the Live field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetLiveOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Live, true
}

// SetLive sets field value
func (o *OperatorRuntimeMetricsWorkers) SetLive(v int32) {
	o.Live = v
}

// GetRunning returns the Running field value
func (o *OperatorRuntimeMetricsWorkers) GetRunning() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Running
}

// GetRunningOk returns a tuple with the Running field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetRunningOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Running, true
}

// SetRunning sets field value
func (o *OperatorRuntimeMetricsWorkers) SetRunning(v int32) {
	o.Running = v
}

// GetStarting returns the Starting field value
func (o *OperatorRuntimeMetricsWorkers) GetStarting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Starting
}

// GetStartingOk returns a tuple with the Starting field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetStartingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starting, true
}

// SetStarting sets field value
func (o *OperatorRuntimeMetricsWorkers) SetStarting(v int32) {
	o.Starting = v
}

// GetStale returns the Stale field value
func (o *OperatorRuntimeMetricsWorkers) GetStale() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Stale
}

// GetStaleOk returns a tuple with the Stale field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetStaleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stale, true
}

// SetStale sets field value
func (o *OperatorRuntimeMetricsWorkers) SetStale(v int32) {
	o.Stale = v
}

// GetFailed returns the Failed field value
func (o *OperatorRuntimeMetricsWorkers) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *OperatorRuntimeMetricsWorkers) SetFailed(v int32) {
	o.Failed = v
}

// GetDraining returns the Draining field value
func (o *OperatorRuntimeMetricsWorkers) GetDraining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Draining
}

// GetDrainingOk returns a tuple with the Draining field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetDrainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Draining, true
}

// SetDraining sets field value
func (o *OperatorRuntimeMetricsWorkers) SetDraining(v int32) {
	o.Draining = v
}

// GetCapacityRatio returns the CapacityRatio field value
func (o *OperatorRuntimeMetricsWorkers) GetCapacityRatio() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.CapacityRatio
}

// GetCapacityRatioOk returns a tuple with the CapacityRatio field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetCapacityRatioOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityRatio, true
}

// SetCapacityRatio sets field value
func (o *OperatorRuntimeMetricsWorkers) SetCapacityRatio(v float64) {
	o.CapacityRatio = v
}

// GetProcessedTotal returns the ProcessedTotal field value
func (o *OperatorRuntimeMetricsWorkers) GetProcessedTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProcessedTotal
}

// GetProcessedTotalOk returns a tuple with the ProcessedTotal field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetProcessedTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessedTotal, true
}

// SetProcessedTotal sets field value
func (o *OperatorRuntimeMetricsWorkers) SetProcessedTotal(v int32) {
	o.ProcessedTotal = v
}

// GetFailureTotal returns the FailureTotal field value
func (o *OperatorRuntimeMetricsWorkers) GetFailureTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailureTotal
}

// GetFailureTotalOk returns a tuple with the FailureTotal field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsWorkers) GetFailureTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureTotal, true
}

// SetFailureTotal sets field value
func (o *OperatorRuntimeMetricsWorkers) SetFailureTotal(v int32) {
	o.FailureTotal = v
}

func (o OperatorRuntimeMetricsWorkers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeMetricsWorkers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["observed"] = o.Observed
	toSerialize["live"] = o.Live
	toSerialize["running"] = o.Running
	toSerialize["starting"] = o.Starting
	toSerialize["stale"] = o.Stale
	toSerialize["failed"] = o.Failed
	toSerialize["draining"] = o.Draining
	toSerialize["capacity_ratio"] = o.CapacityRatio
	toSerialize["processed_total"] = o.ProcessedTotal
	toSerialize["failure_total"] = o.FailureTotal
	return toSerialize, nil
}

func (o *OperatorRuntimeMetricsWorkers) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"observed",
		"live",
		"running",
		"starting",
		"stale",
		"failed",
		"draining",
		"capacity_ratio",
		"processed_total",
		"failure_total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeMetricsWorkers := _OperatorRuntimeMetricsWorkers{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeMetricsWorkers)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeMetricsWorkers(varOperatorRuntimeMetricsWorkers)

	return err
}

type NullableOperatorRuntimeMetricsWorkers struct {
	value *OperatorRuntimeMetricsWorkers
	isSet bool
}

func (v NullableOperatorRuntimeMetricsWorkers) Get() *OperatorRuntimeMetricsWorkers {
	return v.value
}

func (v *NullableOperatorRuntimeMetricsWorkers) Set(val *OperatorRuntimeMetricsWorkers) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeMetricsWorkers) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeMetricsWorkers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeMetricsWorkers(val *OperatorRuntimeMetricsWorkers) *NullableOperatorRuntimeMetricsWorkers {
	return &NullableOperatorRuntimeMetricsWorkers{value: val, isSet: true}
}

func (v NullableOperatorRuntimeMetricsWorkers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeMetricsWorkers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
