/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AnalyticsDeadLetterRecoveryOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsDeadLetterRecoveryOperation{}

// AnalyticsDeadLetterRecoveryOperation struct for AnalyticsDeadLetterRecoveryOperation
type AnalyticsDeadLetterRecoveryOperation struct {
	Id                   string         `json:"id"`
	Operation            string         `json:"operation"`
	Status               string         `json:"status"`
	OrganizationId       string         `json:"organization_id"`
	ProjectionId         NullableString `json:"projection_id"`
	TargetResourceType   string         `json:"target_resource_type"`
	TargetResourceId     string         `json:"target_resource_id"`
	IdempotencyKey       string         `json:"idempotency_key"`
	PreviousState        interface{}    `json:"previous_state"`
	ResultingState       interface{}    `json:"resulting_state"`
	DispatchEvidence     interface{}    `json:"dispatch_evidence"`
	OperationFingerprint string         `json:"operation_fingerprint"`
}

type _AnalyticsDeadLetterRecoveryOperation AnalyticsDeadLetterRecoveryOperation

// NewAnalyticsDeadLetterRecoveryOperation instantiates a new AnalyticsDeadLetterRecoveryOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsDeadLetterRecoveryOperation(id string, operation string, status string, organizationId string, projectionId NullableString, targetResourceType string, targetResourceId string, idempotencyKey string, previousState interface{}, resultingState interface{}, dispatchEvidence interface{}, operationFingerprint string) *AnalyticsDeadLetterRecoveryOperation {
	this := AnalyticsDeadLetterRecoveryOperation{}
	this.Id = id
	this.Operation = operation
	this.Status = status
	this.OrganizationId = organizationId
	this.ProjectionId = projectionId
	this.TargetResourceType = targetResourceType
	this.TargetResourceId = targetResourceId
	this.IdempotencyKey = idempotencyKey
	this.PreviousState = previousState
	this.ResultingState = resultingState
	this.DispatchEvidence = dispatchEvidence
	this.OperationFingerprint = operationFingerprint
	return &this
}

// NewAnalyticsDeadLetterRecoveryOperationWithDefaults instantiates a new AnalyticsDeadLetterRecoveryOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsDeadLetterRecoveryOperationWithDefaults() *AnalyticsDeadLetterRecoveryOperation {
	this := AnalyticsDeadLetterRecoveryOperation{}
	return &this
}

// GetId returns the Id field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetId(v string) {
	o.Id = v
}

// GetOperation returns the Operation field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetOperation(v string) {
	o.Operation = v
}

// GetStatus returns the Status field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetStatus(v string) {
	o.Status = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetProjectionId returns the ProjectionId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetProjectionId() string {
	if o == nil || o.ProjectionId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProjectionId.Get()
}

// GetProjectionIdOk returns a tuple with the ProjectionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetProjectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectionId.Get(), o.ProjectionId.IsSet()
}

// SetProjectionId sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetProjectionId(v string) {
	o.ProjectionId.Set(&v)
}

// GetTargetResourceType returns the TargetResourceType field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetTargetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetResourceType
}

// GetTargetResourceTypeOk returns a tuple with the TargetResourceType field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetTargetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetResourceType, true
}

// SetTargetResourceType sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetTargetResourceType(v string) {
	o.TargetResourceType = v
}

// GetTargetResourceId returns the TargetResourceId field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetTargetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetResourceId
}

// GetTargetResourceIdOk returns a tuple with the TargetResourceId field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetTargetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetResourceId, true
}

// SetTargetResourceId sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetTargetResourceId(v string) {
	o.TargetResourceId = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetPreviousState returns the PreviousState field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetPreviousState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.PreviousState
}

// GetPreviousStateOk returns a tuple with the PreviousState field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetPreviousStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PreviousState) {
		return nil, false
	}
	return &o.PreviousState, true
}

// SetPreviousState sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetPreviousState(v interface{}) {
	o.PreviousState = v
}

// GetResultingState returns the ResultingState field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetResultingState() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ResultingState
}

// GetResultingStateOk returns a tuple with the ResultingState field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetResultingStateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ResultingState) {
		return nil, false
	}
	return &o.ResultingState, true
}

// SetResultingState sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetResultingState(v interface{}) {
	o.ResultingState = v
}

// GetDispatchEvidence returns the DispatchEvidence field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetDispatchEvidence() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DispatchEvidence
}

// GetDispatchEvidenceOk returns a tuple with the DispatchEvidence field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalyticsDeadLetterRecoveryOperation) GetDispatchEvidenceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DispatchEvidence) {
		return nil, false
	}
	return &o.DispatchEvidence, true
}

// SetDispatchEvidence sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetDispatchEvidence(v interface{}) {
	o.DispatchEvidence = v
}

// GetOperationFingerprint returns the OperationFingerprint field value
func (o *AnalyticsDeadLetterRecoveryOperation) GetOperationFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationFingerprint
}

// GetOperationFingerprintOk returns a tuple with the OperationFingerprint field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDeadLetterRecoveryOperation) GetOperationFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationFingerprint, true
}

// SetOperationFingerprint sets field value
func (o *AnalyticsDeadLetterRecoveryOperation) SetOperationFingerprint(v string) {
	o.OperationFingerprint = v
}

func (o AnalyticsDeadLetterRecoveryOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsDeadLetterRecoveryOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["operation"] = o.Operation
	toSerialize["status"] = o.Status
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["projection_id"] = o.ProjectionId.Get()
	toSerialize["target_resource_type"] = o.TargetResourceType
	toSerialize["target_resource_id"] = o.TargetResourceId
	toSerialize["idempotency_key"] = o.IdempotencyKey
	if o.PreviousState != nil {
		toSerialize["previous_state"] = o.PreviousState
	}
	if o.ResultingState != nil {
		toSerialize["resulting_state"] = o.ResultingState
	}
	if o.DispatchEvidence != nil {
		toSerialize["dispatch_evidence"] = o.DispatchEvidence
	}
	toSerialize["operation_fingerprint"] = o.OperationFingerprint
	return toSerialize, nil
}

func (o *AnalyticsDeadLetterRecoveryOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"operation",
		"status",
		"organization_id",
		"projection_id",
		"target_resource_type",
		"target_resource_id",
		"idempotency_key",
		"previous_state",
		"resulting_state",
		"dispatch_evidence",
		"operation_fingerprint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyticsDeadLetterRecoveryOperation := _AnalyticsDeadLetterRecoveryOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyticsDeadLetterRecoveryOperation)

	if err != nil {
		return err
	}

	*o = AnalyticsDeadLetterRecoveryOperation(varAnalyticsDeadLetterRecoveryOperation)

	return err
}

type NullableAnalyticsDeadLetterRecoveryOperation struct {
	value *AnalyticsDeadLetterRecoveryOperation
	isSet bool
}

func (v NullableAnalyticsDeadLetterRecoveryOperation) Get() *AnalyticsDeadLetterRecoveryOperation {
	return v.value
}

func (v *NullableAnalyticsDeadLetterRecoveryOperation) Set(val *AnalyticsDeadLetterRecoveryOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsDeadLetterRecoveryOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsDeadLetterRecoveryOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsDeadLetterRecoveryOperation(val *AnalyticsDeadLetterRecoveryOperation) *NullableAnalyticsDeadLetterRecoveryOperation {
	return &NullableAnalyticsDeadLetterRecoveryOperation{value: val, isSet: true}
}

func (v NullableAnalyticsDeadLetterRecoveryOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsDeadLetterRecoveryOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
