/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OperatorRuntimeIncidentNotificationActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeIncidentNotificationActionResponse{}

// OperatorRuntimeIncidentNotificationActionResponse struct for OperatorRuntimeIncidentNotificationActionResponse
type OperatorRuntimeIncidentNotificationActionResponse struct {
	OutboxId       string    `json:"outbox_id"`
	EventId        string    `json:"event_id"`
	Action         string    `json:"action"`
	PreviousStatus string    `json:"previous_status"`
	Status         string    `json:"status"`
	AttemptCount   int32     `json:"attempt_count"`
	MaxAttempts    int32     `json:"max_attempts"`
	NextAttemptAt  time.Time `json:"next_attempt_at"`
	Revision       int32     `json:"revision"`
	Actor          string    `json:"actor"`
	OccurredAt     time.Time `json:"occurred_at"`
}

type _OperatorRuntimeIncidentNotificationActionResponse OperatorRuntimeIncidentNotificationActionResponse

// NewOperatorRuntimeIncidentNotificationActionResponse instantiates a new OperatorRuntimeIncidentNotificationActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeIncidentNotificationActionResponse(outboxId string, eventId string, action string, previousStatus string, status string, attemptCount int32, maxAttempts int32, nextAttemptAt time.Time, revision int32, actor string, occurredAt time.Time) *OperatorRuntimeIncidentNotificationActionResponse {
	this := OperatorRuntimeIncidentNotificationActionResponse{}
	this.OutboxId = outboxId
	this.EventId = eventId
	this.Action = action
	this.PreviousStatus = previousStatus
	this.Status = status
	this.AttemptCount = attemptCount
	this.MaxAttempts = maxAttempts
	this.NextAttemptAt = nextAttemptAt
	this.Revision = revision
	this.Actor = actor
	this.OccurredAt = occurredAt
	return &this
}

// NewOperatorRuntimeIncidentNotificationActionResponseWithDefaults instantiates a new OperatorRuntimeIncidentNotificationActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeIncidentNotificationActionResponseWithDefaults() *OperatorRuntimeIncidentNotificationActionResponse {
	this := OperatorRuntimeIncidentNotificationActionResponse{}
	return &this
}

// GetOutboxId returns the OutboxId field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetOutboxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutboxId
}

// GetOutboxIdOk returns a tuple with the OutboxId field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetOutboxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutboxId, true
}

// SetOutboxId sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetOutboxId(v string) {
	o.OutboxId = v
}

// GetEventId returns the EventId field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetEventId(v string) {
	o.EventId = v
}

// GetAction returns the Action field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetAction(v string) {
	o.Action = v
}

// GetPreviousStatus returns the PreviousStatus field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetPreviousStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviousStatus
}

// GetPreviousStatusOk returns a tuple with the PreviousStatus field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetPreviousStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousStatus, true
}

// SetPreviousStatus sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetPreviousStatus(v string) {
	o.PreviousStatus = v
}

// GetStatus returns the Status field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetStatus(v string) {
	o.Status = v
}

// GetAttemptCount returns the AttemptCount field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetAttemptCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptCount
}

// GetAttemptCountOk returns a tuple with the AttemptCount field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetAttemptCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptCount, true
}

// SetAttemptCount sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetAttemptCount(v int32) {
	o.AttemptCount = v
}

// GetMaxAttempts returns the MaxAttempts field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetMaxAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAttempts, true
}

// SetMaxAttempts sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetMaxAttempts(v int32) {
	o.MaxAttempts = v
}

// GetNextAttemptAt returns the NextAttemptAt field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetNextAttemptAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.NextAttemptAt
}

// GetNextAttemptAtOk returns a tuple with the NextAttemptAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetNextAttemptAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextAttemptAt, true
}

// SetNextAttemptAt sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetNextAttemptAt(v time.Time) {
	o.NextAttemptAt = v
}

// GetRevision returns the Revision field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetRevision(v int32) {
	o.Revision = v
}

// GetActor returns the Actor field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetActor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Actor
}

// GetActorOk returns a tuple with the Actor field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetActorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Actor, true
}

// SetActor sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetActor(v string) {
	o.Actor = v
}

// GetOccurredAt returns the OccurredAt field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetOccurredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionResponse) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OccurredAt, true
}

// SetOccurredAt sets field value
func (o *OperatorRuntimeIncidentNotificationActionResponse) SetOccurredAt(v time.Time) {
	o.OccurredAt = v
}

func (o OperatorRuntimeIncidentNotificationActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeIncidentNotificationActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["outbox_id"] = o.OutboxId
	toSerialize["event_id"] = o.EventId
	toSerialize["action"] = o.Action
	toSerialize["previous_status"] = o.PreviousStatus
	toSerialize["status"] = o.Status
	toSerialize["attempt_count"] = o.AttemptCount
	toSerialize["max_attempts"] = o.MaxAttempts
	toSerialize["next_attempt_at"] = o.NextAttemptAt
	toSerialize["revision"] = o.Revision
	toSerialize["actor"] = o.Actor
	toSerialize["occurred_at"] = o.OccurredAt
	return toSerialize, nil
}

func (o *OperatorRuntimeIncidentNotificationActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"outbox_id",
		"event_id",
		"action",
		"previous_status",
		"status",
		"attempt_count",
		"max_attempts",
		"next_attempt_at",
		"revision",
		"actor",
		"occurred_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeIncidentNotificationActionResponse := _OperatorRuntimeIncidentNotificationActionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeIncidentNotificationActionResponse)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeIncidentNotificationActionResponse(varOperatorRuntimeIncidentNotificationActionResponse)

	return err
}

type NullableOperatorRuntimeIncidentNotificationActionResponse struct {
	value *OperatorRuntimeIncidentNotificationActionResponse
	isSet bool
}

func (v NullableOperatorRuntimeIncidentNotificationActionResponse) Get() *OperatorRuntimeIncidentNotificationActionResponse {
	return v.value
}

func (v *NullableOperatorRuntimeIncidentNotificationActionResponse) Set(val *OperatorRuntimeIncidentNotificationActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeIncidentNotificationActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeIncidentNotificationActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeIncidentNotificationActionResponse(val *OperatorRuntimeIncidentNotificationActionResponse) *NullableOperatorRuntimeIncidentNotificationActionResponse {
	return &NullableOperatorRuntimeIncidentNotificationActionResponse{value: val, isSet: true}
}

func (v NullableOperatorRuntimeIncidentNotificationActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeIncidentNotificationActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
