/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OperatorRuntimeMetricsDeliveries type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeMetricsDeliveries{}

// OperatorRuntimeMetricsDeliveries struct for OperatorRuntimeMetricsDeliveries
type OperatorRuntimeMetricsDeliveries struct {
	Pending          int32 `json:"pending"`
	Processing       int32 `json:"processing"`
	RetryScheduled   int32 `json:"retry_scheduled"`
	Backlog          int32 `json:"backlog"`
	Failed           int32 `json:"failed"`
	DeadLettered     int32 `json:"dead_lettered"`
	Exhausted        int32 `json:"exhausted"`
	TerminalFailures int32 `json:"terminal_failures"`
	StaleProcessing  int32 `json:"stale_processing"`
}

type _OperatorRuntimeMetricsDeliveries OperatorRuntimeMetricsDeliveries

// NewOperatorRuntimeMetricsDeliveries instantiates a new OperatorRuntimeMetricsDeliveries object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeMetricsDeliveries(pending int32, processing int32, retryScheduled int32, backlog int32, failed int32, deadLettered int32, exhausted int32, terminalFailures int32, staleProcessing int32) *OperatorRuntimeMetricsDeliveries {
	this := OperatorRuntimeMetricsDeliveries{}
	this.Pending = pending
	this.Processing = processing
	this.RetryScheduled = retryScheduled
	this.Backlog = backlog
	this.Failed = failed
	this.DeadLettered = deadLettered
	this.Exhausted = exhausted
	this.TerminalFailures = terminalFailures
	this.StaleProcessing = staleProcessing
	return &this
}

// NewOperatorRuntimeMetricsDeliveriesWithDefaults instantiates a new OperatorRuntimeMetricsDeliveries object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeMetricsDeliveriesWithDefaults() *OperatorRuntimeMetricsDeliveries {
	this := OperatorRuntimeMetricsDeliveries{}
	return &this
}

// GetPending returns the Pending field value
func (o *OperatorRuntimeMetricsDeliveries) GetPending() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetPendingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pending, true
}

// SetPending sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetPending(v int32) {
	o.Pending = v
}

// GetProcessing returns the Processing field value
func (o *OperatorRuntimeMetricsDeliveries) GetProcessing() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Processing
}

// GetProcessingOk returns a tuple with the Processing field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetProcessingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Processing, true
}

// SetProcessing sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetProcessing(v int32) {
	o.Processing = v
}

// GetRetryScheduled returns the RetryScheduled field value
func (o *OperatorRuntimeMetricsDeliveries) GetRetryScheduled() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryScheduled
}

// GetRetryScheduledOk returns a tuple with the RetryScheduled field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetRetryScheduledOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryScheduled, true
}

// SetRetryScheduled sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetRetryScheduled(v int32) {
	o.RetryScheduled = v
}

// GetBacklog returns the Backlog field value
func (o *OperatorRuntimeMetricsDeliveries) GetBacklog() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Backlog
}

// GetBacklogOk returns a tuple with the Backlog field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetBacklogOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backlog, true
}

// SetBacklog sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetBacklog(v int32) {
	o.Backlog = v
}

// GetFailed returns the Failed field value
func (o *OperatorRuntimeMetricsDeliveries) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetFailed(v int32) {
	o.Failed = v
}

// GetDeadLettered returns the DeadLettered field value
func (o *OperatorRuntimeMetricsDeliveries) GetDeadLettered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeadLettered
}

// GetDeadLetteredOk returns a tuple with the DeadLettered field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetDeadLetteredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeadLettered, true
}

// SetDeadLettered sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetDeadLettered(v int32) {
	o.DeadLettered = v
}

// GetExhausted returns the Exhausted field value
func (o *OperatorRuntimeMetricsDeliveries) GetExhausted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Exhausted
}

// GetExhaustedOk returns a tuple with the Exhausted field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetExhaustedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exhausted, true
}

// SetExhausted sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetExhausted(v int32) {
	o.Exhausted = v
}

// GetTerminalFailures returns the TerminalFailures field value
func (o *OperatorRuntimeMetricsDeliveries) GetTerminalFailures() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TerminalFailures
}

// GetTerminalFailuresOk returns a tuple with the TerminalFailures field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetTerminalFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TerminalFailures, true
}

// SetTerminalFailures sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetTerminalFailures(v int32) {
	o.TerminalFailures = v
}

// GetStaleProcessing returns the StaleProcessing field value
func (o *OperatorRuntimeMetricsDeliveries) GetStaleProcessing() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StaleProcessing
}

// GetStaleProcessingOk returns a tuple with the StaleProcessing field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsDeliveries) GetStaleProcessingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaleProcessing, true
}

// SetStaleProcessing sets field value
func (o *OperatorRuntimeMetricsDeliveries) SetStaleProcessing(v int32) {
	o.StaleProcessing = v
}

func (o OperatorRuntimeMetricsDeliveries) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeMetricsDeliveries) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pending"] = o.Pending
	toSerialize["processing"] = o.Processing
	toSerialize["retry_scheduled"] = o.RetryScheduled
	toSerialize["backlog"] = o.Backlog
	toSerialize["failed"] = o.Failed
	toSerialize["dead_lettered"] = o.DeadLettered
	toSerialize["exhausted"] = o.Exhausted
	toSerialize["terminal_failures"] = o.TerminalFailures
	toSerialize["stale_processing"] = o.StaleProcessing
	return toSerialize, nil
}

func (o *OperatorRuntimeMetricsDeliveries) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pending",
		"processing",
		"retry_scheduled",
		"backlog",
		"failed",
		"dead_lettered",
		"exhausted",
		"terminal_failures",
		"stale_processing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeMetricsDeliveries := _OperatorRuntimeMetricsDeliveries{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeMetricsDeliveries)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeMetricsDeliveries(varOperatorRuntimeMetricsDeliveries)

	return err
}

type NullableOperatorRuntimeMetricsDeliveries struct {
	value *OperatorRuntimeMetricsDeliveries
	isSet bool
}

func (v NullableOperatorRuntimeMetricsDeliveries) Get() *OperatorRuntimeMetricsDeliveries {
	return v.value
}

func (v *NullableOperatorRuntimeMetricsDeliveries) Set(val *OperatorRuntimeMetricsDeliveries) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeMetricsDeliveries) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeMetricsDeliveries) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeMetricsDeliveries(val *OperatorRuntimeMetricsDeliveries) *NullableOperatorRuntimeMetricsDeliveries {
	return &NullableOperatorRuntimeMetricsDeliveries{value: val, isSet: true}
}

func (v NullableOperatorRuntimeMetricsDeliveries) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeMetricsDeliveries) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
