/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RecoveryCancelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoveryCancelRequest{}

// RecoveryCancelRequest struct for RecoveryCancelRequest
type RecoveryCancelRequest struct {
	ExpectedRevision int32   `json:"expected_revision"`
	Reason           string  `json:"reason"`
	CorrelationId    *string `json:"correlation_id,omitempty"`
}

type _RecoveryCancelRequest RecoveryCancelRequest

// NewRecoveryCancelRequest instantiates a new RecoveryCancelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoveryCancelRequest(expectedRevision int32, reason string) *RecoveryCancelRequest {
	this := RecoveryCancelRequest{}
	this.ExpectedRevision = expectedRevision
	this.Reason = reason
	return &this
}

// NewRecoveryCancelRequestWithDefaults instantiates a new RecoveryCancelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoveryCancelRequestWithDefaults() *RecoveryCancelRequest {
	this := RecoveryCancelRequest{}
	return &this
}

// GetExpectedRevision returns the ExpectedRevision field value
func (o *RecoveryCancelRequest) GetExpectedRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedRevision
}

// GetExpectedRevisionOk returns a tuple with the ExpectedRevision field value
// and a boolean to check if the value has been set.
func (o *RecoveryCancelRequest) GetExpectedRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedRevision, true
}

// SetExpectedRevision sets field value
func (o *RecoveryCancelRequest) SetExpectedRevision(v int32) {
	o.ExpectedRevision = v
}

// GetReason returns the Reason field value
func (o *RecoveryCancelRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *RecoveryCancelRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *RecoveryCancelRequest) SetReason(v string) {
	o.Reason = v
}

// GetCorrelationId returns the CorrelationId field value if set, zero value otherwise.
func (o *RecoveryCancelRequest) GetCorrelationId() string {
	if o == nil || IsNil(o.CorrelationId) {
		var ret string
		return ret
	}
	return *o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoveryCancelRequest) GetCorrelationIdOk() (*string, bool) {
	if o == nil || IsNil(o.CorrelationId) {
		return nil, false
	}
	return o.CorrelationId, true
}

// HasCorrelationId returns a boolean if a field has been set.
func (o *RecoveryCancelRequest) HasCorrelationId() bool {
	if o != nil && !IsNil(o.CorrelationId) {
		return true
	}

	return false
}

// SetCorrelationId gets a reference to the given string and assigns it to the CorrelationId field.
func (o *RecoveryCancelRequest) SetCorrelationId(v string) {
	o.CorrelationId = &v
}

func (o RecoveryCancelRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoveryCancelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expected_revision"] = o.ExpectedRevision
	toSerialize["reason"] = o.Reason
	if !IsNil(o.CorrelationId) {
		toSerialize["correlation_id"] = o.CorrelationId
	}
	return toSerialize, nil
}

func (o *RecoveryCancelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expected_revision",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoveryCancelRequest := _RecoveryCancelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoveryCancelRequest)

	if err != nil {
		return err
	}

	*o = RecoveryCancelRequest(varRecoveryCancelRequest)

	return err
}

type NullableRecoveryCancelRequest struct {
	value *RecoveryCancelRequest
	isSet bool
}

func (v NullableRecoveryCancelRequest) Get() *RecoveryCancelRequest {
	return v.value
}

func (v *NullableRecoveryCancelRequest) Set(val *RecoveryCancelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryCancelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryCancelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryCancelRequest(val *RecoveryCancelRequest) *NullableRecoveryCancelRequest {
	return &NullableRecoveryCancelRequest{value: val, isSet: true}
}

func (v NullableRecoveryCancelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryCancelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
