/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AnalyticsDashboardValidationErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsDashboardValidationErrorResponse{}

// AnalyticsDashboardValidationErrorResponse struct for AnalyticsDashboardValidationErrorResponse
type AnalyticsDashboardValidationErrorResponse struct {
	Success bool                    `json:"success"`
	Data    interface{}             `json:"data"`
	Error   AnalyticsDashboardError `json:"error"`
	Meta    AnalyticsDashboardMeta  `json:"meta"`
}

type _AnalyticsDashboardValidationErrorResponse AnalyticsDashboardValidationErrorResponse

// NewAnalyticsDashboardValidationErrorResponse instantiates a new AnalyticsDashboardValidationErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsDashboardValidationErrorResponse(success bool, data interface{}, error_ AnalyticsDashboardError, meta AnalyticsDashboardMeta) *AnalyticsDashboardValidationErrorResponse {
	this := AnalyticsDashboardValidationErrorResponse{}
	this.Success = success
	this.Data = data
	this.Error = error_
	this.Meta = meta
	return &this
}

// NewAnalyticsDashboardValidationErrorResponseWithDefaults instantiates a new AnalyticsDashboardValidationErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsDashboardValidationErrorResponseWithDefaults() *AnalyticsDashboardValidationErrorResponse {
	this := AnalyticsDashboardValidationErrorResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *AnalyticsDashboardValidationErrorResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDashboardValidationErrorResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *AnalyticsDashboardValidationErrorResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AnalyticsDashboardValidationErrorResponse) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalyticsDashboardValidationErrorResponse) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AnalyticsDashboardValidationErrorResponse) SetData(v interface{}) {
	o.Data = v
}

// GetError returns the Error field value
func (o *AnalyticsDashboardValidationErrorResponse) GetError() AnalyticsDashboardError {
	if o == nil {
		var ret AnalyticsDashboardError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDashboardValidationErrorResponse) GetErrorOk() (*AnalyticsDashboardError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *AnalyticsDashboardValidationErrorResponse) SetError(v AnalyticsDashboardError) {
	o.Error = v
}

// GetMeta returns the Meta field value
func (o *AnalyticsDashboardValidationErrorResponse) GetMeta() AnalyticsDashboardMeta {
	if o == nil {
		var ret AnalyticsDashboardMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *AnalyticsDashboardValidationErrorResponse) GetMetaOk() (*AnalyticsDashboardMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *AnalyticsDashboardValidationErrorResponse) SetMeta(v AnalyticsDashboardMeta) {
	o.Meta = v
}

func (o AnalyticsDashboardValidationErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsDashboardValidationErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data
	toSerialize["error"] = o.Error
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *AnalyticsDashboardValidationErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
		"error",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyticsDashboardValidationErrorResponse := _AnalyticsDashboardValidationErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyticsDashboardValidationErrorResponse)

	if err != nil {
		return err
	}

	*o = AnalyticsDashboardValidationErrorResponse(varAnalyticsDashboardValidationErrorResponse)

	return err
}

type NullableAnalyticsDashboardValidationErrorResponse struct {
	value *AnalyticsDashboardValidationErrorResponse
	isSet bool
}

func (v NullableAnalyticsDashboardValidationErrorResponse) Get() *AnalyticsDashboardValidationErrorResponse {
	return v.value
}

func (v *NullableAnalyticsDashboardValidationErrorResponse) Set(val *AnalyticsDashboardValidationErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsDashboardValidationErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsDashboardValidationErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsDashboardValidationErrorResponse(val *AnalyticsDashboardValidationErrorResponse) *NullableAnalyticsDashboardValidationErrorResponse {
	return &NullableAnalyticsDashboardValidationErrorResponse{value: val, isSet: true}
}

func (v NullableAnalyticsDashboardValidationErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsDashboardValidationErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
