/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CheckpointRecoveryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckpointRecoveryRequest{}

// CheckpointRecoveryRequest struct for CheckpointRecoveryRequest
type CheckpointRecoveryRequest struct {
	OrganizationId            *string        `json:"organization_id,omitempty"`
	ProjectionId              string         `json:"projection_id"`
	IdempotencyKey            string         `json:"idempotency_key"`
	Reason                    string         `json:"reason"`
	ExpectedFencingGeneration int32          `json:"expected_fencing_generation"`
	ExpectedRebuildGeneration int32          `json:"expected_rebuild_generation"`
	Force                     *bool          `json:"force,omitempty"`
	ExpectedCursorOccurredAt  NullableTime   `json:"expected_cursor_occurred_at,omitempty"`
	ExpectedCursorEventId     NullableString `json:"expected_cursor_event_id,omitempty"`
	TargetCursorOccurredAt    NullableTime   `json:"target_cursor_occurred_at,omitempty"`
	TargetCursorEventId       NullableString `json:"target_cursor_event_id,omitempty"`
}

type _CheckpointRecoveryRequest CheckpointRecoveryRequest

// NewCheckpointRecoveryRequest instantiates a new CheckpointRecoveryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckpointRecoveryRequest(projectionId string, idempotencyKey string, reason string, expectedFencingGeneration int32, expectedRebuildGeneration int32) *CheckpointRecoveryRequest {
	this := CheckpointRecoveryRequest{}
	this.ProjectionId = projectionId
	this.IdempotencyKey = idempotencyKey
	this.Reason = reason
	this.ExpectedFencingGeneration = expectedFencingGeneration
	this.ExpectedRebuildGeneration = expectedRebuildGeneration
	var force bool = false
	this.Force = &force
	return &this
}

// NewCheckpointRecoveryRequestWithDefaults instantiates a new CheckpointRecoveryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckpointRecoveryRequestWithDefaults() *CheckpointRecoveryRequest {
	this := CheckpointRecoveryRequest{}
	var force bool = false
	this.Force = &force
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CheckpointRecoveryRequest) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *CheckpointRecoveryRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetProjectionId returns the ProjectionId field value
func (o *CheckpointRecoveryRequest) GetProjectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectionId
}

// GetProjectionIdOk returns a tuple with the ProjectionId field value
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetProjectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectionId, true
}

// SetProjectionId sets field value
func (o *CheckpointRecoveryRequest) SetProjectionId(v string) {
	o.ProjectionId = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *CheckpointRecoveryRequest) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *CheckpointRecoveryRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetReason returns the Reason field value
func (o *CheckpointRecoveryRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CheckpointRecoveryRequest) SetReason(v string) {
	o.Reason = v
}

// GetExpectedFencingGeneration returns the ExpectedFencingGeneration field value
func (o *CheckpointRecoveryRequest) GetExpectedFencingGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedFencingGeneration
}

// GetExpectedFencingGenerationOk returns a tuple with the ExpectedFencingGeneration field value
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetExpectedFencingGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedFencingGeneration, true
}

// SetExpectedFencingGeneration sets field value
func (o *CheckpointRecoveryRequest) SetExpectedFencingGeneration(v int32) {
	o.ExpectedFencingGeneration = v
}

// GetExpectedRebuildGeneration returns the ExpectedRebuildGeneration field value
func (o *CheckpointRecoveryRequest) GetExpectedRebuildGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpectedRebuildGeneration
}

// GetExpectedRebuildGenerationOk returns a tuple with the ExpectedRebuildGeneration field value
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetExpectedRebuildGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedRebuildGeneration, true
}

// SetExpectedRebuildGeneration sets field value
func (o *CheckpointRecoveryRequest) SetExpectedRebuildGeneration(v int32) {
	o.ExpectedRebuildGeneration = v
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *CheckpointRecoveryRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckpointRecoveryRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *CheckpointRecoveryRequest) SetForce(v bool) {
	o.Force = &v
}

// GetExpectedCursorOccurredAt returns the ExpectedCursorOccurredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckpointRecoveryRequest) GetExpectedCursorOccurredAt() time.Time {
	if o == nil || IsNil(o.ExpectedCursorOccurredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpectedCursorOccurredAt.Get()
}

// GetExpectedCursorOccurredAtOk returns a tuple with the ExpectedCursorOccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckpointRecoveryRequest) GetExpectedCursorOccurredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedCursorOccurredAt.Get(), o.ExpectedCursorOccurredAt.IsSet()
}

// HasExpectedCursorOccurredAt returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasExpectedCursorOccurredAt() bool {
	if o != nil && o.ExpectedCursorOccurredAt.IsSet() {
		return true
	}

	return false
}

// SetExpectedCursorOccurredAt gets a reference to the given NullableTime and assigns it to the ExpectedCursorOccurredAt field.
func (o *CheckpointRecoveryRequest) SetExpectedCursorOccurredAt(v time.Time) {
	o.ExpectedCursorOccurredAt.Set(&v)
}

// SetExpectedCursorOccurredAtNil sets the value for ExpectedCursorOccurredAt to be an explicit nil
func (o *CheckpointRecoveryRequest) SetExpectedCursorOccurredAtNil() {
	o.ExpectedCursorOccurredAt.Set(nil)
}

// UnsetExpectedCursorOccurredAt ensures that no value is present for ExpectedCursorOccurredAt, not even an explicit nil
func (o *CheckpointRecoveryRequest) UnsetExpectedCursorOccurredAt() {
	o.ExpectedCursorOccurredAt.Unset()
}

// GetExpectedCursorEventId returns the ExpectedCursorEventId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckpointRecoveryRequest) GetExpectedCursorEventId() string {
	if o == nil || IsNil(o.ExpectedCursorEventId.Get()) {
		var ret string
		return ret
	}
	return *o.ExpectedCursorEventId.Get()
}

// GetExpectedCursorEventIdOk returns a tuple with the ExpectedCursorEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckpointRecoveryRequest) GetExpectedCursorEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedCursorEventId.Get(), o.ExpectedCursorEventId.IsSet()
}

// HasExpectedCursorEventId returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasExpectedCursorEventId() bool {
	if o != nil && o.ExpectedCursorEventId.IsSet() {
		return true
	}

	return false
}

// SetExpectedCursorEventId gets a reference to the given NullableString and assigns it to the ExpectedCursorEventId field.
func (o *CheckpointRecoveryRequest) SetExpectedCursorEventId(v string) {
	o.ExpectedCursorEventId.Set(&v)
}

// SetExpectedCursorEventIdNil sets the value for ExpectedCursorEventId to be an explicit nil
func (o *CheckpointRecoveryRequest) SetExpectedCursorEventIdNil() {
	o.ExpectedCursorEventId.Set(nil)
}

// UnsetExpectedCursorEventId ensures that no value is present for ExpectedCursorEventId, not even an explicit nil
func (o *CheckpointRecoveryRequest) UnsetExpectedCursorEventId() {
	o.ExpectedCursorEventId.Unset()
}

// GetTargetCursorOccurredAt returns the TargetCursorOccurredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckpointRecoveryRequest) GetTargetCursorOccurredAt() time.Time {
	if o == nil || IsNil(o.TargetCursorOccurredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TargetCursorOccurredAt.Get()
}

// GetTargetCursorOccurredAtOk returns a tuple with the TargetCursorOccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckpointRecoveryRequest) GetTargetCursorOccurredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetCursorOccurredAt.Get(), o.TargetCursorOccurredAt.IsSet()
}

// HasTargetCursorOccurredAt returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasTargetCursorOccurredAt() bool {
	if o != nil && o.TargetCursorOccurredAt.IsSet() {
		return true
	}

	return false
}

// SetTargetCursorOccurredAt gets a reference to the given NullableTime and assigns it to the TargetCursorOccurredAt field.
func (o *CheckpointRecoveryRequest) SetTargetCursorOccurredAt(v time.Time) {
	o.TargetCursorOccurredAt.Set(&v)
}

// SetTargetCursorOccurredAtNil sets the value for TargetCursorOccurredAt to be an explicit nil
func (o *CheckpointRecoveryRequest) SetTargetCursorOccurredAtNil() {
	o.TargetCursorOccurredAt.Set(nil)
}

// UnsetTargetCursorOccurredAt ensures that no value is present for TargetCursorOccurredAt, not even an explicit nil
func (o *CheckpointRecoveryRequest) UnsetTargetCursorOccurredAt() {
	o.TargetCursorOccurredAt.Unset()
}

// GetTargetCursorEventId returns the TargetCursorEventId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckpointRecoveryRequest) GetTargetCursorEventId() string {
	if o == nil || IsNil(o.TargetCursorEventId.Get()) {
		var ret string
		return ret
	}
	return *o.TargetCursorEventId.Get()
}

// GetTargetCursorEventIdOk returns a tuple with the TargetCursorEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckpointRecoveryRequest) GetTargetCursorEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetCursorEventId.Get(), o.TargetCursorEventId.IsSet()
}

// HasTargetCursorEventId returns a boolean if a field has been set.
func (o *CheckpointRecoveryRequest) HasTargetCursorEventId() bool {
	if o != nil && o.TargetCursorEventId.IsSet() {
		return true
	}

	return false
}

// SetTargetCursorEventId gets a reference to the given NullableString and assigns it to the TargetCursorEventId field.
func (o *CheckpointRecoveryRequest) SetTargetCursorEventId(v string) {
	o.TargetCursorEventId.Set(&v)
}

// SetTargetCursorEventIdNil sets the value for TargetCursorEventId to be an explicit nil
func (o *CheckpointRecoveryRequest) SetTargetCursorEventIdNil() {
	o.TargetCursorEventId.Set(nil)
}

// UnsetTargetCursorEventId ensures that no value is present for TargetCursorEventId, not even an explicit nil
func (o *CheckpointRecoveryRequest) UnsetTargetCursorEventId() {
	o.TargetCursorEventId.Unset()
}

func (o CheckpointRecoveryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckpointRecoveryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	toSerialize["projection_id"] = o.ProjectionId
	toSerialize["idempotency_key"] = o.IdempotencyKey
	toSerialize["reason"] = o.Reason
	toSerialize["expected_fencing_generation"] = o.ExpectedFencingGeneration
	toSerialize["expected_rebuild_generation"] = o.ExpectedRebuildGeneration
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	if o.ExpectedCursorOccurredAt.IsSet() {
		toSerialize["expected_cursor_occurred_at"] = o.ExpectedCursorOccurredAt.Get()
	}
	if o.ExpectedCursorEventId.IsSet() {
		toSerialize["expected_cursor_event_id"] = o.ExpectedCursorEventId.Get()
	}
	if o.TargetCursorOccurredAt.IsSet() {
		toSerialize["target_cursor_occurred_at"] = o.TargetCursorOccurredAt.Get()
	}
	if o.TargetCursorEventId.IsSet() {
		toSerialize["target_cursor_event_id"] = o.TargetCursorEventId.Get()
	}
	return toSerialize, nil
}

func (o *CheckpointRecoveryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projection_id",
		"idempotency_key",
		"reason",
		"expected_fencing_generation",
		"expected_rebuild_generation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckpointRecoveryRequest := _CheckpointRecoveryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckpointRecoveryRequest)

	if err != nil {
		return err
	}

	*o = CheckpointRecoveryRequest(varCheckpointRecoveryRequest)

	return err
}

type NullableCheckpointRecoveryRequest struct {
	value *CheckpointRecoveryRequest
	isSet bool
}

func (v NullableCheckpointRecoveryRequest) Get() *CheckpointRecoveryRequest {
	return v.value
}

func (v *NullableCheckpointRecoveryRequest) Set(val *CheckpointRecoveryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckpointRecoveryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckpointRecoveryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckpointRecoveryRequest(val *CheckpointRecoveryRequest) *NullableCheckpointRecoveryRequest {
	return &NullableCheckpointRecoveryRequest{value: val, isSet: true}
}

func (v NullableCheckpointRecoveryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckpointRecoveryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
