/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RegionalFailoverVerification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionalFailoverVerification{}

// RegionalFailoverVerification struct for RegionalFailoverVerification
type RegionalFailoverVerification struct {
	Id                        string                              `json:"id"`
	OrganizationId            string                              `json:"organization_id"`
	ExecutionId               string                              `json:"execution_id"`
	TopologyId                string                              `json:"topology_id"`
	SourceRegionId            string                              `json:"source_region_id"`
	TargetRegionId            string                              `json:"target_region_id"`
	ContextFingerprint        string                              `json:"context_fingerprint"`
	ReportFingerprint         string                              `json:"report_fingerprint"`
	Status                    string                              `json:"status"`
	TopologyRevision          int64                               `json:"topology_revision"`
	ExpectedAuthorityRegionId string                              `json:"expected_authority_region_id"`
	ExpectedAuthorityEpoch    int64                               `json:"expected_authority_epoch"`
	ExpectedFencingToken      string                              `json:"expected_fencing_token"`
	ObservedAuthorityRegionId string                              `json:"observed_authority_region_id"`
	ObservedAuthorityEpoch    int64                               `json:"observed_authority_epoch"`
	ObservedFencingToken      string                              `json:"observed_fencing_token"`
	ObservedAt                time.Time                           `json:"observed_at"`
	VerifiedAt                time.Time                           `json:"verified_at"`
	Metadata                  interface{}                         `json:"metadata,omitempty"`
	Checks                    []RegionalFailoverVerificationCheck `json:"checks"`
	Drifts                    []RegionalFailoverDrift             `json:"drifts"`
	CreatedAt                 time.Time                           `json:"created_at"`
}

type _RegionalFailoverVerification RegionalFailoverVerification

// NewRegionalFailoverVerification instantiates a new RegionalFailoverVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionalFailoverVerification(id string, organizationId string, executionId string, topologyId string, sourceRegionId string, targetRegionId string, contextFingerprint string, reportFingerprint string, status string, topologyRevision int64, expectedAuthorityRegionId string, expectedAuthorityEpoch int64, expectedFencingToken string, observedAuthorityRegionId string, observedAuthorityEpoch int64, observedFencingToken string, observedAt time.Time, verifiedAt time.Time, checks []RegionalFailoverVerificationCheck, drifts []RegionalFailoverDrift, createdAt time.Time) *RegionalFailoverVerification {
	this := RegionalFailoverVerification{}
	this.Id = id
	this.OrganizationId = organizationId
	this.ExecutionId = executionId
	this.TopologyId = topologyId
	this.SourceRegionId = sourceRegionId
	this.TargetRegionId = targetRegionId
	this.ContextFingerprint = contextFingerprint
	this.ReportFingerprint = reportFingerprint
	this.Status = status
	this.TopologyRevision = topologyRevision
	this.ExpectedAuthorityRegionId = expectedAuthorityRegionId
	this.ExpectedAuthorityEpoch = expectedAuthorityEpoch
	this.ExpectedFencingToken = expectedFencingToken
	this.ObservedAuthorityRegionId = observedAuthorityRegionId
	this.ObservedAuthorityEpoch = observedAuthorityEpoch
	this.ObservedFencingToken = observedFencingToken
	this.ObservedAt = observedAt
	this.VerifiedAt = verifiedAt
	this.Checks = checks
	this.Drifts = drifts
	this.CreatedAt = createdAt
	return &this
}

// NewRegionalFailoverVerificationWithDefaults instantiates a new RegionalFailoverVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionalFailoverVerificationWithDefaults() *RegionalFailoverVerification {
	this := RegionalFailoverVerification{}
	return &this
}

// GetId returns the Id field value
func (o *RegionalFailoverVerification) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegionalFailoverVerification) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *RegionalFailoverVerification) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RegionalFailoverVerification) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetExecutionId returns the ExecutionId field value
func (o *RegionalFailoverVerification) GetExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionId, true
}

// SetExecutionId sets field value
func (o *RegionalFailoverVerification) SetExecutionId(v string) {
	o.ExecutionId = v
}

// GetTopologyId returns the TopologyId field value
func (o *RegionalFailoverVerification) GetTopologyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TopologyId
}

// GetTopologyIdOk returns a tuple with the TopologyId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetTopologyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopologyId, true
}

// SetTopologyId sets field value
func (o *RegionalFailoverVerification) SetTopologyId(v string) {
	o.TopologyId = v
}

// GetSourceRegionId returns the SourceRegionId field value
func (o *RegionalFailoverVerification) GetSourceRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRegionId
}

// GetSourceRegionIdOk returns a tuple with the SourceRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetSourceRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRegionId, true
}

// SetSourceRegionId sets field value
func (o *RegionalFailoverVerification) SetSourceRegionId(v string) {
	o.SourceRegionId = v
}

// GetTargetRegionId returns the TargetRegionId field value
func (o *RegionalFailoverVerification) GetTargetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetRegionId
}

// GetTargetRegionIdOk returns a tuple with the TargetRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetTargetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetRegionId, true
}

// SetTargetRegionId sets field value
func (o *RegionalFailoverVerification) SetTargetRegionId(v string) {
	o.TargetRegionId = v
}

// GetContextFingerprint returns the ContextFingerprint field value
func (o *RegionalFailoverVerification) GetContextFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextFingerprint
}

// GetContextFingerprintOk returns a tuple with the ContextFingerprint field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetContextFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextFingerprint, true
}

// SetContextFingerprint sets field value
func (o *RegionalFailoverVerification) SetContextFingerprint(v string) {
	o.ContextFingerprint = v
}

// GetReportFingerprint returns the ReportFingerprint field value
func (o *RegionalFailoverVerification) GetReportFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReportFingerprint
}

// GetReportFingerprintOk returns a tuple with the ReportFingerprint field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetReportFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportFingerprint, true
}

// SetReportFingerprint sets field value
func (o *RegionalFailoverVerification) SetReportFingerprint(v string) {
	o.ReportFingerprint = v
}

// GetStatus returns the Status field value
func (o *RegionalFailoverVerification) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RegionalFailoverVerification) SetStatus(v string) {
	o.Status = v
}

// GetTopologyRevision returns the TopologyRevision field value
func (o *RegionalFailoverVerification) GetTopologyRevision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TopologyRevision
}

// GetTopologyRevisionOk returns a tuple with the TopologyRevision field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetTopologyRevisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopologyRevision, true
}

// SetTopologyRevision sets field value
func (o *RegionalFailoverVerification) SetTopologyRevision(v int64) {
	o.TopologyRevision = v
}

// GetExpectedAuthorityRegionId returns the ExpectedAuthorityRegionId field value
func (o *RegionalFailoverVerification) GetExpectedAuthorityRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedAuthorityRegionId
}

// GetExpectedAuthorityRegionIdOk returns a tuple with the ExpectedAuthorityRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetExpectedAuthorityRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAuthorityRegionId, true
}

// SetExpectedAuthorityRegionId sets field value
func (o *RegionalFailoverVerification) SetExpectedAuthorityRegionId(v string) {
	o.ExpectedAuthorityRegionId = v
}

// GetExpectedAuthorityEpoch returns the ExpectedAuthorityEpoch field value
func (o *RegionalFailoverVerification) GetExpectedAuthorityEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpectedAuthorityEpoch
}

// GetExpectedAuthorityEpochOk returns a tuple with the ExpectedAuthorityEpoch field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetExpectedAuthorityEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedAuthorityEpoch, true
}

// SetExpectedAuthorityEpoch sets field value
func (o *RegionalFailoverVerification) SetExpectedAuthorityEpoch(v int64) {
	o.ExpectedAuthorityEpoch = v
}

// GetExpectedFencingToken returns the ExpectedFencingToken field value
func (o *RegionalFailoverVerification) GetExpectedFencingToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedFencingToken
}

// GetExpectedFencingTokenOk returns a tuple with the ExpectedFencingToken field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetExpectedFencingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedFencingToken, true
}

// SetExpectedFencingToken sets field value
func (o *RegionalFailoverVerification) SetExpectedFencingToken(v string) {
	o.ExpectedFencingToken = v
}

// GetObservedAuthorityRegionId returns the ObservedAuthorityRegionId field value
func (o *RegionalFailoverVerification) GetObservedAuthorityRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObservedAuthorityRegionId
}

// GetObservedAuthorityRegionIdOk returns a tuple with the ObservedAuthorityRegionId field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetObservedAuthorityRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAuthorityRegionId, true
}

// SetObservedAuthorityRegionId sets field value
func (o *RegionalFailoverVerification) SetObservedAuthorityRegionId(v string) {
	o.ObservedAuthorityRegionId = v
}

// GetObservedAuthorityEpoch returns the ObservedAuthorityEpoch field value
func (o *RegionalFailoverVerification) GetObservedAuthorityEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ObservedAuthorityEpoch
}

// GetObservedAuthorityEpochOk returns a tuple with the ObservedAuthorityEpoch field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetObservedAuthorityEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAuthorityEpoch, true
}

// SetObservedAuthorityEpoch sets field value
func (o *RegionalFailoverVerification) SetObservedAuthorityEpoch(v int64) {
	o.ObservedAuthorityEpoch = v
}

// GetObservedFencingToken returns the ObservedFencingToken field value
func (o *RegionalFailoverVerification) GetObservedFencingToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObservedFencingToken
}

// GetObservedFencingTokenOk returns a tuple with the ObservedFencingToken field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetObservedFencingTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedFencingToken, true
}

// SetObservedFencingToken sets field value
func (o *RegionalFailoverVerification) SetObservedFencingToken(v string) {
	o.ObservedFencingToken = v
}

// GetObservedAt returns the ObservedAt field value
func (o *RegionalFailoverVerification) GetObservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetObservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedAt, true
}

// SetObservedAt sets field value
func (o *RegionalFailoverVerification) SetObservedAt(v time.Time) {
	o.ObservedAt = v
}

// GetVerifiedAt returns the VerifiedAt field value
func (o *RegionalFailoverVerification) GetVerifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifiedAt, true
}

// SetVerifiedAt sets field value
func (o *RegionalFailoverVerification) SetVerifiedAt(v time.Time) {
	o.VerifiedAt = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionalFailoverVerification) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionalFailoverVerification) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RegionalFailoverVerification) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *RegionalFailoverVerification) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetChecks returns the Checks field value
func (o *RegionalFailoverVerification) GetChecks() []RegionalFailoverVerificationCheck {
	if o == nil {
		var ret []RegionalFailoverVerificationCheck
		return ret
	}

	return o.Checks
}

// GetChecksOk returns a tuple with the Checks field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetChecksOk() ([]RegionalFailoverVerificationCheck, bool) {
	if o == nil {
		return nil, false
	}
	return o.Checks, true
}

// SetChecks sets field value
func (o *RegionalFailoverVerification) SetChecks(v []RegionalFailoverVerificationCheck) {
	o.Checks = v
}

// GetDrifts returns the Drifts field value
func (o *RegionalFailoverVerification) GetDrifts() []RegionalFailoverDrift {
	if o == nil {
		var ret []RegionalFailoverDrift
		return ret
	}

	return o.Drifts
}

// GetDriftsOk returns a tuple with the Drifts field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetDriftsOk() ([]RegionalFailoverDrift, bool) {
	if o == nil {
		return nil, false
	}
	return o.Drifts, true
}

// SetDrifts sets field value
func (o *RegionalFailoverVerification) SetDrifts(v []RegionalFailoverDrift) {
	o.Drifts = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RegionalFailoverVerification) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RegionalFailoverVerification) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RegionalFailoverVerification) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o RegionalFailoverVerification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionalFailoverVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["context_fingerprint"] = o.ContextFingerprint
	toSerialize["report_fingerprint"] = o.ReportFingerprint
	toSerialize["status"] = o.Status
	toSerialize["topology_revision"] = o.TopologyRevision
	toSerialize["expected_authority_region_id"] = o.ExpectedAuthorityRegionId
	toSerialize["expected_authority_epoch"] = o.ExpectedAuthorityEpoch
	toSerialize["expected_fencing_token"] = o.ExpectedFencingToken
	toSerialize["observed_authority_region_id"] = o.ObservedAuthorityRegionId
	toSerialize["observed_authority_epoch"] = o.ObservedAuthorityEpoch
	toSerialize["observed_fencing_token"] = o.ObservedFencingToken
	toSerialize["observed_at"] = o.ObservedAt
	toSerialize["verified_at"] = o.VerifiedAt
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *RegionalFailoverVerification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organization_id",
		"execution_id",
		"topology_id",
		"source_region_id",
		"target_region_id",
		"context_fingerprint",
		"report_fingerprint",
		"status",
		"topology_revision",
		"expected_authority_region_id",
		"expected_authority_epoch",
		"expected_fencing_token",
		"observed_authority_region_id",
		"observed_authority_epoch",
		"observed_fencing_token",
		"observed_at",
		"verified_at",
		"checks",
		"drifts",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionalFailoverVerification := _RegionalFailoverVerification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionalFailoverVerification)

	if err != nil {
		return err
	}

	*o = RegionalFailoverVerification(varRegionalFailoverVerification)

	return err
}

type NullableRegionalFailoverVerification struct {
	value *RegionalFailoverVerification
	isSet bool
}

func (v NullableRegionalFailoverVerification) Get() *RegionalFailoverVerification {
	return v.value
}

func (v *NullableRegionalFailoverVerification) Set(val *RegionalFailoverVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionalFailoverVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionalFailoverVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionalFailoverVerification(val *RegionalFailoverVerification) *NullableRegionalFailoverVerification {
	return &NullableRegionalFailoverVerification{value: val, isSet: true}
}

func (v NullableRegionalFailoverVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionalFailoverVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
