/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LifecycleReportRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecycleReportRequestRequest{}

// LifecycleReportRequestRequest struct for LifecycleReportRequestRequest
type LifecycleReportRequestRequest struct {
	ReportType          LifecycleReportRequestReportTypeEnum `json:"report_type"`
	IdempotencyKey      string                               `json:"idempotency_key"`
	ExpiresInDays       *int32                               `json:"expires_in_days,omitempty"`
	GenerateImmediately *bool                                `json:"generate_immediately,omitempty"`
}

type _LifecycleReportRequestRequest LifecycleReportRequestRequest

// NewLifecycleReportRequestRequest instantiates a new LifecycleReportRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecycleReportRequestRequest(reportType LifecycleReportRequestReportTypeEnum, idempotencyKey string) *LifecycleReportRequestRequest {
	this := LifecycleReportRequestRequest{}
	this.ReportType = reportType
	this.IdempotencyKey = idempotencyKey
	var expiresInDays int32 = 30
	this.ExpiresInDays = &expiresInDays
	var generateImmediately bool = true
	this.GenerateImmediately = &generateImmediately
	return &this
}

// NewLifecycleReportRequestRequestWithDefaults instantiates a new LifecycleReportRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecycleReportRequestRequestWithDefaults() *LifecycleReportRequestRequest {
	this := LifecycleReportRequestRequest{}
	var expiresInDays int32 = 30
	this.ExpiresInDays = &expiresInDays
	var generateImmediately bool = true
	this.GenerateImmediately = &generateImmediately
	return &this
}

// GetReportType returns the ReportType field value
func (o *LifecycleReportRequestRequest) GetReportType() LifecycleReportRequestReportTypeEnum {
	if o == nil {
		var ret LifecycleReportRequestReportTypeEnum
		return ret
	}

	return o.ReportType
}

// GetReportTypeOk returns a tuple with the ReportType field value
// and a boolean to check if the value has been set.
func (o *LifecycleReportRequestRequest) GetReportTypeOk() (*LifecycleReportRequestReportTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportType, true
}

// SetReportType sets field value
func (o *LifecycleReportRequestRequest) SetReportType(v LifecycleReportRequestReportTypeEnum) {
	o.ReportType = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *LifecycleReportRequestRequest) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *LifecycleReportRequestRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *LifecycleReportRequestRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetExpiresInDays returns the ExpiresInDays field value if set, zero value otherwise.
func (o *LifecycleReportRequestRequest) GetExpiresInDays() int32 {
	if o == nil || IsNil(o.ExpiresInDays) {
		var ret int32
		return ret
	}
	return *o.ExpiresInDays
}

// GetExpiresInDaysOk returns a tuple with the ExpiresInDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecycleReportRequestRequest) GetExpiresInDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresInDays) {
		return nil, false
	}
	return o.ExpiresInDays, true
}

// HasExpiresInDays returns a boolean if a field has been set.
func (o *LifecycleReportRequestRequest) HasExpiresInDays() bool {
	if o != nil && !IsNil(o.ExpiresInDays) {
		return true
	}

	return false
}

// SetExpiresInDays gets a reference to the given int32 and assigns it to the ExpiresInDays field.
func (o *LifecycleReportRequestRequest) SetExpiresInDays(v int32) {
	o.ExpiresInDays = &v
}

// GetGenerateImmediately returns the GenerateImmediately field value if set, zero value otherwise.
func (o *LifecycleReportRequestRequest) GetGenerateImmediately() bool {
	if o == nil || IsNil(o.GenerateImmediately) {
		var ret bool
		return ret
	}
	return *o.GenerateImmediately
}

// GetGenerateImmediatelyOk returns a tuple with the GenerateImmediately field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecycleReportRequestRequest) GetGenerateImmediatelyOk() (*bool, bool) {
	if o == nil || IsNil(o.GenerateImmediately) {
		return nil, false
	}
	return o.GenerateImmediately, true
}

// HasGenerateImmediately returns a boolean if a field has been set.
func (o *LifecycleReportRequestRequest) HasGenerateImmediately() bool {
	if o != nil && !IsNil(o.GenerateImmediately) {
		return true
	}

	return false
}

// SetGenerateImmediately gets a reference to the given bool and assigns it to the GenerateImmediately field.
func (o *LifecycleReportRequestRequest) SetGenerateImmediately(v bool) {
	o.GenerateImmediately = &v
}

func (o LifecycleReportRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecycleReportRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["report_type"] = o.ReportType
	toSerialize["idempotency_key"] = o.IdempotencyKey
	if !IsNil(o.ExpiresInDays) {
		toSerialize["expires_in_days"] = o.ExpiresInDays
	}
	if !IsNil(o.GenerateImmediately) {
		toSerialize["generate_immediately"] = o.GenerateImmediately
	}
	return toSerialize, nil
}

func (o *LifecycleReportRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"report_type",
		"idempotency_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLifecycleReportRequestRequest := _LifecycleReportRequestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLifecycleReportRequestRequest)

	if err != nil {
		return err
	}

	*o = LifecycleReportRequestRequest(varLifecycleReportRequestRequest)

	return err
}

type NullableLifecycleReportRequestRequest struct {
	value *LifecycleReportRequestRequest
	isSet bool
}

func (v NullableLifecycleReportRequestRequest) Get() *LifecycleReportRequestRequest {
	return v.value
}

func (v *NullableLifecycleReportRequestRequest) Set(val *LifecycleReportRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleReportRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleReportRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleReportRequestRequest(val *LifecycleReportRequestRequest) *NullableLifecycleReportRequestRequest {
	return &NullableLifecycleReportRequestRequest{value: val, isSet: true}
}

func (v NullableLifecycleReportRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleReportRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
