/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleAlertSeverityEnum * `info` - Info * `warning` - Warning * `critical` - Critical
type LifecycleAlertSeverityEnum string

// List of LifecycleAlertSeverityEnum
const (
	LIFECYCLEALERTSEVERITYENUM_INFO     LifecycleAlertSeverityEnum = "info"
	LIFECYCLEALERTSEVERITYENUM_WARNING  LifecycleAlertSeverityEnum = "warning"
	LIFECYCLEALERTSEVERITYENUM_CRITICAL LifecycleAlertSeverityEnum = "critical"
)

// All allowed values of LifecycleAlertSeverityEnum enum
var AllowedLifecycleAlertSeverityEnumEnumValues = []LifecycleAlertSeverityEnum{
	"info",
	"warning",
	"critical",
}

func (v *LifecycleAlertSeverityEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleAlertSeverityEnum(value)
	for _, existing := range AllowedLifecycleAlertSeverityEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleAlertSeverityEnum", value)
}

// NewLifecycleAlertSeverityEnumFromValue returns a pointer to a valid LifecycleAlertSeverityEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleAlertSeverityEnumFromValue(v string) (*LifecycleAlertSeverityEnum, error) {
	ev := LifecycleAlertSeverityEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleAlertSeverityEnum: valid values are %v", v, AllowedLifecycleAlertSeverityEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleAlertSeverityEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleAlertSeverityEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleAlertSeverityEnum value
func (v LifecycleAlertSeverityEnum) Ptr() *LifecycleAlertSeverityEnum {
	return &v
}

type NullableLifecycleAlertSeverityEnum struct {
	value *LifecycleAlertSeverityEnum
	isSet bool
}

func (v NullableLifecycleAlertSeverityEnum) Get() *LifecycleAlertSeverityEnum {
	return v.value
}

func (v *NullableLifecycleAlertSeverityEnum) Set(val *LifecycleAlertSeverityEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleAlertSeverityEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleAlertSeverityEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleAlertSeverityEnum(val *LifecycleAlertSeverityEnum) *NullableLifecycleAlertSeverityEnum {
	return &NullableLifecycleAlertSeverityEnum{value: val, isSet: true}
}

func (v NullableLifecycleAlertSeverityEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleAlertSeverityEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
