/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the LifecycleDashboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecycleDashboard{}

// LifecycleDashboard struct for LifecycleDashboard
type LifecycleDashboard struct {
	OrganizationId string                    `json:"organization_id"`
	GeneratedAt    time.Time                 `json:"generated_at"`
	Policies       LifecyclePolicySummary    `json:"policies"`
	LegalHolds     LifecycleLegalHoldSummary `json:"legal_holds"`
	Executions     LifecycleExecutionSummary `json:"executions"`
	Backlog        LifecycleBacklogSummary   `json:"backlog"`
	Evidence       LifecycleEvidenceSummary  `json:"evidence"`
	SloIndicators  []LifecycleSLOIndicator   `json:"slo_indicators"`
}

type _LifecycleDashboard LifecycleDashboard

// NewLifecycleDashboard instantiates a new LifecycleDashboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecycleDashboard(organizationId string, generatedAt time.Time, policies LifecyclePolicySummary, legalHolds LifecycleLegalHoldSummary, executions LifecycleExecutionSummary, backlog LifecycleBacklogSummary, evidence LifecycleEvidenceSummary, sloIndicators []LifecycleSLOIndicator) *LifecycleDashboard {
	this := LifecycleDashboard{}
	this.OrganizationId = organizationId
	this.GeneratedAt = generatedAt
	this.Policies = policies
	this.LegalHolds = legalHolds
	this.Executions = executions
	this.Backlog = backlog
	this.Evidence = evidence
	this.SloIndicators = sloIndicators
	return &this
}

// NewLifecycleDashboardWithDefaults instantiates a new LifecycleDashboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecycleDashboardWithDefaults() *LifecycleDashboard {
	this := LifecycleDashboard{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *LifecycleDashboard) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *LifecycleDashboard) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *LifecycleDashboard) GetGeneratedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *LifecycleDashboard) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = v
}

// GetPolicies returns the Policies field value
func (o *LifecycleDashboard) GetPolicies() LifecyclePolicySummary {
	if o == nil {
		var ret LifecyclePolicySummary
		return ret
	}

	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetPoliciesOk() (*LifecyclePolicySummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policies, true
}

// SetPolicies sets field value
func (o *LifecycleDashboard) SetPolicies(v LifecyclePolicySummary) {
	o.Policies = v
}

// GetLegalHolds returns the LegalHolds field value
func (o *LifecycleDashboard) GetLegalHolds() LifecycleLegalHoldSummary {
	if o == nil {
		var ret LifecycleLegalHoldSummary
		return ret
	}

	return o.LegalHolds
}

// GetLegalHoldsOk returns a tuple with the LegalHolds field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetLegalHoldsOk() (*LifecycleLegalHoldSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegalHolds, true
}

// SetLegalHolds sets field value
func (o *LifecycleDashboard) SetLegalHolds(v LifecycleLegalHoldSummary) {
	o.LegalHolds = v
}

// GetExecutions returns the Executions field value
func (o *LifecycleDashboard) GetExecutions() LifecycleExecutionSummary {
	if o == nil {
		var ret LifecycleExecutionSummary
		return ret
	}

	return o.Executions
}

// GetExecutionsOk returns a tuple with the Executions field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetExecutionsOk() (*LifecycleExecutionSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Executions, true
}

// SetExecutions sets field value
func (o *LifecycleDashboard) SetExecutions(v LifecycleExecutionSummary) {
	o.Executions = v
}

// GetBacklog returns the Backlog field value
func (o *LifecycleDashboard) GetBacklog() LifecycleBacklogSummary {
	if o == nil {
		var ret LifecycleBacklogSummary
		return ret
	}

	return o.Backlog
}

// GetBacklogOk returns a tuple with the Backlog field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetBacklogOk() (*LifecycleBacklogSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backlog, true
}

// SetBacklog sets field value
func (o *LifecycleDashboard) SetBacklog(v LifecycleBacklogSummary) {
	o.Backlog = v
}

// GetEvidence returns the Evidence field value
func (o *LifecycleDashboard) GetEvidence() LifecycleEvidenceSummary {
	if o == nil {
		var ret LifecycleEvidenceSummary
		return ret
	}

	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetEvidenceOk() (*LifecycleEvidenceSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Evidence, true
}

// SetEvidence sets field value
func (o *LifecycleDashboard) SetEvidence(v LifecycleEvidenceSummary) {
	o.Evidence = v
}

// GetSloIndicators returns the SloIndicators field value
func (o *LifecycleDashboard) GetSloIndicators() []LifecycleSLOIndicator {
	if o == nil {
		var ret []LifecycleSLOIndicator
		return ret
	}

	return o.SloIndicators
}

// GetSloIndicatorsOk returns a tuple with the SloIndicators field value
// and a boolean to check if the value has been set.
func (o *LifecycleDashboard) GetSloIndicatorsOk() ([]LifecycleSLOIndicator, bool) {
	if o == nil {
		return nil, false
	}
	return o.SloIndicators, true
}

// SetSloIndicators sets field value
func (o *LifecycleDashboard) SetSloIndicators(v []LifecycleSLOIndicator) {
	o.SloIndicators = v
}

func (o LifecycleDashboard) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecycleDashboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["generated_at"] = o.GeneratedAt
	toSerialize["policies"] = o.Policies
	toSerialize["legal_holds"] = o.LegalHolds
	toSerialize["executions"] = o.Executions
	toSerialize["backlog"] = o.Backlog
	toSerialize["evidence"] = o.Evidence
	toSerialize["slo_indicators"] = o.SloIndicators
	return toSerialize, nil
}

func (o *LifecycleDashboard) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization_id",
		"generated_at",
		"policies",
		"legal_holds",
		"executions",
		"backlog",
		"evidence",
		"slo_indicators",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLifecycleDashboard := _LifecycleDashboard{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLifecycleDashboard)

	if err != nil {
		return err
	}

	*o = LifecycleDashboard(varLifecycleDashboard)

	return err
}

type NullableLifecycleDashboard struct {
	value *LifecycleDashboard
	isSet bool
}

func (v NullableLifecycleDashboard) Get() *LifecycleDashboard {
	return v.value
}

func (v *NullableLifecycleDashboard) Set(val *LifecycleDashboard) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleDashboard) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleDashboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleDashboard(val *LifecycleDashboard) *NullableLifecycleDashboard {
	return &NullableLifecycleDashboard{value: val, isSet: true}
}

func (v NullableLifecycleDashboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleDashboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
