/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SaaSOperatorReservationRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SaaSOperatorReservationRecord{}

// SaaSOperatorReservationRecord struct for SaaSOperatorReservationRecord
type SaaSOperatorReservationRecord struct {
	ReservationId     string    `json:"reservation_id"`
	OrganizationId    string    `json:"organization_id"`
	QuotaCode         string    `json:"quota_code"`
	Status            string    `json:"status"`
	RequestedQuantity string    `json:"requested_quantity" validate:"regexp=^-?\\\\d{0,27}(?:\\\\.\\\\d{0,9})?$"`
	CommittedQuantity string    `json:"committed_quantity" validate:"regexp=^-?\\\\d{0,27}(?:\\\\.\\\\d{0,9})?$"`
	ReleasedQuantity  string    `json:"released_quantity" validate:"regexp=^-?\\\\d{0,27}(?:\\\\.\\\\d{0,9})?$"`
	RemainingQuantity string    `json:"remaining_quantity" validate:"regexp=^-?\\\\d{0,27}(?:\\\\.\\\\d{0,9})?$"`
	LeaseExpiresAt    time.Time `json:"lease_expires_at"`
	ReservedAt        time.Time `json:"reserved_at"`
	Revision          int32     `json:"revision"`
}

type _SaaSOperatorReservationRecord SaaSOperatorReservationRecord

// NewSaaSOperatorReservationRecord instantiates a new SaaSOperatorReservationRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSaaSOperatorReservationRecord(reservationId string, organizationId string, quotaCode string, status string, requestedQuantity string, committedQuantity string, releasedQuantity string, remainingQuantity string, leaseExpiresAt time.Time, reservedAt time.Time, revision int32) *SaaSOperatorReservationRecord {
	this := SaaSOperatorReservationRecord{}
	this.ReservationId = reservationId
	this.OrganizationId = organizationId
	this.QuotaCode = quotaCode
	this.Status = status
	this.RequestedQuantity = requestedQuantity
	this.CommittedQuantity = committedQuantity
	this.ReleasedQuantity = releasedQuantity
	this.RemainingQuantity = remainingQuantity
	this.LeaseExpiresAt = leaseExpiresAt
	this.ReservedAt = reservedAt
	this.Revision = revision
	return &this
}

// NewSaaSOperatorReservationRecordWithDefaults instantiates a new SaaSOperatorReservationRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaaSOperatorReservationRecordWithDefaults() *SaaSOperatorReservationRecord {
	this := SaaSOperatorReservationRecord{}
	return &this
}

// GetReservationId returns the ReservationId field value
func (o *SaaSOperatorReservationRecord) GetReservationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReservationId
}

// GetReservationIdOk returns a tuple with the ReservationId field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetReservationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservationId, true
}

// SetReservationId sets field value
func (o *SaaSOperatorReservationRecord) SetReservationId(v string) {
	o.ReservationId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *SaaSOperatorReservationRecord) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *SaaSOperatorReservationRecord) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetQuotaCode returns the QuotaCode field value
func (o *SaaSOperatorReservationRecord) GetQuotaCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuotaCode
}

// GetQuotaCodeOk returns a tuple with the QuotaCode field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetQuotaCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaCode, true
}

// SetQuotaCode sets field value
func (o *SaaSOperatorReservationRecord) SetQuotaCode(v string) {
	o.QuotaCode = v
}

// GetStatus returns the Status field value
func (o *SaaSOperatorReservationRecord) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SaaSOperatorReservationRecord) SetStatus(v string) {
	o.Status = v
}

// GetRequestedQuantity returns the RequestedQuantity field value
func (o *SaaSOperatorReservationRecord) GetRequestedQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedQuantity
}

// GetRequestedQuantityOk returns a tuple with the RequestedQuantity field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetRequestedQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedQuantity, true
}

// SetRequestedQuantity sets field value
func (o *SaaSOperatorReservationRecord) SetRequestedQuantity(v string) {
	o.RequestedQuantity = v
}

// GetCommittedQuantity returns the CommittedQuantity field value
func (o *SaaSOperatorReservationRecord) GetCommittedQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommittedQuantity
}

// GetCommittedQuantityOk returns a tuple with the CommittedQuantity field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetCommittedQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommittedQuantity, true
}

// SetCommittedQuantity sets field value
func (o *SaaSOperatorReservationRecord) SetCommittedQuantity(v string) {
	o.CommittedQuantity = v
}

// GetReleasedQuantity returns the ReleasedQuantity field value
func (o *SaaSOperatorReservationRecord) GetReleasedQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleasedQuantity
}

// GetReleasedQuantityOk returns a tuple with the ReleasedQuantity field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetReleasedQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleasedQuantity, true
}

// SetReleasedQuantity sets field value
func (o *SaaSOperatorReservationRecord) SetReleasedQuantity(v string) {
	o.ReleasedQuantity = v
}

// GetRemainingQuantity returns the RemainingQuantity field value
func (o *SaaSOperatorReservationRecord) GetRemainingQuantity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemainingQuantity
}

// GetRemainingQuantityOk returns a tuple with the RemainingQuantity field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetRemainingQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemainingQuantity, true
}

// SetRemainingQuantity sets field value
func (o *SaaSOperatorReservationRecord) SetRemainingQuantity(v string) {
	o.RemainingQuantity = v
}

// GetLeaseExpiresAt returns the LeaseExpiresAt field value
func (o *SaaSOperatorReservationRecord) GetLeaseExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LeaseExpiresAt
}

// GetLeaseExpiresAtOk returns a tuple with the LeaseExpiresAt field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetLeaseExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseExpiresAt, true
}

// SetLeaseExpiresAt sets field value
func (o *SaaSOperatorReservationRecord) SetLeaseExpiresAt(v time.Time) {
	o.LeaseExpiresAt = v
}

// GetReservedAt returns the ReservedAt field value
func (o *SaaSOperatorReservationRecord) GetReservedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReservedAt
}

// GetReservedAtOk returns a tuple with the ReservedAt field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetReservedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedAt, true
}

// SetReservedAt sets field value
func (o *SaaSOperatorReservationRecord) SetReservedAt(v time.Time) {
	o.ReservedAt = v
}

// GetRevision returns the Revision field value
func (o *SaaSOperatorReservationRecord) GetRevision() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *SaaSOperatorReservationRecord) GetRevisionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *SaaSOperatorReservationRecord) SetRevision(v int32) {
	o.Revision = v
}

func (o SaaSOperatorReservationRecord) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SaaSOperatorReservationRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reservation_id"] = o.ReservationId
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["quota_code"] = o.QuotaCode
	toSerialize["status"] = o.Status
	toSerialize["requested_quantity"] = o.RequestedQuantity
	toSerialize["committed_quantity"] = o.CommittedQuantity
	toSerialize["released_quantity"] = o.ReleasedQuantity
	toSerialize["remaining_quantity"] = o.RemainingQuantity
	toSerialize["lease_expires_at"] = o.LeaseExpiresAt
	toSerialize["reserved_at"] = o.ReservedAt
	toSerialize["revision"] = o.Revision
	return toSerialize, nil
}

func (o *SaaSOperatorReservationRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reservation_id",
		"organization_id",
		"quota_code",
		"status",
		"requested_quantity",
		"committed_quantity",
		"released_quantity",
		"remaining_quantity",
		"lease_expires_at",
		"reserved_at",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSaaSOperatorReservationRecord := _SaaSOperatorReservationRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSaaSOperatorReservationRecord)

	if err != nil {
		return err
	}

	*o = SaaSOperatorReservationRecord(varSaaSOperatorReservationRecord)

	return err
}

type NullableSaaSOperatorReservationRecord struct {
	value *SaaSOperatorReservationRecord
	isSet bool
}

func (v NullableSaaSOperatorReservationRecord) Get() *SaaSOperatorReservationRecord {
	return v.value
}

func (v *NullableSaaSOperatorReservationRecord) Set(val *SaaSOperatorReservationRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSaaSOperatorReservationRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSaaSOperatorReservationRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaaSOperatorReservationRecord(val *SaaSOperatorReservationRecord) *NullableSaaSOperatorReservationRecord {
	return &NullableSaaSOperatorReservationRecord{value: val, isSet: true}
}

func (v NullableSaaSOperatorReservationRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaaSOperatorReservationRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
