/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// DeadLetterActionActionEnum * `retry-approved` - retry-approved * `dismissed` - dismissed * `investigating` - investigating * `resolved` - resolved
type DeadLetterActionActionEnum string

// List of DeadLetterActionActionEnum
const (
	DEADLETTERACTIONACTIONENUM_RETRY_APPROVED DeadLetterActionActionEnum = "retry-approved"
	DEADLETTERACTIONACTIONENUM_DISMISSED      DeadLetterActionActionEnum = "dismissed"
	DEADLETTERACTIONACTIONENUM_INVESTIGATING  DeadLetterActionActionEnum = "investigating"
	DEADLETTERACTIONACTIONENUM_RESOLVED       DeadLetterActionActionEnum = "resolved"
)

// All allowed values of DeadLetterActionActionEnum enum
var AllowedDeadLetterActionActionEnumEnumValues = []DeadLetterActionActionEnum{
	"retry-approved",
	"dismissed",
	"investigating",
	"resolved",
}

func (v *DeadLetterActionActionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeadLetterActionActionEnum(value)
	for _, existing := range AllowedDeadLetterActionActionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeadLetterActionActionEnum", value)
}

// NewDeadLetterActionActionEnumFromValue returns a pointer to a valid DeadLetterActionActionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeadLetterActionActionEnumFromValue(v string) (*DeadLetterActionActionEnum, error) {
	ev := DeadLetterActionActionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeadLetterActionActionEnum: valid values are %v", v, AllowedDeadLetterActionActionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeadLetterActionActionEnum) IsValid() bool {
	for _, existing := range AllowedDeadLetterActionActionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DeadLetterActionActionEnum value
func (v DeadLetterActionActionEnum) Ptr() *DeadLetterActionActionEnum {
	return &v
}

type NullableDeadLetterActionActionEnum struct {
	value *DeadLetterActionActionEnum
	isSet bool
}

func (v NullableDeadLetterActionActionEnum) Get() *DeadLetterActionActionEnum {
	return v.value
}

func (v *NullableDeadLetterActionActionEnum) Set(val *DeadLetterActionActionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableDeadLetterActionActionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableDeadLetterActionActionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeadLetterActionActionEnum(val *DeadLetterActionActionEnum) *NullableDeadLetterActionActionEnum {
	return &NullableDeadLetterActionActionEnum{value: val, isSet: true}
}

func (v NullableDeadLetterActionActionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeadLetterActionActionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
