/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
)

// checks if the PatchedRetentionPolicyWriteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedRetentionPolicyWriteRequest{}

// PatchedRetentionPolicyWriteRequest Tenant-facing retention policy input.  organization_id is never accepted from the request. It is always supplied by the trusted tenant context.
type PatchedRetentionPolicyWriteRequest struct {
	Name             *string                        `json:"name,omitempty"`
	Description      *string                        `json:"description,omitempty"`
	Scope            *RetentionPolicyWriteScopeEnum `json:"scope,omitempty"`
	EventTypeId      NullableString                 `json:"event_type_id,omitempty"`
	Source           *string                        `json:"source,omitempty"`
	ArchiveAfterDays NullableInt32                  `json:"archive_after_days,omitempty"`
	DeleteAfterDays  NullableInt32                  `json:"delete_after_days,omitempty"`
	RetainForever    *bool                          `json:"retain_forever,omitempty"`
	IsEnabled        *bool                          `json:"is_enabled,omitempty"`
}

// NewPatchedRetentionPolicyWriteRequest instantiates a new PatchedRetentionPolicyWriteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedRetentionPolicyWriteRequest() *PatchedRetentionPolicyWriteRequest {
	this := PatchedRetentionPolicyWriteRequest{}
	var description string = ""
	this.Description = &description
	var source string = ""
	this.Source = &source
	var retainForever bool = false
	this.RetainForever = &retainForever
	var isEnabled bool = true
	this.IsEnabled = &isEnabled
	return &this
}

// NewPatchedRetentionPolicyWriteRequestWithDefaults instantiates a new PatchedRetentionPolicyWriteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedRetentionPolicyWriteRequestWithDefaults() *PatchedRetentionPolicyWriteRequest {
	this := PatchedRetentionPolicyWriteRequest{}
	var description string = ""
	this.Description = &description
	var source string = ""
	this.Source = &source
	var retainForever bool = false
	this.RetainForever = &retainForever
	var isEnabled bool = true
	this.IsEnabled = &isEnabled
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedRetentionPolicyWriteRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedRetentionPolicyWriteRequest) SetDescription(v string) {
	o.Description = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetScope() RetentionPolicyWriteScopeEnum {
	if o == nil || IsNil(o.Scope) {
		var ret RetentionPolicyWriteScopeEnum
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetScopeOk() (*RetentionPolicyWriteScopeEnum, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given RetentionPolicyWriteScopeEnum and assigns it to the Scope field.
func (o *PatchedRetentionPolicyWriteRequest) SetScope(v RetentionPolicyWriteScopeEnum) {
	o.Scope = &v
}

// GetEventTypeId returns the EventTypeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedRetentionPolicyWriteRequest) GetEventTypeId() string {
	if o == nil || IsNil(o.EventTypeId.Get()) {
		var ret string
		return ret
	}
	return *o.EventTypeId.Get()
}

// GetEventTypeIdOk returns a tuple with the EventTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedRetentionPolicyWriteRequest) GetEventTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypeId.Get(), o.EventTypeId.IsSet()
}

// HasEventTypeId returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasEventTypeId() bool {
	if o != nil && o.EventTypeId.IsSet() {
		return true
	}

	return false
}

// SetEventTypeId gets a reference to the given NullableString and assigns it to the EventTypeId field.
func (o *PatchedRetentionPolicyWriteRequest) SetEventTypeId(v string) {
	o.EventTypeId.Set(&v)
}

// SetEventTypeIdNil sets the value for EventTypeId to be an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) SetEventTypeIdNil() {
	o.EventTypeId.Set(nil)
}

// UnsetEventTypeId ensures that no value is present for EventTypeId, not even an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) UnsetEventTypeId() {
	o.EventTypeId.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *PatchedRetentionPolicyWriteRequest) SetSource(v string) {
	o.Source = &v
}

// GetArchiveAfterDays returns the ArchiveAfterDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedRetentionPolicyWriteRequest) GetArchiveAfterDays() int32 {
	if o == nil || IsNil(o.ArchiveAfterDays.Get()) {
		var ret int32
		return ret
	}
	return *o.ArchiveAfterDays.Get()
}

// GetArchiveAfterDaysOk returns a tuple with the ArchiveAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedRetentionPolicyWriteRequest) GetArchiveAfterDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchiveAfterDays.Get(), o.ArchiveAfterDays.IsSet()
}

// HasArchiveAfterDays returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasArchiveAfterDays() bool {
	if o != nil && o.ArchiveAfterDays.IsSet() {
		return true
	}

	return false
}

// SetArchiveAfterDays gets a reference to the given NullableInt32 and assigns it to the ArchiveAfterDays field.
func (o *PatchedRetentionPolicyWriteRequest) SetArchiveAfterDays(v int32) {
	o.ArchiveAfterDays.Set(&v)
}

// SetArchiveAfterDaysNil sets the value for ArchiveAfterDays to be an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) SetArchiveAfterDaysNil() {
	o.ArchiveAfterDays.Set(nil)
}

// UnsetArchiveAfterDays ensures that no value is present for ArchiveAfterDays, not even an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) UnsetArchiveAfterDays() {
	o.ArchiveAfterDays.Unset()
}

// GetDeleteAfterDays returns the DeleteAfterDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedRetentionPolicyWriteRequest) GetDeleteAfterDays() int32 {
	if o == nil || IsNil(o.DeleteAfterDays.Get()) {
		var ret int32
		return ret
	}
	return *o.DeleteAfterDays.Get()
}

// GetDeleteAfterDaysOk returns a tuple with the DeleteAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedRetentionPolicyWriteRequest) GetDeleteAfterDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeleteAfterDays.Get(), o.DeleteAfterDays.IsSet()
}

// HasDeleteAfterDays returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasDeleteAfterDays() bool {
	if o != nil && o.DeleteAfterDays.IsSet() {
		return true
	}

	return false
}

// SetDeleteAfterDays gets a reference to the given NullableInt32 and assigns it to the DeleteAfterDays field.
func (o *PatchedRetentionPolicyWriteRequest) SetDeleteAfterDays(v int32) {
	o.DeleteAfterDays.Set(&v)
}

// SetDeleteAfterDaysNil sets the value for DeleteAfterDays to be an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) SetDeleteAfterDaysNil() {
	o.DeleteAfterDays.Set(nil)
}

// UnsetDeleteAfterDays ensures that no value is present for DeleteAfterDays, not even an explicit nil
func (o *PatchedRetentionPolicyWriteRequest) UnsetDeleteAfterDays() {
	o.DeleteAfterDays.Unset()
}

// GetRetainForever returns the RetainForever field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetRetainForever() bool {
	if o == nil || IsNil(o.RetainForever) {
		var ret bool
		return ret
	}
	return *o.RetainForever
}

// GetRetainForeverOk returns a tuple with the RetainForever field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetRetainForeverOk() (*bool, bool) {
	if o == nil || IsNil(o.RetainForever) {
		return nil, false
	}
	return o.RetainForever, true
}

// HasRetainForever returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasRetainForever() bool {
	if o != nil && !IsNil(o.RetainForever) {
		return true
	}

	return false
}

// SetRetainForever gets a reference to the given bool and assigns it to the RetainForever field.
func (o *PatchedRetentionPolicyWriteRequest) SetRetainForever(v bool) {
	o.RetainForever = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *PatchedRetentionPolicyWriteRequest) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedRetentionPolicyWriteRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *PatchedRetentionPolicyWriteRequest) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *PatchedRetentionPolicyWriteRequest) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

func (o PatchedRetentionPolicyWriteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedRetentionPolicyWriteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if o.EventTypeId.IsSet() {
		toSerialize["event_type_id"] = o.EventTypeId.Get()
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if o.ArchiveAfterDays.IsSet() {
		toSerialize["archive_after_days"] = o.ArchiveAfterDays.Get()
	}
	if o.DeleteAfterDays.IsSet() {
		toSerialize["delete_after_days"] = o.DeleteAfterDays.Get()
	}
	if !IsNil(o.RetainForever) {
		toSerialize["retain_forever"] = o.RetainForever
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	return toSerialize, nil
}

type NullablePatchedRetentionPolicyWriteRequest struct {
	value *PatchedRetentionPolicyWriteRequest
	isSet bool
}

func (v NullablePatchedRetentionPolicyWriteRequest) Get() *PatchedRetentionPolicyWriteRequest {
	return v.value
}

func (v *NullablePatchedRetentionPolicyWriteRequest) Set(val *PatchedRetentionPolicyWriteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedRetentionPolicyWriteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedRetentionPolicyWriteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedRetentionPolicyWriteRequest(val *PatchedRetentionPolicyWriteRequest) *NullablePatchedRetentionPolicyWriteRequest {
	return &NullablePatchedRetentionPolicyWriteRequest{value: val, isSet: true}
}

func (v NullablePatchedRetentionPolicyWriteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedRetentionPolicyWriteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
