/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// OutcomeEnum * `completed` - completed * `dispatched` - dispatched
type OutcomeEnum string

// List of OutcomeEnum
const (
	OUTCOMEENUM_COMPLETED  OutcomeEnum = "completed"
	OUTCOMEENUM_DISPATCHED OutcomeEnum = "dispatched"
)

// All allowed values of OutcomeEnum enum
var AllowedOutcomeEnumEnumValues = []OutcomeEnum{
	"completed",
	"dispatched",
}

func (v *OutcomeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OutcomeEnum(value)
	for _, existing := range AllowedOutcomeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OutcomeEnum", value)
}

// NewOutcomeEnumFromValue returns a pointer to a valid OutcomeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOutcomeEnumFromValue(v string) (*OutcomeEnum, error) {
	ev := OutcomeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OutcomeEnum: valid values are %v", v, AllowedOutcomeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OutcomeEnum) IsValid() bool {
	for _, existing := range AllowedOutcomeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OutcomeEnum value
func (v OutcomeEnum) Ptr() *OutcomeEnum {
	return &v
}

type NullableOutcomeEnum struct {
	value *OutcomeEnum
	isSet bool
}

func (v NullableOutcomeEnum) Get() *OutcomeEnum {
	return v.value
}

func (v *NullableOutcomeEnum) Set(val *OutcomeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableOutcomeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableOutcomeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutcomeEnum(val *OutcomeEnum) *NullableOutcomeEnum {
	return &NullableOutcomeEnum{value: val, isSet: true}
}

func (v NullableOutcomeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutcomeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
