/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// NotificationStatusEnum * `pending` - Pending * `published` - Published * `failed` - Failed * `closed` - Closed
type NotificationStatusEnum string

// List of NotificationStatusEnum
const (
	NOTIFICATIONSTATUSENUM_PENDING   NotificationStatusEnum = "pending"
	NOTIFICATIONSTATUSENUM_PUBLISHED NotificationStatusEnum = "published"
	NOTIFICATIONSTATUSENUM_FAILED    NotificationStatusEnum = "failed"
	NOTIFICATIONSTATUSENUM_CLOSED    NotificationStatusEnum = "closed"
)

// All allowed values of NotificationStatusEnum enum
var AllowedNotificationStatusEnumEnumValues = []NotificationStatusEnum{
	"pending",
	"published",
	"failed",
	"closed",
}

func (v *NotificationStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationStatusEnum(value)
	for _, existing := range AllowedNotificationStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationStatusEnum", value)
}

// NewNotificationStatusEnumFromValue returns a pointer to a valid NotificationStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationStatusEnumFromValue(v string) (*NotificationStatusEnum, error) {
	ev := NotificationStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationStatusEnum: valid values are %v", v, AllowedNotificationStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationStatusEnum) IsValid() bool {
	for _, existing := range AllowedNotificationStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NotificationStatusEnum value
func (v NotificationStatusEnum) Ptr() *NotificationStatusEnum {
	return &v
}

type NullableNotificationStatusEnum struct {
	value *NotificationStatusEnum
	isSet bool
}

func (v NullableNotificationStatusEnum) Get() *NotificationStatusEnum {
	return v.value
}

func (v *NullableNotificationStatusEnum) Set(val *NotificationStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationStatusEnum(val *NotificationStatusEnum) *NullableNotificationStatusEnum {
	return &NullableNotificationStatusEnum{value: val, isSet: true}
}

func (v NullableNotificationStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
