/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OperatorConsumerSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorConsumerSummary{}

// OperatorConsumerSummary struct for OperatorConsumerSummary
type OperatorConsumerSummary struct {
	Total           int32                             `json:"total"`
	Counts          map[string]int32                  `json:"counts"`
	EnabledBindings int32                             `json:"enabled_bindings"`
	Deliveries      OperatorConsumerDeliverySummary   `json:"deliveries"`
	RecentFailures  []OperatorConsumerDeliveryFailure `json:"recent_failures"`
}

type _OperatorConsumerSummary OperatorConsumerSummary

// NewOperatorConsumerSummary instantiates a new OperatorConsumerSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorConsumerSummary(total int32, counts map[string]int32, enabledBindings int32, deliveries OperatorConsumerDeliverySummary, recentFailures []OperatorConsumerDeliveryFailure) *OperatorConsumerSummary {
	this := OperatorConsumerSummary{}
	this.Total = total
	this.Counts = counts
	this.EnabledBindings = enabledBindings
	this.Deliveries = deliveries
	this.RecentFailures = recentFailures
	return &this
}

// NewOperatorConsumerSummaryWithDefaults instantiates a new OperatorConsumerSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorConsumerSummaryWithDefaults() *OperatorConsumerSummary {
	this := OperatorConsumerSummary{}
	return &this
}

// GetTotal returns the Total field value
func (o *OperatorConsumerSummary) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *OperatorConsumerSummary) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *OperatorConsumerSummary) SetTotal(v int32) {
	o.Total = v
}

// GetCounts returns the Counts field value
func (o *OperatorConsumerSummary) GetCounts() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.Counts
}

// GetCountsOk returns a tuple with the Counts field value
// and a boolean to check if the value has been set.
func (o *OperatorConsumerSummary) GetCountsOk() (*map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Counts, true
}

// SetCounts sets field value
func (o *OperatorConsumerSummary) SetCounts(v map[string]int32) {
	o.Counts = v
}

// GetEnabledBindings returns the EnabledBindings field value
func (o *OperatorConsumerSummary) GetEnabledBindings() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EnabledBindings
}

// GetEnabledBindingsOk returns a tuple with the EnabledBindings field value
// and a boolean to check if the value has been set.
func (o *OperatorConsumerSummary) GetEnabledBindingsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnabledBindings, true
}

// SetEnabledBindings sets field value
func (o *OperatorConsumerSummary) SetEnabledBindings(v int32) {
	o.EnabledBindings = v
}

// GetDeliveries returns the Deliveries field value
func (o *OperatorConsumerSummary) GetDeliveries() OperatorConsumerDeliverySummary {
	if o == nil {
		var ret OperatorConsumerDeliverySummary
		return ret
	}

	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value
// and a boolean to check if the value has been set.
func (o *OperatorConsumerSummary) GetDeliveriesOk() (*OperatorConsumerDeliverySummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deliveries, true
}

// SetDeliveries sets field value
func (o *OperatorConsumerSummary) SetDeliveries(v OperatorConsumerDeliverySummary) {
	o.Deliveries = v
}

// GetRecentFailures returns the RecentFailures field value
func (o *OperatorConsumerSummary) GetRecentFailures() []OperatorConsumerDeliveryFailure {
	if o == nil {
		var ret []OperatorConsumerDeliveryFailure
		return ret
	}

	return o.RecentFailures
}

// GetRecentFailuresOk returns a tuple with the RecentFailures field value
// and a boolean to check if the value has been set.
func (o *OperatorConsumerSummary) GetRecentFailuresOk() ([]OperatorConsumerDeliveryFailure, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecentFailures, true
}

// SetRecentFailures sets field value
func (o *OperatorConsumerSummary) SetRecentFailures(v []OperatorConsumerDeliveryFailure) {
	o.RecentFailures = v
}

func (o OperatorConsumerSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorConsumerSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["counts"] = o.Counts
	toSerialize["enabled_bindings"] = o.EnabledBindings
	toSerialize["deliveries"] = o.Deliveries
	toSerialize["recent_failures"] = o.RecentFailures
	return toSerialize, nil
}

func (o *OperatorConsumerSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"counts",
		"enabled_bindings",
		"deliveries",
		"recent_failures",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorConsumerSummary := _OperatorConsumerSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorConsumerSummary)

	if err != nil {
		return err
	}

	*o = OperatorConsumerSummary(varOperatorConsumerSummary)

	return err
}

type NullableOperatorConsumerSummary struct {
	value *OperatorConsumerSummary
	isSet bool
}

func (v NullableOperatorConsumerSummary) Get() *OperatorConsumerSummary {
	return v.value
}

func (v *NullableOperatorConsumerSummary) Set(val *OperatorConsumerSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorConsumerSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorConsumerSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorConsumerSummary(val *OperatorConsumerSummary) *NullableOperatorConsumerSummary {
	return &NullableOperatorConsumerSummary{value: val, isSet: true}
}

func (v NullableOperatorConsumerSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorConsumerSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
