/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleBatchStatusEnum * `pending` - Pending * `leased` - Leased * `running` - Running * `acknowledged` - Acknowledged * `completed` - Completed * `partial` - Partial * `failed` - Failed * `cancelled` - Cancelled
type LifecycleBatchStatusEnum string

// List of LifecycleBatchStatusEnum
const (
	LIFECYCLEBATCHSTATUSENUM_PENDING      LifecycleBatchStatusEnum = "pending"
	LIFECYCLEBATCHSTATUSENUM_LEASED       LifecycleBatchStatusEnum = "leased"
	LIFECYCLEBATCHSTATUSENUM_RUNNING      LifecycleBatchStatusEnum = "running"
	LIFECYCLEBATCHSTATUSENUM_ACKNOWLEDGED LifecycleBatchStatusEnum = "acknowledged"
	LIFECYCLEBATCHSTATUSENUM_COMPLETED    LifecycleBatchStatusEnum = "completed"
	LIFECYCLEBATCHSTATUSENUM_PARTIAL      LifecycleBatchStatusEnum = "partial"
	LIFECYCLEBATCHSTATUSENUM_FAILED       LifecycleBatchStatusEnum = "failed"
	LIFECYCLEBATCHSTATUSENUM_CANCELLED    LifecycleBatchStatusEnum = "cancelled"
)

// All allowed values of LifecycleBatchStatusEnum enum
var AllowedLifecycleBatchStatusEnumEnumValues = []LifecycleBatchStatusEnum{
	"pending",
	"leased",
	"running",
	"acknowledged",
	"completed",
	"partial",
	"failed",
	"cancelled",
}

func (v *LifecycleBatchStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleBatchStatusEnum(value)
	for _, existing := range AllowedLifecycleBatchStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleBatchStatusEnum", value)
}

// NewLifecycleBatchStatusEnumFromValue returns a pointer to a valid LifecycleBatchStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleBatchStatusEnumFromValue(v string) (*LifecycleBatchStatusEnum, error) {
	ev := LifecycleBatchStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleBatchStatusEnum: valid values are %v", v, AllowedLifecycleBatchStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleBatchStatusEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleBatchStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleBatchStatusEnum value
func (v LifecycleBatchStatusEnum) Ptr() *LifecycleBatchStatusEnum {
	return &v
}

type NullableLifecycleBatchStatusEnum struct {
	value *LifecycleBatchStatusEnum
	isSet bool
}

func (v NullableLifecycleBatchStatusEnum) Get() *LifecycleBatchStatusEnum {
	return v.value
}

func (v *NullableLifecycleBatchStatusEnum) Set(val *LifecycleBatchStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleBatchStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleBatchStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleBatchStatusEnum(val *LifecycleBatchStatusEnum) *NullableLifecycleBatchStatusEnum {
	return &NullableLifecycleBatchStatusEnum{value: val, isSet: true}
}

func (v NullableLifecycleBatchStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleBatchStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
