/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OperatorRuntimeMetricsAggregate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeMetricsAggregate{}

// OperatorRuntimeMetricsAggregate struct for OperatorRuntimeMetricsAggregate
type OperatorRuntimeMetricsAggregate struct {
	OrganizationId NullableString                        `json:"organization_id"`
	CapturedAt     time.Time                             `json:"captured_at"`
	Consumers      OperatorRuntimeMetricsConsumerSummary `json:"consumers"`
	Assignment     OperatorRuntimeMetricsAssignment      `json:"assignment"`
	Workers        OperatorRuntimeMetricsWorkers         `json:"workers"`
	Supervisors    OperatorRuntimeMetricsSupervisors     `json:"supervisors"`
	Deliveries     OperatorRuntimeMetricsDeliveries      `json:"deliveries"`
	Collection     OperatorRuntimeMetricsCollectionState `json:"collection"`
	Points         []OperatorRuntimeMetricPoint          `json:"points,omitempty"`
}

type _OperatorRuntimeMetricsAggregate OperatorRuntimeMetricsAggregate

// NewOperatorRuntimeMetricsAggregate instantiates a new OperatorRuntimeMetricsAggregate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeMetricsAggregate(organizationId NullableString, capturedAt time.Time, consumers OperatorRuntimeMetricsConsumerSummary, assignment OperatorRuntimeMetricsAssignment, workers OperatorRuntimeMetricsWorkers, supervisors OperatorRuntimeMetricsSupervisors, deliveries OperatorRuntimeMetricsDeliveries, collection OperatorRuntimeMetricsCollectionState) *OperatorRuntimeMetricsAggregate {
	this := OperatorRuntimeMetricsAggregate{}
	this.OrganizationId = organizationId
	this.CapturedAt = capturedAt
	this.Consumers = consumers
	this.Assignment = assignment
	this.Workers = workers
	this.Supervisors = supervisors
	this.Deliveries = deliveries
	this.Collection = collection
	return &this
}

// NewOperatorRuntimeMetricsAggregateWithDefaults instantiates a new OperatorRuntimeMetricsAggregate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeMetricsAggregateWithDefaults() *OperatorRuntimeMetricsAggregate {
	this := OperatorRuntimeMetricsAggregate{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *OperatorRuntimeMetricsAggregate) GetOrganizationId() string {
	if o == nil || o.OrganizationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatorRuntimeMetricsAggregate) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// SetOrganizationId sets field value
func (o *OperatorRuntimeMetricsAggregate) SetOrganizationId(v string) {
	o.OrganizationId.Set(&v)
}

// GetCapturedAt returns the CapturedAt field value
func (o *OperatorRuntimeMetricsAggregate) GetCapturedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CapturedAt
}

// GetCapturedAtOk returns a tuple with the CapturedAt field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetCapturedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapturedAt, true
}

// SetCapturedAt sets field value
func (o *OperatorRuntimeMetricsAggregate) SetCapturedAt(v time.Time) {
	o.CapturedAt = v
}

// GetConsumers returns the Consumers field value
func (o *OperatorRuntimeMetricsAggregate) GetConsumers() OperatorRuntimeMetricsConsumerSummary {
	if o == nil {
		var ret OperatorRuntimeMetricsConsumerSummary
		return ret
	}

	return o.Consumers
}

// GetConsumersOk returns a tuple with the Consumers field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetConsumersOk() (*OperatorRuntimeMetricsConsumerSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Consumers, true
}

// SetConsumers sets field value
func (o *OperatorRuntimeMetricsAggregate) SetConsumers(v OperatorRuntimeMetricsConsumerSummary) {
	o.Consumers = v
}

// GetAssignment returns the Assignment field value
func (o *OperatorRuntimeMetricsAggregate) GetAssignment() OperatorRuntimeMetricsAssignment {
	if o == nil {
		var ret OperatorRuntimeMetricsAssignment
		return ret
	}

	return o.Assignment
}

// GetAssignmentOk returns a tuple with the Assignment field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetAssignmentOk() (*OperatorRuntimeMetricsAssignment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assignment, true
}

// SetAssignment sets field value
func (o *OperatorRuntimeMetricsAggregate) SetAssignment(v OperatorRuntimeMetricsAssignment) {
	o.Assignment = v
}

// GetWorkers returns the Workers field value
func (o *OperatorRuntimeMetricsAggregate) GetWorkers() OperatorRuntimeMetricsWorkers {
	if o == nil {
		var ret OperatorRuntimeMetricsWorkers
		return ret
	}

	return o.Workers
}

// GetWorkersOk returns a tuple with the Workers field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetWorkersOk() (*OperatorRuntimeMetricsWorkers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Workers, true
}

// SetWorkers sets field value
func (o *OperatorRuntimeMetricsAggregate) SetWorkers(v OperatorRuntimeMetricsWorkers) {
	o.Workers = v
}

// GetSupervisors returns the Supervisors field value
func (o *OperatorRuntimeMetricsAggregate) GetSupervisors() OperatorRuntimeMetricsSupervisors {
	if o == nil {
		var ret OperatorRuntimeMetricsSupervisors
		return ret
	}

	return o.Supervisors
}

// GetSupervisorsOk returns a tuple with the Supervisors field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetSupervisorsOk() (*OperatorRuntimeMetricsSupervisors, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Supervisors, true
}

// SetSupervisors sets field value
func (o *OperatorRuntimeMetricsAggregate) SetSupervisors(v OperatorRuntimeMetricsSupervisors) {
	o.Supervisors = v
}

// GetDeliveries returns the Deliveries field value
func (o *OperatorRuntimeMetricsAggregate) GetDeliveries() OperatorRuntimeMetricsDeliveries {
	if o == nil {
		var ret OperatorRuntimeMetricsDeliveries
		return ret
	}

	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetDeliveriesOk() (*OperatorRuntimeMetricsDeliveries, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deliveries, true
}

// SetDeliveries sets field value
func (o *OperatorRuntimeMetricsAggregate) SetDeliveries(v OperatorRuntimeMetricsDeliveries) {
	o.Deliveries = v
}

// GetCollection returns the Collection field value
func (o *OperatorRuntimeMetricsAggregate) GetCollection() OperatorRuntimeMetricsCollectionState {
	if o == nil {
		var ret OperatorRuntimeMetricsCollectionState
		return ret
	}

	return o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetCollectionOk() (*OperatorRuntimeMetricsCollectionState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Collection, true
}

// SetCollection sets field value
func (o *OperatorRuntimeMetricsAggregate) SetCollection(v OperatorRuntimeMetricsCollectionState) {
	o.Collection = v
}

// GetPoints returns the Points field value if set, zero value otherwise.
func (o *OperatorRuntimeMetricsAggregate) GetPoints() []OperatorRuntimeMetricPoint {
	if o == nil || IsNil(o.Points) {
		var ret []OperatorRuntimeMetricPoint
		return ret
	}
	return o.Points
}

// GetPointsOk returns a tuple with the Points field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeMetricsAggregate) GetPointsOk() ([]OperatorRuntimeMetricPoint, bool) {
	if o == nil || IsNil(o.Points) {
		return nil, false
	}
	return o.Points, true
}

// HasPoints returns a boolean if a field has been set.
func (o *OperatorRuntimeMetricsAggregate) HasPoints() bool {
	if o != nil && !IsNil(o.Points) {
		return true
	}

	return false
}

// SetPoints gets a reference to the given []OperatorRuntimeMetricPoint and assigns it to the Points field.
func (o *OperatorRuntimeMetricsAggregate) SetPoints(v []OperatorRuntimeMetricPoint) {
	o.Points = v
}

func (o OperatorRuntimeMetricsAggregate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeMetricsAggregate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId.Get()
	toSerialize["captured_at"] = o.CapturedAt
	toSerialize["consumers"] = o.Consumers
	toSerialize["assignment"] = o.Assignment
	toSerialize["workers"] = o.Workers
	toSerialize["supervisors"] = o.Supervisors
	toSerialize["deliveries"] = o.Deliveries
	toSerialize["collection"] = o.Collection
	if !IsNil(o.Points) {
		toSerialize["points"] = o.Points
	}
	return toSerialize, nil
}

func (o *OperatorRuntimeMetricsAggregate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization_id",
		"captured_at",
		"consumers",
		"assignment",
		"workers",
		"supervisors",
		"deliveries",
		"collection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeMetricsAggregate := _OperatorRuntimeMetricsAggregate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeMetricsAggregate)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeMetricsAggregate(varOperatorRuntimeMetricsAggregate)

	return err
}

type NullableOperatorRuntimeMetricsAggregate struct {
	value *OperatorRuntimeMetricsAggregate
	isSet bool
}

func (v NullableOperatorRuntimeMetricsAggregate) Get() *OperatorRuntimeMetricsAggregate {
	return v.value
}

func (v *NullableOperatorRuntimeMetricsAggregate) Set(val *OperatorRuntimeMetricsAggregate) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeMetricsAggregate) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeMetricsAggregate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeMetricsAggregate(val *OperatorRuntimeMetricsAggregate) *NullableOperatorRuntimeMetricsAggregate {
	return &NullableOperatorRuntimeMetricsAggregate{value: val, isSet: true}
}

func (v NullableOperatorRuntimeMetricsAggregate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeMetricsAggregate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
