/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuthorityVoteCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorityVoteCreateRequest{}

// AuthorityVoteCreateRequest struct for AuthorityVoteCreateRequest
type AuthorityVoteCreateRequest struct {
	ControllerId string       `json:"controller_id"`
	Decision     DecisionEnum `json:"decision"`
	Reason       *string      `json:"reason,omitempty"`
}

type _AuthorityVoteCreateRequest AuthorityVoteCreateRequest

// NewAuthorityVoteCreateRequest instantiates a new AuthorityVoteCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorityVoteCreateRequest(controllerId string, decision DecisionEnum) *AuthorityVoteCreateRequest {
	this := AuthorityVoteCreateRequest{}
	this.ControllerId = controllerId
	this.Decision = decision
	var reason string = ""
	this.Reason = &reason
	return &this
}

// NewAuthorityVoteCreateRequestWithDefaults instantiates a new AuthorityVoteCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorityVoteCreateRequestWithDefaults() *AuthorityVoteCreateRequest {
	this := AuthorityVoteCreateRequest{}
	var reason string = ""
	this.Reason = &reason
	return &this
}

// GetControllerId returns the ControllerId field value
func (o *AuthorityVoteCreateRequest) GetControllerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ControllerId
}

// GetControllerIdOk returns a tuple with the ControllerId field value
// and a boolean to check if the value has been set.
func (o *AuthorityVoteCreateRequest) GetControllerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ControllerId, true
}

// SetControllerId sets field value
func (o *AuthorityVoteCreateRequest) SetControllerId(v string) {
	o.ControllerId = v
}

// GetDecision returns the Decision field value
func (o *AuthorityVoteCreateRequest) GetDecision() DecisionEnum {
	if o == nil {
		var ret DecisionEnum
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *AuthorityVoteCreateRequest) GetDecisionOk() (*DecisionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *AuthorityVoteCreateRequest) SetDecision(v DecisionEnum) {
	o.Decision = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AuthorityVoteCreateRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorityVoteCreateRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AuthorityVoteCreateRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AuthorityVoteCreateRequest) SetReason(v string) {
	o.Reason = &v
}

func (o AuthorityVoteCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorityVoteCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["controller_id"] = o.ControllerId
	toSerialize["decision"] = o.Decision
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *AuthorityVoteCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"controller_id",
		"decision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorityVoteCreateRequest := _AuthorityVoteCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorityVoteCreateRequest)

	if err != nil {
		return err
	}

	*o = AuthorityVoteCreateRequest(varAuthorityVoteCreateRequest)

	return err
}

type NullableAuthorityVoteCreateRequest struct {
	value *AuthorityVoteCreateRequest
	isSet bool
}

func (v NullableAuthorityVoteCreateRequest) Get() *AuthorityVoteCreateRequest {
	return v.value
}

func (v *NullableAuthorityVoteCreateRequest) Set(val *AuthorityVoteCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorityVoteCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorityVoteCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorityVoteCreateRequest(val *AuthorityVoteCreateRequest) *NullableAuthorityVoteCreateRequest {
	return &NullableAuthorityVoteCreateRequest{value: val, isSet: true}
}

func (v NullableAuthorityVoteCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorityVoteCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
