/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RetentionPolicyRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetentionPolicyRead{}

// RetentionPolicyRead struct for RetentionPolicyRead
type RetentionPolicyRead struct {
	Id               string                       `json:"id"`
	OrganizationId   NullableString               `json:"organization_id,omitempty"`
	Name             string                       `json:"name"`
	Description      *string                      `json:"description,omitempty"`
	Scope            RetentionPolicyReadScopeEnum `json:"scope"`
	EventTypeId      NullableString               `json:"event_type_id"`
	EventTypeName    NullableString               `json:"event_type_name"`
	Source           string                       `json:"source"`
	ArchiveAfterDays NullableInt64                `json:"archive_after_days,omitempty"`
	DeleteAfterDays  NullableInt64                `json:"delete_after_days,omitempty"`
	RetainForever    *bool                        `json:"retain_forever,omitempty"`
	IsEnabled        *bool                        `json:"is_enabled,omitempty"`
	CreatedAt        time.Time                    `json:"created_at"`
	UpdatedAt        time.Time                    `json:"updated_at"`
}

type _RetentionPolicyRead RetentionPolicyRead

// NewRetentionPolicyRead instantiates a new RetentionPolicyRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetentionPolicyRead(id string, name string, scope RetentionPolicyReadScopeEnum, eventTypeId NullableString, eventTypeName NullableString, source string, createdAt time.Time, updatedAt time.Time) *RetentionPolicyRead {
	this := RetentionPolicyRead{}
	this.Id = id
	this.Name = name
	this.Scope = scope
	this.EventTypeId = eventTypeId
	this.EventTypeName = eventTypeName
	this.Source = source
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewRetentionPolicyReadWithDefaults instantiates a new RetentionPolicyRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetentionPolicyReadWithDefaults() *RetentionPolicyRead {
	this := RetentionPolicyRead{}
	return &this
}

// GetId returns the Id field value
func (o *RetentionPolicyRead) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RetentionPolicyRead) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetentionPolicyRead) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyRead) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasOrganizationId() bool {
	if o != nil && o.OrganizationId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given NullableString and assigns it to the OrganizationId field.
func (o *RetentionPolicyRead) SetOrganizationId(v string) {
	o.OrganizationId.Set(&v)
}

// SetOrganizationIdNil sets the value for OrganizationId to be an explicit nil
func (o *RetentionPolicyRead) SetOrganizationIdNil() {
	o.OrganizationId.Set(nil)
}

// UnsetOrganizationId ensures that no value is present for OrganizationId, not even an explicit nil
func (o *RetentionPolicyRead) UnsetOrganizationId() {
	o.OrganizationId.Unset()
}

// GetName returns the Name field value
func (o *RetentionPolicyRead) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RetentionPolicyRead) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RetentionPolicyRead) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RetentionPolicyRead) SetDescription(v string) {
	o.Description = &v
}

// GetScope returns the Scope field value
func (o *RetentionPolicyRead) GetScope() RetentionPolicyReadScopeEnum {
	if o == nil {
		var ret RetentionPolicyReadScopeEnum
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetScopeOk() (*RetentionPolicyReadScopeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *RetentionPolicyRead) SetScope(v RetentionPolicyReadScopeEnum) {
	o.Scope = v
}

// GetEventTypeId returns the EventTypeId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RetentionPolicyRead) GetEventTypeId() string {
	if o == nil || o.EventTypeId.Get() == nil {
		var ret string
		return ret
	}

	return *o.EventTypeId.Get()
}

// GetEventTypeIdOk returns a tuple with the EventTypeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyRead) GetEventTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypeId.Get(), o.EventTypeId.IsSet()
}

// SetEventTypeId sets field value
func (o *RetentionPolicyRead) SetEventTypeId(v string) {
	o.EventTypeId.Set(&v)
}

// GetEventTypeName returns the EventTypeName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RetentionPolicyRead) GetEventTypeName() string {
	if o == nil || o.EventTypeName.Get() == nil {
		var ret string
		return ret
	}

	return *o.EventTypeName.Get()
}

// GetEventTypeNameOk returns a tuple with the EventTypeName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyRead) GetEventTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypeName.Get(), o.EventTypeName.IsSet()
}

// SetEventTypeName sets field value
func (o *RetentionPolicyRead) SetEventTypeName(v string) {
	o.EventTypeName.Set(&v)
}

// GetSource returns the Source field value
func (o *RetentionPolicyRead) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *RetentionPolicyRead) SetSource(v string) {
	o.Source = v
}

// GetArchiveAfterDays returns the ArchiveAfterDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetentionPolicyRead) GetArchiveAfterDays() int64 {
	if o == nil || IsNil(o.ArchiveAfterDays.Get()) {
		var ret int64
		return ret
	}
	return *o.ArchiveAfterDays.Get()
}

// GetArchiveAfterDaysOk returns a tuple with the ArchiveAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyRead) GetArchiveAfterDaysOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchiveAfterDays.Get(), o.ArchiveAfterDays.IsSet()
}

// HasArchiveAfterDays returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasArchiveAfterDays() bool {
	if o != nil && o.ArchiveAfterDays.IsSet() {
		return true
	}

	return false
}

// SetArchiveAfterDays gets a reference to the given NullableInt64 and assigns it to the ArchiveAfterDays field.
func (o *RetentionPolicyRead) SetArchiveAfterDays(v int64) {
	o.ArchiveAfterDays.Set(&v)
}

// SetArchiveAfterDaysNil sets the value for ArchiveAfterDays to be an explicit nil
func (o *RetentionPolicyRead) SetArchiveAfterDaysNil() {
	o.ArchiveAfterDays.Set(nil)
}

// UnsetArchiveAfterDays ensures that no value is present for ArchiveAfterDays, not even an explicit nil
func (o *RetentionPolicyRead) UnsetArchiveAfterDays() {
	o.ArchiveAfterDays.Unset()
}

// GetDeleteAfterDays returns the DeleteAfterDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetentionPolicyRead) GetDeleteAfterDays() int64 {
	if o == nil || IsNil(o.DeleteAfterDays.Get()) {
		var ret int64
		return ret
	}
	return *o.DeleteAfterDays.Get()
}

// GetDeleteAfterDaysOk returns a tuple with the DeleteAfterDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyRead) GetDeleteAfterDaysOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeleteAfterDays.Get(), o.DeleteAfterDays.IsSet()
}

// HasDeleteAfterDays returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasDeleteAfterDays() bool {
	if o != nil && o.DeleteAfterDays.IsSet() {
		return true
	}

	return false
}

// SetDeleteAfterDays gets a reference to the given NullableInt64 and assigns it to the DeleteAfterDays field.
func (o *RetentionPolicyRead) SetDeleteAfterDays(v int64) {
	o.DeleteAfterDays.Set(&v)
}

// SetDeleteAfterDaysNil sets the value for DeleteAfterDays to be an explicit nil
func (o *RetentionPolicyRead) SetDeleteAfterDaysNil() {
	o.DeleteAfterDays.Set(nil)
}

// UnsetDeleteAfterDays ensures that no value is present for DeleteAfterDays, not even an explicit nil
func (o *RetentionPolicyRead) UnsetDeleteAfterDays() {
	o.DeleteAfterDays.Unset()
}

// GetRetainForever returns the RetainForever field value if set, zero value otherwise.
func (o *RetentionPolicyRead) GetRetainForever() bool {
	if o == nil || IsNil(o.RetainForever) {
		var ret bool
		return ret
	}
	return *o.RetainForever
}

// GetRetainForeverOk returns a tuple with the RetainForever field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetRetainForeverOk() (*bool, bool) {
	if o == nil || IsNil(o.RetainForever) {
		return nil, false
	}
	return o.RetainForever, true
}

// HasRetainForever returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasRetainForever() bool {
	if o != nil && !IsNil(o.RetainForever) {
		return true
	}

	return false
}

// SetRetainForever gets a reference to the given bool and assigns it to the RetainForever field.
func (o *RetentionPolicyRead) SetRetainForever(v bool) {
	o.RetainForever = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *RetentionPolicyRead) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *RetentionPolicyRead) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *RetentionPolicyRead) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RetentionPolicyRead) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RetentionPolicyRead) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *RetentionPolicyRead) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyRead) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *RetentionPolicyRead) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o RetentionPolicyRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetentionPolicyRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrganizationId.IsSet() {
		toSerialize["organization_id"] = o.OrganizationId.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["scope"] = o.Scope
	toSerialize["source"] = o.Source
	if o.ArchiveAfterDays.IsSet() {
		toSerialize["archive_after_days"] = o.ArchiveAfterDays.Get()
	}
	if o.DeleteAfterDays.IsSet() {
		toSerialize["delete_after_days"] = o.DeleteAfterDays.Get()
	}
	if !IsNil(o.RetainForever) {
		toSerialize["retain_forever"] = o.RetainForever
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	return toSerialize, nil
}

func (o *RetentionPolicyRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"scope",
		"event_type_id",
		"event_type_name",
		"source",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetentionPolicyRead := _RetentionPolicyRead{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetentionPolicyRead)

	if err != nil {
		return err
	}

	*o = RetentionPolicyRead(varRetentionPolicyRead)

	return err
}

type NullableRetentionPolicyRead struct {
	value *RetentionPolicyRead
	isSet bool
}

func (v NullableRetentionPolicyRead) Get() *RetentionPolicyRead {
	return v.value
}

func (v *NullableRetentionPolicyRead) Set(val *RetentionPolicyRead) {
	v.value = val
	v.isSet = true
}

func (v NullableRetentionPolicyRead) IsSet() bool {
	return v.isSet
}

func (v *NullableRetentionPolicyRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetentionPolicyRead(val *RetentionPolicyRead) *NullableRetentionPolicyRead {
	return &NullableRetentionPolicyRead{value: val, isSet: true}
}

func (v NullableRetentionPolicyRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetentionPolicyRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
