/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RetentionPolicyVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetentionPolicyVersion{}

// RetentionPolicyVersion struct for RetentionPolicyVersion
type RetentionPolicyVersion struct {
	Id                     string                         `json:"id"`
	OrganizationId         string                         `json:"organization_id"`
	Version                int64                          `json:"version"`
	Status                 *LifecycleDefinitionStatusEnum `json:"status,omitempty"`
	Fingerprint            string                         `json:"fingerprint"`
	CatalogFingerprint     *string                        `json:"catalog_fingerprint,omitempty"`
	CompositionFingerprint *string                        `json:"composition_fingerprint,omitempty"`
	DefaultClassification  *string                        `json:"default_classification,omitempty"`
	EffectiveFrom          time.Time                      `json:"effective_from"`
	CreatedBy              string                         `json:"created_by"`
	Description            *string                        `json:"description,omitempty"`
	Metadata               interface{}                    `json:"metadata,omitempty"`
	CreatedAt              time.Time                      `json:"created_at"`
	Policy                 string                         `json:"policy"`
}

type _RetentionPolicyVersion RetentionPolicyVersion

// NewRetentionPolicyVersion instantiates a new RetentionPolicyVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetentionPolicyVersion(id string, organizationId string, version int64, fingerprint string, effectiveFrom time.Time, createdBy string, createdAt time.Time, policy string) *RetentionPolicyVersion {
	this := RetentionPolicyVersion{}
	this.Id = id
	this.OrganizationId = organizationId
	this.Version = version
	this.Fingerprint = fingerprint
	this.EffectiveFrom = effectiveFrom
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	this.Policy = policy
	return &this
}

// NewRetentionPolicyVersionWithDefaults instantiates a new RetentionPolicyVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetentionPolicyVersionWithDefaults() *RetentionPolicyVersion {
	this := RetentionPolicyVersion{}
	return &this
}

// GetId returns the Id field value
func (o *RetentionPolicyVersion) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RetentionPolicyVersion) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *RetentionPolicyVersion) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RetentionPolicyVersion) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetVersion returns the Version field value
func (o *RetentionPolicyVersion) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RetentionPolicyVersion) SetVersion(v int64) {
	o.Version = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RetentionPolicyVersion) GetStatus() LifecycleDefinitionStatusEnum {
	if o == nil || IsNil(o.Status) {
		var ret LifecycleDefinitionStatusEnum
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetStatusOk() (*LifecycleDefinitionStatusEnum, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given LifecycleDefinitionStatusEnum and assigns it to the Status field.
func (o *RetentionPolicyVersion) SetStatus(v LifecycleDefinitionStatusEnum) {
	o.Status = &v
}

// GetFingerprint returns the Fingerprint field value
func (o *RetentionPolicyVersion) GetFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fingerprint, true
}

// SetFingerprint sets field value
func (o *RetentionPolicyVersion) SetFingerprint(v string) {
	o.Fingerprint = v
}

// GetCatalogFingerprint returns the CatalogFingerprint field value if set, zero value otherwise.
func (o *RetentionPolicyVersion) GetCatalogFingerprint() string {
	if o == nil || IsNil(o.CatalogFingerprint) {
		var ret string
		return ret
	}
	return *o.CatalogFingerprint
}

// GetCatalogFingerprintOk returns a tuple with the CatalogFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetCatalogFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.CatalogFingerprint) {
		return nil, false
	}
	return o.CatalogFingerprint, true
}

// HasCatalogFingerprint returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasCatalogFingerprint() bool {
	if o != nil && !IsNil(o.CatalogFingerprint) {
		return true
	}

	return false
}

// SetCatalogFingerprint gets a reference to the given string and assigns it to the CatalogFingerprint field.
func (o *RetentionPolicyVersion) SetCatalogFingerprint(v string) {
	o.CatalogFingerprint = &v
}

// GetCompositionFingerprint returns the CompositionFingerprint field value if set, zero value otherwise.
func (o *RetentionPolicyVersion) GetCompositionFingerprint() string {
	if o == nil || IsNil(o.CompositionFingerprint) {
		var ret string
		return ret
	}
	return *o.CompositionFingerprint
}

// GetCompositionFingerprintOk returns a tuple with the CompositionFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetCompositionFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.CompositionFingerprint) {
		return nil, false
	}
	return o.CompositionFingerprint, true
}

// HasCompositionFingerprint returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasCompositionFingerprint() bool {
	if o != nil && !IsNil(o.CompositionFingerprint) {
		return true
	}

	return false
}

// SetCompositionFingerprint gets a reference to the given string and assigns it to the CompositionFingerprint field.
func (o *RetentionPolicyVersion) SetCompositionFingerprint(v string) {
	o.CompositionFingerprint = &v
}

// GetDefaultClassification returns the DefaultClassification field value if set, zero value otherwise.
func (o *RetentionPolicyVersion) GetDefaultClassification() string {
	if o == nil || IsNil(o.DefaultClassification) {
		var ret string
		return ret
	}
	return *o.DefaultClassification
}

// GetDefaultClassificationOk returns a tuple with the DefaultClassification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetDefaultClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultClassification) {
		return nil, false
	}
	return o.DefaultClassification, true
}

// HasDefaultClassification returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasDefaultClassification() bool {
	if o != nil && !IsNil(o.DefaultClassification) {
		return true
	}

	return false
}

// SetDefaultClassification gets a reference to the given string and assigns it to the DefaultClassification field.
func (o *RetentionPolicyVersion) SetDefaultClassification(v string) {
	o.DefaultClassification = &v
}

// GetEffectiveFrom returns the EffectiveFrom field value
func (o *RetentionPolicyVersion) GetEffectiveFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetEffectiveFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveFrom, true
}

// SetEffectiveFrom sets field value
func (o *RetentionPolicyVersion) SetEffectiveFrom(v time.Time) {
	o.EffectiveFrom = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *RetentionPolicyVersion) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *RetentionPolicyVersion) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RetentionPolicyVersion) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RetentionPolicyVersion) SetDescription(v string) {
	o.Description = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetentionPolicyVersion) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetentionPolicyVersion) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RetentionPolicyVersion) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *RetentionPolicyVersion) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RetentionPolicyVersion) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RetentionPolicyVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetPolicy returns the Policy field value
func (o *RetentionPolicyVersion) GetPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *RetentionPolicyVersion) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *RetentionPolicyVersion) SetPolicy(v string) {
	o.Policy = v
}

func (o RetentionPolicyVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetentionPolicyVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["version"] = o.Version
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["fingerprint"] = o.Fingerprint
	if !IsNil(o.CatalogFingerprint) {
		toSerialize["catalog_fingerprint"] = o.CatalogFingerprint
	}
	if !IsNil(o.CompositionFingerprint) {
		toSerialize["composition_fingerprint"] = o.CompositionFingerprint
	}
	if !IsNil(o.DefaultClassification) {
		toSerialize["default_classification"] = o.DefaultClassification
	}
	toSerialize["effective_from"] = o.EffectiveFrom
	toSerialize["created_by"] = o.CreatedBy
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["policy"] = o.Policy
	return toSerialize, nil
}

func (o *RetentionPolicyVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organization_id",
		"version",
		"fingerprint",
		"effective_from",
		"created_by",
		"created_at",
		"policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetentionPolicyVersion := _RetentionPolicyVersion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetentionPolicyVersion)

	if err != nil {
		return err
	}

	*o = RetentionPolicyVersion(varRetentionPolicyVersion)

	return err
}

type NullableRetentionPolicyVersion struct {
	value *RetentionPolicyVersion
	isSet bool
}

func (v NullableRetentionPolicyVersion) Get() *RetentionPolicyVersion {
	return v.value
}

func (v *NullableRetentionPolicyVersion) Set(val *RetentionPolicyVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableRetentionPolicyVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableRetentionPolicyVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetentionPolicyVersion(val *RetentionPolicyVersion) *NullableRetentionPolicyVersion {
	return &NullableRetentionPolicyVersion{value: val, isSet: true}
}

func (v NullableRetentionPolicyVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetentionPolicyVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
