/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OperatorRuntimeDashboardDistributions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeDashboardDistributions{}

// OperatorRuntimeDashboardDistributions struct for OperatorRuntimeDashboardDistributions
type OperatorRuntimeDashboardDistributions struct {
	HealthStatuses  map[string]int32 `json:"health_statuses"`
	DesiredStatuses map[string]int32 `json:"desired_statuses"`
}

type _OperatorRuntimeDashboardDistributions OperatorRuntimeDashboardDistributions

// NewOperatorRuntimeDashboardDistributions instantiates a new OperatorRuntimeDashboardDistributions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeDashboardDistributions(healthStatuses map[string]int32, desiredStatuses map[string]int32) *OperatorRuntimeDashboardDistributions {
	this := OperatorRuntimeDashboardDistributions{}
	this.HealthStatuses = healthStatuses
	this.DesiredStatuses = desiredStatuses
	return &this
}

// NewOperatorRuntimeDashboardDistributionsWithDefaults instantiates a new OperatorRuntimeDashboardDistributions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeDashboardDistributionsWithDefaults() *OperatorRuntimeDashboardDistributions {
	this := OperatorRuntimeDashboardDistributions{}
	return &this
}

// GetHealthStatuses returns the HealthStatuses field value
func (o *OperatorRuntimeDashboardDistributions) GetHealthStatuses() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.HealthStatuses
}

// GetHealthStatusesOk returns a tuple with the HealthStatuses field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeDashboardDistributions) GetHealthStatusesOk() (*map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HealthStatuses, true
}

// SetHealthStatuses sets field value
func (o *OperatorRuntimeDashboardDistributions) SetHealthStatuses(v map[string]int32) {
	o.HealthStatuses = v
}

// GetDesiredStatuses returns the DesiredStatuses field value
func (o *OperatorRuntimeDashboardDistributions) GetDesiredStatuses() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.DesiredStatuses
}

// GetDesiredStatusesOk returns a tuple with the DesiredStatuses field value
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeDashboardDistributions) GetDesiredStatusesOk() (*map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DesiredStatuses, true
}

// SetDesiredStatuses sets field value
func (o *OperatorRuntimeDashboardDistributions) SetDesiredStatuses(v map[string]int32) {
	o.DesiredStatuses = v
}

func (o OperatorRuntimeDashboardDistributions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeDashboardDistributions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["health_statuses"] = o.HealthStatuses
	toSerialize["desired_statuses"] = o.DesiredStatuses
	return toSerialize, nil
}

func (o *OperatorRuntimeDashboardDistributions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"health_statuses",
		"desired_statuses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRuntimeDashboardDistributions := _OperatorRuntimeDashboardDistributions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRuntimeDashboardDistributions)

	if err != nil {
		return err
	}

	*o = OperatorRuntimeDashboardDistributions(varOperatorRuntimeDashboardDistributions)

	return err
}

type NullableOperatorRuntimeDashboardDistributions struct {
	value *OperatorRuntimeDashboardDistributions
	isSet bool
}

func (v NullableOperatorRuntimeDashboardDistributions) Get() *OperatorRuntimeDashboardDistributions {
	return v.value
}

func (v *NullableOperatorRuntimeDashboardDistributions) Set(val *OperatorRuntimeDashboardDistributions) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeDashboardDistributions) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeDashboardDistributions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeDashboardDistributions(val *OperatorRuntimeDashboardDistributions) *NullableOperatorRuntimeDashboardDistributions {
	return &NullableOperatorRuntimeDashboardDistributions{value: val, isSet: true}
}

func (v NullableOperatorRuntimeDashboardDistributions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeDashboardDistributions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
