/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LifecyclePolicySummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecyclePolicySummary{}

// LifecyclePolicySummary struct for LifecyclePolicySummary
type LifecyclePolicySummary struct {
	TotalPolicies  int32            `json:"total_policies"`
	TotalVersions  int32            `json:"total_versions"`
	ActiveVersions int32            `json:"active_versions"`
	DraftVersions  int32            `json:"draft_versions"`
	StatusCounts   map[string]int32 `json:"status_counts"`
}

type _LifecyclePolicySummary LifecyclePolicySummary

// NewLifecyclePolicySummary instantiates a new LifecyclePolicySummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecyclePolicySummary(totalPolicies int32, totalVersions int32, activeVersions int32, draftVersions int32, statusCounts map[string]int32) *LifecyclePolicySummary {
	this := LifecyclePolicySummary{}
	this.TotalPolicies = totalPolicies
	this.TotalVersions = totalVersions
	this.ActiveVersions = activeVersions
	this.DraftVersions = draftVersions
	this.StatusCounts = statusCounts
	return &this
}

// NewLifecyclePolicySummaryWithDefaults instantiates a new LifecyclePolicySummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecyclePolicySummaryWithDefaults() *LifecyclePolicySummary {
	this := LifecyclePolicySummary{}
	return &this
}

// GetTotalPolicies returns the TotalPolicies field value
func (o *LifecyclePolicySummary) GetTotalPolicies() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPolicies
}

// GetTotalPoliciesOk returns a tuple with the TotalPolicies field value
// and a boolean to check if the value has been set.
func (o *LifecyclePolicySummary) GetTotalPoliciesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPolicies, true
}

// SetTotalPolicies sets field value
func (o *LifecyclePolicySummary) SetTotalPolicies(v int32) {
	o.TotalPolicies = v
}

// GetTotalVersions returns the TotalVersions field value
func (o *LifecyclePolicySummary) GetTotalVersions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalVersions
}

// GetTotalVersionsOk returns a tuple with the TotalVersions field value
// and a boolean to check if the value has been set.
func (o *LifecyclePolicySummary) GetTotalVersionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalVersions, true
}

// SetTotalVersions sets field value
func (o *LifecyclePolicySummary) SetTotalVersions(v int32) {
	o.TotalVersions = v
}

// GetActiveVersions returns the ActiveVersions field value
func (o *LifecyclePolicySummary) GetActiveVersions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveVersions
}

// GetActiveVersionsOk returns a tuple with the ActiveVersions field value
// and a boolean to check if the value has been set.
func (o *LifecyclePolicySummary) GetActiveVersionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveVersions, true
}

// SetActiveVersions sets field value
func (o *LifecyclePolicySummary) SetActiveVersions(v int32) {
	o.ActiveVersions = v
}

// GetDraftVersions returns the DraftVersions field value
func (o *LifecyclePolicySummary) GetDraftVersions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DraftVersions
}

// GetDraftVersionsOk returns a tuple with the DraftVersions field value
// and a boolean to check if the value has been set.
func (o *LifecyclePolicySummary) GetDraftVersionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DraftVersions, true
}

// SetDraftVersions sets field value
func (o *LifecyclePolicySummary) SetDraftVersions(v int32) {
	o.DraftVersions = v
}

// GetStatusCounts returns the StatusCounts field value
func (o *LifecyclePolicySummary) GetStatusCounts() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.StatusCounts
}

// GetStatusCountsOk returns a tuple with the StatusCounts field value
// and a boolean to check if the value has been set.
func (o *LifecyclePolicySummary) GetStatusCountsOk() (*map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCounts, true
}

// SetStatusCounts sets field value
func (o *LifecyclePolicySummary) SetStatusCounts(v map[string]int32) {
	o.StatusCounts = v
}

func (o LifecyclePolicySummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecyclePolicySummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_policies"] = o.TotalPolicies
	toSerialize["total_versions"] = o.TotalVersions
	toSerialize["active_versions"] = o.ActiveVersions
	toSerialize["draft_versions"] = o.DraftVersions
	toSerialize["status_counts"] = o.StatusCounts
	return toSerialize, nil
}

func (o *LifecyclePolicySummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_policies",
		"total_versions",
		"active_versions",
		"draft_versions",
		"status_counts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLifecyclePolicySummary := _LifecyclePolicySummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLifecyclePolicySummary)

	if err != nil {
		return err
	}

	*o = LifecyclePolicySummary(varLifecyclePolicySummary)

	return err
}

type NullableLifecyclePolicySummary struct {
	value *LifecyclePolicySummary
	isSet bool
}

func (v NullableLifecyclePolicySummary) Get() *LifecyclePolicySummary {
	return v.value
}

func (v *NullableLifecyclePolicySummary) Set(val *LifecyclePolicySummary) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecyclePolicySummary) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecyclePolicySummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecyclePolicySummary(val *LifecyclePolicySummary) *NullableLifecyclePolicySummary {
	return &NullableLifecyclePolicySummary{value: val, isSet: true}
}

func (v NullableLifecyclePolicySummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecyclePolicySummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
