/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// CriticalityEnum * `mission_critical` - mission_critical * `business_critical` - business_critical * `important` - important * `standard` - standard
type CriticalityEnum string

// List of CriticalityEnum
const (
	CRITICALITYENUM_MISSION_CRITICAL  CriticalityEnum = "mission_critical"
	CRITICALITYENUM_BUSINESS_CRITICAL CriticalityEnum = "business_critical"
	CRITICALITYENUM_IMPORTANT         CriticalityEnum = "important"
	CRITICALITYENUM_STANDARD          CriticalityEnum = "standard"
)

// All allowed values of CriticalityEnum enum
var AllowedCriticalityEnumEnumValues = []CriticalityEnum{
	"mission_critical",
	"business_critical",
	"important",
	"standard",
}

func (v *CriticalityEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CriticalityEnum(value)
	for _, existing := range AllowedCriticalityEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CriticalityEnum", value)
}

// NewCriticalityEnumFromValue returns a pointer to a valid CriticalityEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCriticalityEnumFromValue(v string) (*CriticalityEnum, error) {
	ev := CriticalityEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CriticalityEnum: valid values are %v", v, AllowedCriticalityEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CriticalityEnum) IsValid() bool {
	for _, existing := range AllowedCriticalityEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CriticalityEnum value
func (v CriticalityEnum) Ptr() *CriticalityEnum {
	return &v
}

type NullableCriticalityEnum struct {
	value *CriticalityEnum
	isSet bool
}

func (v NullableCriticalityEnum) Get() *CriticalityEnum {
	return v.value
}

func (v *NullableCriticalityEnum) Set(val *CriticalityEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCriticalityEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCriticalityEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCriticalityEnum(val *CriticalityEnum) *NullableCriticalityEnum {
	return &NullableCriticalityEnum{value: val, isSet: true}
}

func (v NullableCriticalityEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCriticalityEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
