/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
)

// checks if the OperatorRuntimeIncidentNotificationActionRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRuntimeIncidentNotificationActionRequestRequest{}

// OperatorRuntimeIncidentNotificationActionRequestRequest struct for OperatorRuntimeIncidentNotificationActionRequestRequest
type OperatorRuntimeIncidentNotificationActionRequestRequest struct {
	Note *string `json:"note,omitempty"`
}

// NewOperatorRuntimeIncidentNotificationActionRequestRequest instantiates a new OperatorRuntimeIncidentNotificationActionRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRuntimeIncidentNotificationActionRequestRequest() *OperatorRuntimeIncidentNotificationActionRequestRequest {
	this := OperatorRuntimeIncidentNotificationActionRequestRequest{}
	var note string = ""
	this.Note = &note
	return &this
}

// NewOperatorRuntimeIncidentNotificationActionRequestRequestWithDefaults instantiates a new OperatorRuntimeIncidentNotificationActionRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRuntimeIncidentNotificationActionRequestRequestWithDefaults() *OperatorRuntimeIncidentNotificationActionRequestRequest {
	this := OperatorRuntimeIncidentNotificationActionRequestRequest{}
	var note string = ""
	this.Note = &note
	return &this
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *OperatorRuntimeIncidentNotificationActionRequestRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRuntimeIncidentNotificationActionRequestRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *OperatorRuntimeIncidentNotificationActionRequestRequest) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *OperatorRuntimeIncidentNotificationActionRequestRequest) SetNote(v string) {
	o.Note = &v
}

func (o OperatorRuntimeIncidentNotificationActionRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRuntimeIncidentNotificationActionRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	return toSerialize, nil
}

type NullableOperatorRuntimeIncidentNotificationActionRequestRequest struct {
	value *OperatorRuntimeIncidentNotificationActionRequestRequest
	isSet bool
}

func (v NullableOperatorRuntimeIncidentNotificationActionRequestRequest) Get() *OperatorRuntimeIncidentNotificationActionRequestRequest {
	return v.value
}

func (v *NullableOperatorRuntimeIncidentNotificationActionRequestRequest) Set(val *OperatorRuntimeIncidentNotificationActionRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRuntimeIncidentNotificationActionRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRuntimeIncidentNotificationActionRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRuntimeIncidentNotificationActionRequestRequest(val *OperatorRuntimeIncidentNotificationActionRequestRequest) *NullableOperatorRuntimeIncidentNotificationActionRequestRequest {
	return &NullableOperatorRuntimeIncidentNotificationActionRequestRequest{value: val, isSet: true}
}

func (v NullableOperatorRuntimeIncidentNotificationActionRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRuntimeIncidentNotificationActionRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
