/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// ScheduledActiveReleaseStatusEnum * `scheduled` - Scheduled * `active` - Active * `released` - Released * `expired` - Expired * `cancelled` - Cancelled
type ScheduledActiveReleaseStatusEnum string

// List of ScheduledActiveReleaseStatusEnum
const (
	SCHEDULEDACTIVERELEASESTATUSENUM_SCHEDULED ScheduledActiveReleaseStatusEnum = "scheduled"
	SCHEDULEDACTIVERELEASESTATUSENUM_ACTIVE    ScheduledActiveReleaseStatusEnum = "active"
	SCHEDULEDACTIVERELEASESTATUSENUM_RELEASED  ScheduledActiveReleaseStatusEnum = "released"
	SCHEDULEDACTIVERELEASESTATUSENUM_EXPIRED   ScheduledActiveReleaseStatusEnum = "expired"
	SCHEDULEDACTIVERELEASESTATUSENUM_CANCELLED ScheduledActiveReleaseStatusEnum = "cancelled"
)

// All allowed values of ScheduledActiveReleaseStatusEnum enum
var AllowedScheduledActiveReleaseStatusEnumEnumValues = []ScheduledActiveReleaseStatusEnum{
	"scheduled",
	"active",
	"released",
	"expired",
	"cancelled",
}

func (v *ScheduledActiveReleaseStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ScheduledActiveReleaseStatusEnum(value)
	for _, existing := range AllowedScheduledActiveReleaseStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ScheduledActiveReleaseStatusEnum", value)
}

// NewScheduledActiveReleaseStatusEnumFromValue returns a pointer to a valid ScheduledActiveReleaseStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewScheduledActiveReleaseStatusEnumFromValue(v string) (*ScheduledActiveReleaseStatusEnum, error) {
	ev := ScheduledActiveReleaseStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ScheduledActiveReleaseStatusEnum: valid values are %v", v, AllowedScheduledActiveReleaseStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ScheduledActiveReleaseStatusEnum) IsValid() bool {
	for _, existing := range AllowedScheduledActiveReleaseStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ScheduledActiveReleaseStatusEnum value
func (v ScheduledActiveReleaseStatusEnum) Ptr() *ScheduledActiveReleaseStatusEnum {
	return &v
}

type NullableScheduledActiveReleaseStatusEnum struct {
	value *ScheduledActiveReleaseStatusEnum
	isSet bool
}

func (v NullableScheduledActiveReleaseStatusEnum) Get() *ScheduledActiveReleaseStatusEnum {
	return v.value
}

func (v *NullableScheduledActiveReleaseStatusEnum) Set(val *ScheduledActiveReleaseStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledActiveReleaseStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledActiveReleaseStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledActiveReleaseStatusEnum(val *ScheduledActiveReleaseStatusEnum) *NullableScheduledActiveReleaseStatusEnum {
	return &NullableScheduledActiveReleaseStatusEnum{value: val, isSet: true}
}

func (v NullableScheduledActiveReleaseStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledActiveReleaseStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
