/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// RuntimeRecoveryStageStatusEnum * `pending` - Pending * `running` - Running * `succeeded` - Succeeded * `failed` - Failed * `timed_out` - Timed Out * `skipped` - Skipped * `compensated` - Compensated * `compensation_failed` - Compensation Failed
type RuntimeRecoveryStageStatusEnum string

// List of RuntimeRecoveryStageStatusEnum
const (
	RUNTIMERECOVERYSTAGESTATUSENUM_PENDING             RuntimeRecoveryStageStatusEnum = "pending"
	RUNTIMERECOVERYSTAGESTATUSENUM_RUNNING             RuntimeRecoveryStageStatusEnum = "running"
	RUNTIMERECOVERYSTAGESTATUSENUM_SUCCEEDED           RuntimeRecoveryStageStatusEnum = "succeeded"
	RUNTIMERECOVERYSTAGESTATUSENUM_FAILED              RuntimeRecoveryStageStatusEnum = "failed"
	RUNTIMERECOVERYSTAGESTATUSENUM_TIMED_OUT           RuntimeRecoveryStageStatusEnum = "timed_out"
	RUNTIMERECOVERYSTAGESTATUSENUM_SKIPPED             RuntimeRecoveryStageStatusEnum = "skipped"
	RUNTIMERECOVERYSTAGESTATUSENUM_COMPENSATED         RuntimeRecoveryStageStatusEnum = "compensated"
	RUNTIMERECOVERYSTAGESTATUSENUM_COMPENSATION_FAILED RuntimeRecoveryStageStatusEnum = "compensation_failed"
)

// All allowed values of RuntimeRecoveryStageStatusEnum enum
var AllowedRuntimeRecoveryStageStatusEnumEnumValues = []RuntimeRecoveryStageStatusEnum{
	"pending",
	"running",
	"succeeded",
	"failed",
	"timed_out",
	"skipped",
	"compensated",
	"compensation_failed",
}

func (v *RuntimeRecoveryStageStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RuntimeRecoveryStageStatusEnum(value)
	for _, existing := range AllowedRuntimeRecoveryStageStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RuntimeRecoveryStageStatusEnum", value)
}

// NewRuntimeRecoveryStageStatusEnumFromValue returns a pointer to a valid RuntimeRecoveryStageStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRuntimeRecoveryStageStatusEnumFromValue(v string) (*RuntimeRecoveryStageStatusEnum, error) {
	ev := RuntimeRecoveryStageStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RuntimeRecoveryStageStatusEnum: valid values are %v", v, AllowedRuntimeRecoveryStageStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RuntimeRecoveryStageStatusEnum) IsValid() bool {
	for _, existing := range AllowedRuntimeRecoveryStageStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RuntimeRecoveryStageStatusEnum value
func (v RuntimeRecoveryStageStatusEnum) Ptr() *RuntimeRecoveryStageStatusEnum {
	return &v
}

type NullableRuntimeRecoveryStageStatusEnum struct {
	value *RuntimeRecoveryStageStatusEnum
	isSet bool
}

func (v NullableRuntimeRecoveryStageStatusEnum) Get() *RuntimeRecoveryStageStatusEnum {
	return v.value
}

func (v *NullableRuntimeRecoveryStageStatusEnum) Set(val *RuntimeRecoveryStageStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRuntimeRecoveryStageStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRuntimeRecoveryStageStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuntimeRecoveryStageStatusEnum(val *RuntimeRecoveryStageStatusEnum) *NullableRuntimeRecoveryStageStatusEnum {
	return &NullableRuntimeRecoveryStageStatusEnum{value: val, isSet: true}
}

func (v NullableRuntimeRecoveryStageStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuntimeRecoveryStageStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
