/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LifecycleBacklogSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecycleBacklogSummary{}

// LifecycleBacklogSummary struct for LifecycleBacklogSummary
type LifecycleBacklogSummary struct {
	ArchiveBatches              int32 `json:"archive_batches"`
	PurgeBatches                int32 `json:"purge_batches"`
	PendingArchiveBatches       int32 `json:"pending_archive_batches"`
	PendingPurgeBatches         int32 `json:"pending_purge_batches"`
	RetryablePurgeCandidates    int32 `json:"retryable_purge_candidates"`
	DeadLetteredPurgeCandidates int32 `json:"dead_lettered_purge_candidates"`
	ActivePurgeLeases           int32 `json:"active_purge_leases"`
	ExpiredPurgeLeases          int32 `json:"expired_purge_leases"`
}

type _LifecycleBacklogSummary LifecycleBacklogSummary

// NewLifecycleBacklogSummary instantiates a new LifecycleBacklogSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecycleBacklogSummary(archiveBatches int32, purgeBatches int32, pendingArchiveBatches int32, pendingPurgeBatches int32, retryablePurgeCandidates int32, deadLetteredPurgeCandidates int32, activePurgeLeases int32, expiredPurgeLeases int32) *LifecycleBacklogSummary {
	this := LifecycleBacklogSummary{}
	this.ArchiveBatches = archiveBatches
	this.PurgeBatches = purgeBatches
	this.PendingArchiveBatches = pendingArchiveBatches
	this.PendingPurgeBatches = pendingPurgeBatches
	this.RetryablePurgeCandidates = retryablePurgeCandidates
	this.DeadLetteredPurgeCandidates = deadLetteredPurgeCandidates
	this.ActivePurgeLeases = activePurgeLeases
	this.ExpiredPurgeLeases = expiredPurgeLeases
	return &this
}

// NewLifecycleBacklogSummaryWithDefaults instantiates a new LifecycleBacklogSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecycleBacklogSummaryWithDefaults() *LifecycleBacklogSummary {
	this := LifecycleBacklogSummary{}
	return &this
}

// GetArchiveBatches returns the ArchiveBatches field value
func (o *LifecycleBacklogSummary) GetArchiveBatches() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ArchiveBatches
}

// GetArchiveBatchesOk returns a tuple with the ArchiveBatches field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetArchiveBatchesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArchiveBatches, true
}

// SetArchiveBatches sets field value
func (o *LifecycleBacklogSummary) SetArchiveBatches(v int32) {
	o.ArchiveBatches = v
}

// GetPurgeBatches returns the PurgeBatches field value
func (o *LifecycleBacklogSummary) GetPurgeBatches() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PurgeBatches
}

// GetPurgeBatchesOk returns a tuple with the PurgeBatches field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetPurgeBatchesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PurgeBatches, true
}

// SetPurgeBatches sets field value
func (o *LifecycleBacklogSummary) SetPurgeBatches(v int32) {
	o.PurgeBatches = v
}

// GetPendingArchiveBatches returns the PendingArchiveBatches field value
func (o *LifecycleBacklogSummary) GetPendingArchiveBatches() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PendingArchiveBatches
}

// GetPendingArchiveBatchesOk returns a tuple with the PendingArchiveBatches field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetPendingArchiveBatchesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingArchiveBatches, true
}

// SetPendingArchiveBatches sets field value
func (o *LifecycleBacklogSummary) SetPendingArchiveBatches(v int32) {
	o.PendingArchiveBatches = v
}

// GetPendingPurgeBatches returns the PendingPurgeBatches field value
func (o *LifecycleBacklogSummary) GetPendingPurgeBatches() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PendingPurgeBatches
}

// GetPendingPurgeBatchesOk returns a tuple with the PendingPurgeBatches field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetPendingPurgeBatchesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingPurgeBatches, true
}

// SetPendingPurgeBatches sets field value
func (o *LifecycleBacklogSummary) SetPendingPurgeBatches(v int32) {
	o.PendingPurgeBatches = v
}

// GetRetryablePurgeCandidates returns the RetryablePurgeCandidates field value
func (o *LifecycleBacklogSummary) GetRetryablePurgeCandidates() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryablePurgeCandidates
}

// GetRetryablePurgeCandidatesOk returns a tuple with the RetryablePurgeCandidates field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetRetryablePurgeCandidatesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryablePurgeCandidates, true
}

// SetRetryablePurgeCandidates sets field value
func (o *LifecycleBacklogSummary) SetRetryablePurgeCandidates(v int32) {
	o.RetryablePurgeCandidates = v
}

// GetDeadLetteredPurgeCandidates returns the DeadLetteredPurgeCandidates field value
func (o *LifecycleBacklogSummary) GetDeadLetteredPurgeCandidates() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeadLetteredPurgeCandidates
}

// GetDeadLetteredPurgeCandidatesOk returns a tuple with the DeadLetteredPurgeCandidates field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetDeadLetteredPurgeCandidatesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeadLetteredPurgeCandidates, true
}

// SetDeadLetteredPurgeCandidates sets field value
func (o *LifecycleBacklogSummary) SetDeadLetteredPurgeCandidates(v int32) {
	o.DeadLetteredPurgeCandidates = v
}

// GetActivePurgeLeases returns the ActivePurgeLeases field value
func (o *LifecycleBacklogSummary) GetActivePurgeLeases() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActivePurgeLeases
}

// GetActivePurgeLeasesOk returns a tuple with the ActivePurgeLeases field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetActivePurgeLeasesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivePurgeLeases, true
}

// SetActivePurgeLeases sets field value
func (o *LifecycleBacklogSummary) SetActivePurgeLeases(v int32) {
	o.ActivePurgeLeases = v
}

// GetExpiredPurgeLeases returns the ExpiredPurgeLeases field value
func (o *LifecycleBacklogSummary) GetExpiredPurgeLeases() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiredPurgeLeases
}

// GetExpiredPurgeLeasesOk returns a tuple with the ExpiredPurgeLeases field value
// and a boolean to check if the value has been set.
func (o *LifecycleBacklogSummary) GetExpiredPurgeLeasesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiredPurgeLeases, true
}

// SetExpiredPurgeLeases sets field value
func (o *LifecycleBacklogSummary) SetExpiredPurgeLeases(v int32) {
	o.ExpiredPurgeLeases = v
}

func (o LifecycleBacklogSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecycleBacklogSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["archive_batches"] = o.ArchiveBatches
	toSerialize["purge_batches"] = o.PurgeBatches
	toSerialize["pending_archive_batches"] = o.PendingArchiveBatches
	toSerialize["pending_purge_batches"] = o.PendingPurgeBatches
	toSerialize["retryable_purge_candidates"] = o.RetryablePurgeCandidates
	toSerialize["dead_lettered_purge_candidates"] = o.DeadLetteredPurgeCandidates
	toSerialize["active_purge_leases"] = o.ActivePurgeLeases
	toSerialize["expired_purge_leases"] = o.ExpiredPurgeLeases
	return toSerialize, nil
}

func (o *LifecycleBacklogSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"archive_batches",
		"purge_batches",
		"pending_archive_batches",
		"pending_purge_batches",
		"retryable_purge_candidates",
		"dead_lettered_purge_candidates",
		"active_purge_leases",
		"expired_purge_leases",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLifecycleBacklogSummary := _LifecycleBacklogSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLifecycleBacklogSummary)

	if err != nil {
		return err
	}

	*o = LifecycleBacklogSummary(varLifecycleBacklogSummary)

	return err
}

type NullableLifecycleBacklogSummary struct {
	value *LifecycleBacklogSummary
	isSet bool
}

func (v NullableLifecycleBacklogSummary) Get() *LifecycleBacklogSummary {
	return v.value
}

func (v *NullableLifecycleBacklogSummary) Set(val *LifecycleBacklogSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleBacklogSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleBacklogSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleBacklogSummary(val *LifecycleBacklogSummary) *NullableLifecycleBacklogSummary {
	return &NullableLifecycleBacklogSummary{value: val, isSet: true}
}

func (v NullableLifecycleBacklogSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleBacklogSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
