/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleAlertActionActionEnum * `acknowledge` - acknowledge * `resolve` - resolve * `suppress` - suppress * `reopen` - reopen
type LifecycleAlertActionActionEnum string

// List of LifecycleAlertActionActionEnum
const (
	LIFECYCLEALERTACTIONACTIONENUM_ACKNOWLEDGE LifecycleAlertActionActionEnum = "acknowledge"
	LIFECYCLEALERTACTIONACTIONENUM_RESOLVE     LifecycleAlertActionActionEnum = "resolve"
	LIFECYCLEALERTACTIONACTIONENUM_SUPPRESS    LifecycleAlertActionActionEnum = "suppress"
	LIFECYCLEALERTACTIONACTIONENUM_REOPEN      LifecycleAlertActionActionEnum = "reopen"
)

// All allowed values of LifecycleAlertActionActionEnum enum
var AllowedLifecycleAlertActionActionEnumEnumValues = []LifecycleAlertActionActionEnum{
	"acknowledge",
	"resolve",
	"suppress",
	"reopen",
}

func (v *LifecycleAlertActionActionEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleAlertActionActionEnum(value)
	for _, existing := range AllowedLifecycleAlertActionActionEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleAlertActionActionEnum", value)
}

// NewLifecycleAlertActionActionEnumFromValue returns a pointer to a valid LifecycleAlertActionActionEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleAlertActionActionEnumFromValue(v string) (*LifecycleAlertActionActionEnum, error) {
	ev := LifecycleAlertActionActionEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleAlertActionActionEnum: valid values are %v", v, AllowedLifecycleAlertActionActionEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleAlertActionActionEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleAlertActionActionEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleAlertActionActionEnum value
func (v LifecycleAlertActionActionEnum) Ptr() *LifecycleAlertActionActionEnum {
	return &v
}

type NullableLifecycleAlertActionActionEnum struct {
	value *LifecycleAlertActionActionEnum
	isSet bool
}

func (v NullableLifecycleAlertActionActionEnum) Get() *LifecycleAlertActionActionEnum {
	return v.value
}

func (v *NullableLifecycleAlertActionActionEnum) Set(val *LifecycleAlertActionActionEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleAlertActionActionEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleAlertActionActionEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleAlertActionActionEnum(val *LifecycleAlertActionActionEnum) *NullableLifecycleAlertActionActionEnum {
	return &NullableLifecycleAlertActionActionEnum{value: val, isSet: true}
}

func (v NullableLifecycleAlertActionActionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleAlertActionActionEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
