/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// RecoveryEscalationStatusEnum * `open` - Open * `acknowledged` - Acknowledged * `resolved` - Resolved * `suppressed` - Suppressed
type RecoveryEscalationStatusEnum string

// List of RecoveryEscalationStatusEnum
const (
	RECOVERYESCALATIONSTATUSENUM_OPEN         RecoveryEscalationStatusEnum = "open"
	RECOVERYESCALATIONSTATUSENUM_ACKNOWLEDGED RecoveryEscalationStatusEnum = "acknowledged"
	RECOVERYESCALATIONSTATUSENUM_RESOLVED     RecoveryEscalationStatusEnum = "resolved"
	RECOVERYESCALATIONSTATUSENUM_SUPPRESSED   RecoveryEscalationStatusEnum = "suppressed"
)

// All allowed values of RecoveryEscalationStatusEnum enum
var AllowedRecoveryEscalationStatusEnumEnumValues = []RecoveryEscalationStatusEnum{
	"open",
	"acknowledged",
	"resolved",
	"suppressed",
}

func (v *RecoveryEscalationStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecoveryEscalationStatusEnum(value)
	for _, existing := range AllowedRecoveryEscalationStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecoveryEscalationStatusEnum", value)
}

// NewRecoveryEscalationStatusEnumFromValue returns a pointer to a valid RecoveryEscalationStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecoveryEscalationStatusEnumFromValue(v string) (*RecoveryEscalationStatusEnum, error) {
	ev := RecoveryEscalationStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecoveryEscalationStatusEnum: valid values are %v", v, AllowedRecoveryEscalationStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecoveryEscalationStatusEnum) IsValid() bool {
	for _, existing := range AllowedRecoveryEscalationStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecoveryEscalationStatusEnum value
func (v RecoveryEscalationStatusEnum) Ptr() *RecoveryEscalationStatusEnum {
	return &v
}

type NullableRecoveryEscalationStatusEnum struct {
	value *RecoveryEscalationStatusEnum
	isSet bool
}

func (v NullableRecoveryEscalationStatusEnum) Get() *RecoveryEscalationStatusEnum {
	return v.value
}

func (v *NullableRecoveryEscalationStatusEnum) Set(val *RecoveryEscalationStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryEscalationStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryEscalationStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryEscalationStatusEnum(val *RecoveryEscalationStatusEnum) *NullableRecoveryEscalationStatusEnum {
	return &NullableRecoveryEscalationStatusEnum{value: val, isSet: true}
}

func (v NullableRecoveryEscalationStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryEscalationStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
