/*
Credoxa Events API

Enterprise multi-tenant event infrastructure for Credoxa Cloud.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package credoxaevents

import (
	"encoding/json"
	"fmt"
)

// LifecycleBatchKindEnum * `archive` - Archive * `purge` - Purge
type LifecycleBatchKindEnum string

// List of LifecycleBatchKindEnum
const (
	LIFECYCLEBATCHKINDENUM_ARCHIVE LifecycleBatchKindEnum = "archive"
	LIFECYCLEBATCHKINDENUM_PURGE   LifecycleBatchKindEnum = "purge"
)

// All allowed values of LifecycleBatchKindEnum enum
var AllowedLifecycleBatchKindEnumEnumValues = []LifecycleBatchKindEnum{
	"archive",
	"purge",
}

func (v *LifecycleBatchKindEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LifecycleBatchKindEnum(value)
	for _, existing := range AllowedLifecycleBatchKindEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LifecycleBatchKindEnum", value)
}

// NewLifecycleBatchKindEnumFromValue returns a pointer to a valid LifecycleBatchKindEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLifecycleBatchKindEnumFromValue(v string) (*LifecycleBatchKindEnum, error) {
	ev := LifecycleBatchKindEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LifecycleBatchKindEnum: valid values are %v", v, AllowedLifecycleBatchKindEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LifecycleBatchKindEnum) IsValid() bool {
	for _, existing := range AllowedLifecycleBatchKindEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LifecycleBatchKindEnum value
func (v LifecycleBatchKindEnum) Ptr() *LifecycleBatchKindEnum {
	return &v
}

type NullableLifecycleBatchKindEnum struct {
	value *LifecycleBatchKindEnum
	isSet bool
}

func (v NullableLifecycleBatchKindEnum) Get() *LifecycleBatchKindEnum {
	return v.value
}

func (v *NullableLifecycleBatchKindEnum) Set(val *LifecycleBatchKindEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleBatchKindEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleBatchKindEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleBatchKindEnum(val *LifecycleBatchKindEnum) *NullableLifecycleBatchKindEnum {
	return &NullableLifecycleBatchKindEnum{value: val, isSet: true}
}

func (v NullableLifecycleBatchKindEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleBatchKindEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
